### ISSUE TITLE
Error starting up node and/or syncing TypeError: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by RomanZacharia** [ethereum/mist#1089]
#### System information
``````
Version: `0.0.0`
OS & Version: ubuntu 15.04
Node type: `eth/geth(default)`
``````
I followed the instructions on README.md to run mist for the development but the gui freezes (see screenshot) and it won't run with the following error in the terminal:
``````
$ electron .
[2016-08-12 20:39:27.265] [INFO] main - Running in production mode: false
[2016-08-12 20:39:27.536] [INFO] main - Starting in Mist mode
[2016-08-12 20:39:29.748] [INFO] Db - Creating db: /home/nerd/.config/Mist/mist.lokidb
[2016-08-12 20:39:29.948] [INFO] Db - Loading db: /home/nerd/.config/Mist/mist.lokidb
[2016-08-12 20:39:29.985] [INFO] Windows - Creating commonly-used windows
[2016-08-12 20:39:29.988] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-08-12 20:39:30.513] [INFO] updateChecker - Check for update...
[2016-08-12 20:39:46.557] [INFO] Windows - Create primary window: main, owner: notset
[2016-08-12 20:39:47.987] [INFO] Windows - Create primary window: splash, owner: notset
[2016-08-12 20:39:54.381] [INFO] updateChecker - App is up-to-date.
[2016-08-12 20:39:56.235] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-08-12 20:40:01.302] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
null
[2016-08-12 20:40:02.419] [ERROR] main - Error starting up node and/or syncing TypeError: Cannot read property 'trim' of null
    at Q.try (/home/nerd/coding/mist/main.js:335:49)
    at tryCatcher (/home/nerd/coding/mist/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/nerd/coding/mist/node_modules/bluebird/js/release/method.js:39:29)
    at Window.kickStart (/home/nerd/coding/mist/main.js:332:14)
    at emitNone (events.js:86:13)
    at Window.emit (events.js:185:7)
    at EventEmitter.Window.webContents.once (/home/nerd/coding/mist/modules/windows.js:71:18)
    at EventEmitter.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
``````

![image](https://cloud.githubusercontent.com/assets/6650934/17632459/05f9530c-60d1-11e6-9015-7b8affb4a9f1.png)

**Comment by gttnb** [comment]
Are you able to solve this error ?. I also got same issue.
