### ISSUE TITLE
Error: Your nodes need to be updated.

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#1214]
#### System information
``````
Version: `0.8.3-dev`
OS & Version: linux 4.7.4 (ArchLinux)
Node type: `none`
``````

This is a follow-up of https://github.com/ethereum/mist/issues/987, esp. https://github.com/ethereum/mist/issues/987#issuecomment-235411229 and was supposed to be fixed in https://github.com/ethereum/mist/pull/1048 and relates to the discussion in https://github.com/ethereum/mist/issues/264

    gulp mist --platform linux

Fails with:

    [10:04:36] Starting 'copy-app-source-files'...
    YOUR NODES NEED TO BE UPDATED run $ gulp update-nodes
    [10:04:36] 'copy-app-source-files' errored after 89 μs
    [10:04:36] Error: YOUR NODES NEED TO BE UPDATED run $ gulp update-nodes
        at Gulp.<anonymous> (/home/user/some/path/mist-git/gulpfile.js:265:15)
        at module.exports (/home/user/some/path/mist-git/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/home/user/some/path/mist-git/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/home/user/some/path/mist-git/node_modules/orchestrator/index.js:214:10)
        at /home/user/some/path/mist-git/node_modules/orchestrator/index.js:279:18
        at finish (/home/user/some/path/mist-git/node_modules/orchestrator/lib/runTask.js:21:8)
        at cb (/home/user/some/path/mist-git/node_modules/orchestrator/lib/runTask.js:29:3)
        at /home/user/some/path/mist-git/node_modules/del/index.js:54:4
        at module.exports (/home/user/some/path/mist-git/node_modules/each-async/index.js:22:3)
        at /home/user/some/path/mist-git/node_modules/del/index.js:40:3
        at /home/user/some/path/mist-git/node_modules/globby/index.js:74:3
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:726:13
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:52:16
        at done (/home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:246:17)
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:44:16
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:723:17
    [10:04:36] 'mist' errored after 18 ms
    [10:04:36] Error in plugin 'run-sequence(copy-app-source-files)'
    Message:
        YOUR NODES NEED TO BE UPDATED run $ gulp update-nodes
    Stack:
    Error: YOUR NODES NEED TO BE UPDATED run $ gulp update-nodes
        at Gulp.<anonymous> (/home/user/some/path/mist-git/gulpfile.js:265:15)
        at module.exports (/home/user/some/path/mist-git/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/home/user/some/path/mist-git/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/home/user/some/path/mist-git/node_modules/orchestrator/index.js:214:10)
        at /home/user/some/path/mist-git/node_modules/orchestrator/index.js:279:18
        at finish (/home/user/some/path/mist-git/node_modules/orchestrator/lib/runTask.js:21:8)
        at cb (/home/user/some/path/mist-git/node_modules/orchestrator/lib/runTask.js:29:3)
        at /home/user/some/path/mist-git/node_modules/del/index.js:54:4
        at module.exports (/home/user/some/path/mist-git/node_modules/each-async/index.js:22:3)
        at /home/user/some/path/mist-git/node_modules/del/index.js:40:3
        at /home/user/some/path/mist-git/node_modules/globby/index.js:74:3
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:726:13
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:52:16
        at done (/home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:246:17)
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:44:16
        at /home/user/some/path/mist-git/node_modules/globby/node_modules/async/lib/async.js:723:17

As explained in the discussion above, I relate on the system wide installations of geth or eth and therefore do not want to _update_ my nodes shipped by mist. Please allow a flag to build Mist without nodes. Thanks.

**Comment by 5chdn** [comment]
Ah, I just discovered https://github.com/ethereum/mist/pull/1064. Let me test this.

**Comment by 5chdn** [comment]
Ok I was a bit rushed with this ticket. This is a exact duplicate of #264. Tested #1064 and confirmed working with ArchLinux 4.7.4.
