### ISSUE TITLE
Ethereum Wallet crashes while sync 

### ISSUE THREAD

**Issue by schwitin** [ethereum/mist#1619]
#### System information
``````
Version: `0.8.8`
OS & Version: debian testing
Node type: geth(?) 
``````

#### log
```
[2017-01-29 13:29:09.750] [INFO] Sockets/node-ipc - Disconnecting...
/opt/Ethereum Wallet/resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS[

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at Pipe.onread (net.js:564:26)
```

[node.logs.zip](https://github.com/ethereum/mist/files/737544/node.logs.zip)

**Comment by evertonfraga** [comment]
Should be fixed.
