### ISSUE TITLE
Ethereum Wallet -- connection lost while Sync

### ISSUE THREAD

**Issue by schwitin** [ethereum/mist#1624]
#### System information
``````
Version: `0.8.8`
OS & Version: debian testing
Node type: `geth(default)`
``````
The Ethereum Wallet was running about 8h and synced 2% of block chain.  In the console log I see following repeating every 5 seconds.

```python 
2017-01-30 17:50:09.280] [INFO] Sockets/2 - Connect to {"path":"/home/stalker/.ethereum/geth.ipc"}
[2017-01-30 17:50:09.289] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2017-01-30 17:50:10.289] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2017-01-30 17:50:11.290] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2017-01-30 17:50:12.290] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2017-01-30 17:50:13.291] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2017-01-30 17:50:14.281] [ERROR] Sockets/2 - Connection failed (5000ms elapsed)
[2017-01-30 17:50:14.282] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.282] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.283] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.283] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.284] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.284] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.284] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.285] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.285] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.286] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.286] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.286] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.287] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.287] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.288] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-01-30 17:50:14.288] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
...
```

**Comment by luclu** [comment]
@schwitin your backend node seem to have crashed. Do you still have the `node.log` as described in these instructions: https://github.com/ethereum/mist/issues/new?
