### ISSUE TITLE
Error: ENOENT: renaming .config/Mist/mist.lokidb~ to .config/Mist/mist.lokidb

### ISSUE THREAD

**Issue by atfornes** [ethereum/mist#1654]
Mist closed after an unexpected error, that was logged to the terminal as follows:

```javascript
/home/antonio/Descargas/linux-unpacked/resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filenam

Error: ENOENT: no such file or directory, rename '/home/antonio/.config/Mist/mist.lokidb~' -> '/home/antonio/.config/Mist/mist.lokidb'
    at Error (native)
```

After this unexpected error, an attempt to start mist again from command line gives the following error messages:

```javascript
[2017-02-10 13:14:17.928] [INFO] main - Running in production mode: true
[2017-02-10 13:14:18.150] [INFO] main - Starting in Mist mode
[2017-02-10 13:14:18.888] [INFO] Db - Loading db: /home/antonio/.config/Mist/mist.lokidb
[2017-02-10 13:14:18.927] [ERROR] Db - SyntaxError: Unexpected token } in JSON at position 7433
    at Object.parse (native)
    at Loki.loadJSON (/home/antonio/Descargas/linux-unpacked/resources/app.asar/node_modules/lokijs/src/lokijs.js:1370:42)
    at loadDatabaseCallback (/home/antonio/Descargas/linux-unpacked/resources/app.asar/node_modules/lokijs/src/lokijs.js:2120:20)
    at readFileCallback (/home/antonio/Descargas/linux-unpacked/resources/app.asar/node_modules/lokijs/src/lokijs.js:1997:15)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
[2017-02-10 13:14:19.001] [ERROR] main - Error: Error instantiating db
    at autoloadCallback (/home/antonio/Descargas/linux-unpacked/resources/app.asar/modules/db.js:43:32)
    at loadDatabaseCallback (/home/antonio/Descargas/linux-unpacked/resources/app.asar/node_modules/lokijs/src/lokijs.js:2123:15)
    at readFileCallback (/home/antonio/Descargas/linux-unpacked/resources/app.asar/node_modules/lokijs/src/lokijs.js:1997:15)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
[2017-02-10 13:14:19.002] [INFO] main - Defer quitting until sockets and node are shut down
[2017-02-10 13:14:19.002] [INFO] Sockets - Destroy all sockets
[2017-02-10 13:14:19.002] [INFO] Sockets/node-ipc - Disconnecting...
[2017-02-10 13:14:19.004] [ERROR] main - Error shutting down sockets
[2017-02-10 13:14:19.506] [INFO] main - About to quit...

```

#### System information
``````
Version: `0.8.9`
OS & Version: Linux (Debian 3.16.39-1)
Node type: `geth`
``````

Please find attached the zipped logs
[MistLogs.zip](https://github.com/ethereum/mist/files/766629/MistLogs.zip)

**Comment by stevenkcolin** [comment]
I have the same problem, 

*******************************************************************************************************************************
[2017-02-11 11:37:51.568] [ERROR] main - UNCAUGHT EXCEPTION { Error: ENOENT: no such file or directory, rename '/Users/linchen/Library/Application Support/Mist/mist.lokidb~' -> '/Users/linchen/Library/Application Support/Mist/mist.lokidb'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/Users/linchen/Library/Application Support/Mist/mist.lokidb~',
  dest: '/Users/linchen/Library/Application Support/Mist/mist.lokidb' }
[2017-02-11 11:37:51.802] [INFO] main - Defer quitting until sockets and node are shut down
[2017-02-11 11:37:51.803] [INFO] Sockets - Destroy all sockets
[2017-02-11 11:37:51.804] [INFO] Sockets/2 - Disconnecting...
[2017-02-11 11:37:51.805] [INFO] Sockets/3 - Disconnecting...
[2017-02-11 11:37:51.805] [INFO] Sockets/4 - Disconnecting...
[2017-02-11 11:37:51.805] [INFO] Sockets/5 - Disconnecting...
[2017-02-11 11:37:51.805] [INFO] Sockets/6 - Disconnecting...
[2017-02-11 11:37:51.805] [INFO] Sockets/7 - Disconnecting...
[2017-02-11 11:37:51.806] [INFO] Sockets/8 - Disconnecting...
[2017-02-11 11:37:51.806] [INFO] Sockets/9 - Disconnecting...

**Comment by luclu** [comment]
pinging @frozeman
