### ISSUE TITLE
[oboe-node] Error: Cannot write after close

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#2141]
While switching to ropsten testnet (geth `1.5.9`).

```javascript
[2017-04-13 02:28:34.553] [ERROR] Sockets/node-ipc - Socket response error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown:
   Error: Cannot write after close
   Ln: 10
   Col: 0
   Chr: undefined
       at Error (native)
       at emitError (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:188:7)
       at Socket._socket.on (/Users/ich/github/mist/modules/sockets/web3Ipc.js:49:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:543:20) }
[2017-04-13 02:28:34.564] [ERROR] NodeSync - Node crashed while syncing? { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown:
   Error: Cannot write after close
   Ln: 10
   Col: 0
   Chr: undefined
       at Error (native)
       at emitError (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:188:7)
       at Socket._socket.on (/Users/ich/github/mist/modules/sockets/web3Ipc.js:49:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:543:20) }
[2017-04-13 02:28:34.564] [ERROR] NodeSync - Sync error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown:
   Error: Cannot write after close
   Ln: 10
   Col: 0
   Chr: undefined
       at Error (native)
       at emitError (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:188:7)
       at Socket._socket.on (/Users/ich/github/mist/modules/sockets/web3Ipc.js:49:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:543:20) }
[2017-04-13 02:28:34.564] [ERROR] main - Error syncing node { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown:
   Error: Cannot write after close
   Ln: 10
   Col: 0
   Chr: undefined
       at Error (native)
       at emitError (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:188:7)
       at Socket._socket.on (/Users/ich/github/mist/modules/sockets/web3Ipc.js:49:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:543:20) }
[2017-04-13 02:28:34.564] [INFO] NodeSync - Sync loop ended
[2017-04-13 02:28:34.564] [ERROR] main - Error starting up node and/or syncing { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown:
   Error: Cannot write after close
   Ln: 10
   Col: 0
   Chr: undefined
       at Error (native)
       at emitError (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/Users/ich/github/mist/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:188:7)
       at Socket._socket.on (/Users/ich/github/mist/modules/sockets/web3Ipc.js:49:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:543:20) }

```

**Comment by luclu** [comment]
might have been a debug issue, will close for now.
