### ISSUE TITLE
Starting mist in light mode does not work since geth 1.6.0 (conflicting node options?)

### ISSUE THREAD

**Issue by ronazulay** [ethereum/mist#2254]
#### System information
``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `geth 1.6.0-stable-facc47cb`
``````
Hi everyone,

I can no longer start mist in light mode since geth was upgraded to 1.6.0.
I usually run mist with the option --node-light but since Geth 1.6.0 I get an error at startup (see attached screenshot).
I have also tried using --node-syncmode light.

Cause seems to be Mist supplying both the --fast and the --syncmode light option when starting Geth:

```
[2017-05-12 21:53:06.312] [DEBUG] EthereumNode - Custom node options [ '--syncmode', 'light' ]
[2017-05-12 21:53:06.312] [TRACE] EthereumNode - Spawn D:\Ethereum\Bin\geth.exe [ '--testnet',
  '--fast',
  '--ipcpath',
  '\\\\.\\pipe\\geth.ipc',
  '--syncmode',
  'light' ]
[2017-05-12 21:53:06.400] [TRACE] EthereumNode - Got stdout data
[2017-05-12 21:53:06.401] [TRACE] EthereumNode - NODE: Fatal: flags --fast, --syncmode can't be used at the same time
```

Workaround for now is starting geth.exe first and then starting Mist.

![mist-error](https://cloud.githubusercontent.com/assets/40405/26014793/6cbca2f6-375e-11e7-8ec2-8cb4950ebd39.png)

[trace.txt](https://github.com/ethereum/mist/files/997826/trace.txt)

**Comment by browning99** [comment]
I have this problem too but I suspect it came from the multiple versions that are kept side-by-side. I'm in the process of removing everything since I was testing I tried multiple clients, node types etc.
I'll restart from scratch (restored wallets excepted)

**Comment by luclu** [comment]
@ronazulay thank you for pointing this out. 
Apparently the hardcoded `--fast` flag in [ethereumNode.js#L356](https://github.com/ethereum/mist/blob/develop/modules/ethereumNode.js#L356) collides with geth's new `--syncmode [fast, full, light]` causing geth to quit.

This behaviour should be fixed with Mist next version as PR https://github.com/ethereum/mist/pull/2093 is expected to be merged. This PR will remove the hardcoded flags.

Unfortunately the current situation will require you to either:
- launch an external instance of geth with your desired flags
- downgrade geth to `<1.6.0`
- wait for the next release
- recompile the Mist with the linked PR (not recommended)

**Comment by ronazulay** [comment]
Cool, thanks. I will wait for the next release 👍

**Comment by Tectract** [comment]
Is this still open? Is it possible to run Mist in light-client mode somehow? 

myetherwallet is garbage. We need a functional light client.

**Comment by pparent76** [comment]
Unfortunately the light client mode don't seem to work better in 0.9 than it was working on 0.8.9:
```

Node type: geth
Network: main
Platform: linux (Architecure x64)

...Fatal: flags --fast, --light can't be used at the same time
```
```

[2017-07-27 11:28:04.557] [INFO] EthereumNode - Node type: geth
[2017-07-27 11:28:04.557] [INFO] EthereumNode - Network: main
[2017-07-27 11:28:04.557] [INFO] EthereumNode - Start node: geth main
[2017-07-27 11:28:04.558] [INFO] EthereumNode - Start node using /home/pparent/.config/Ethereum Wallet/binaries/Geth/unpacked/geth
[2017-07-27 11:28:07.596] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2017-07-27 11:28:07.597] [INFO] EthereumNode - Started node successfully: geth main
[2017-07-27 11:28:07.598] [INFO] Sockets/node-ipc - Connect to {"path":"/home/pparent/.ethereum/geth.ipc"}
[2017-07-27 11:28:07.599] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:08.600] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:09.601] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:10.602] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:11.604] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:12.605] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:13.607] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:14.608] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:15.610] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:16.611] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:17.613] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:18.614] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:19.616] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:20.617] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:21.619] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:22.629] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:23.631] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:24.633] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:25.634] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:26.636] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:27.638] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:28.639] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:29.640] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:30.642] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:31.643] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:32.645] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:33.647] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:34.649] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:35.650] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:36.652] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-27 11:28:37.599] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2017-07-27 11:28:37.600] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-07-27 11:28:37.620] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-07-27 11:28:37.621] [ERROR] main - Error starting up node and/or syncing Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by SB2502** [comment]
I am having the same error using Mist 0.9 on MacOS

```
Node type: geth
Network: main
Platform: darwin (Architecure x64)

...Fatal: flags --fast, --light can't be used at the same time
```

**Comment by rootk1d** [comment]
After several times trying and reading similiar open issues. I found a fix for my case.
I had created a shortcut that has always been using --light to start geth. Someday it stopped working.
I only changed it to --syncmode light and it started syncing immediatley.
Currently I am using the latest dev build.

**Comment by zamicol** [comment]
@rootk1d solution solved the problem for me.

**Comment by marksaitis** [comment]
Can somebody just sort this shit out? Seriously ppl, I only want to launch the damn thing on mac with one click so it just goes to a light option. This also should be 1st item in ethereum wallet documentation. There are 100 guides on geth parameter passing, but not about mac ethereum wallet parameter passing or forcing this to be a default.

**Comment by zamicol** [comment]
@marksaitis It's under pretty heavy development right now.  I would expect there to be a few bugs.  

This should be pretty easy to do from your terminal: 

> geth --syncmode light

I've put that in my bash profile as an alias to `geth` for now.  You should also be able to make a Mac icon to do that for you as well.

**Comment by Tectract** [comment]
I think the solution to this ticket should be:
"update the docs to reflect the --syncmode light command usage, and bash startup settings for that"

That way people will not need to keep coming back here for rootk1d's solution.

**Comment by ronazulay** [comment]
The solution by rootk1d is only a workaround, the bug as reported is still present in Mist 0.9.0.

You should not need to start geth manually to use light mode, you only pass the --node-syncmode light option to Mist and geth will be started automatically in the background by Mist.

Hopefully this will be fixed in 0.9.1 as indicated by @evertonfraga.

**Comment by evertonfraga** [comment]
The main reason the light client isn't the default option is that it is rather slow to retrieve Logs from history — opposed to a full node, where all logs are local. Let's keep in mind its API is transitioning from v1 to v2.

I know you all just want to double-click and start transacting, but please take a look at the whole environment state before any quick judgment. 

Anyway, we're testing the light client along with the wallet to understand the current bottlenecks and hopefully will be released as an experimental feature soon.

**Comment by awishformore** [comment]
That has nothing to do at all with the fact that you actually *can't* pass along the `node-syncmode light` flag to Mist, because it always uses the fast sync option as well. Just simply fix it so it doesn't use the fast flag when it uses the light flag, it should not be a big deal no fix something as annoying as this. How do I explain to my non-techie friends they should first manually install geth or navigate to the geth unpacked folder and then manually launch geth with light mode and only then launch Mist to make it work for non-power users? That's just not acceptable. I want to be able to simply change one little flag to the Mist shortcut to configure their wallet into light mode by default.

**Comment by marksaitis** [comment]
thumbs up

**Comment by HaleTom** [comment]
As a work-around for linux users, based on [@pparent76's script](https://github.com/ethereum/mist/issues/2372#issuecomment-318395351), I came up with:

```
#!/bin/bash
# Work around for issues:
# https://github.com/ethereum/mist/issues/2254
# https://github.com/ethereum/mist/issues/2372
# https://github.com/ethereum/mist/issues/2999
set -eu # For script robustness
geth=$(which geth)
mist=$(which mist) # Change to explicit path if you call this script "mist"

# Use pidof as procps' pgrep is broken:
# sleep 1& pgrep -ax '^sleep$' should return null
if ! geth_pid=$(pidof geth); then
  echo "Starting $geth."
  "$geth" --syncmode light &
else
  echo "Geth is already running with PID(s): $geth_pid"
fi

if ! mist_pid=$(pidof mist); then
  echo "Starting $mist."
  "$mist" --light-node
else
  echo "Mist is already running with PID(s): $mist_pid"
fi
```

Call the script "emist" so it doesn't recursively call itself :)

**Comment by evertonfraga** [comment]
We've enabled the Light Client on Mist 0.9.1 under Develop menu, as an experimental feature.

**Comment by fogbridgegit** [comment]
im kinda zen with the whole thing.  yeah there could be better docs but they all heads down building this thing, or something.  i figure all these little hiccups slows everything down cause blockchain is white hot everybody wants the future now.  we take it step by step  #sipsTea
