### ISSUE TITLE
cannot create contract or send ETH

### ISSUE THREAD

**Issue by philejmath** [ethereum/mist#2406]
whenever I try to send or create a contract geth exits with this error after I type in my password. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46ee985]

goroutine 598 [running]:
github.com/ethereum/go-ethereum/internal/ethapi.(*AddrLocker).lock(0x0, 0xe03fe50f6920ecfa, 0x4cf61def1fb3a451, 0xc4c46a51e6, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/addrlock.go:32 +0x35
github.com/ethereum/go-ethereum/internal/ethapi.(*AddrLocker).LockAddr(0x0, 0xe03fe50f6920ecfa, 0x4cf61def1fb3a451, 0xc46a51e6)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/addrlock.go:47 +0x3f
github.com/ethereum/go-ethereum/internal/ethapi.(*PrivateAccountAPI).SendTransaction(0xc421a788c0, 0x50938c0, 0xc4223440c0, 0xe03fe50f6920ecfa, 0x4cf61def1fb3a451, 0xc46a51e6, 0xc422a03f80, 0xc422a03f40, 0xc422a03f60, 0xc422a03fa0, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:330 +0x587
reflect.Value.call(0xc421b1ef80, 0xc42000edf0, 0x13, 0x4a99c97, 0x4, 0xc422b27020, 0x4, 0x4, 0x0, 0x49cbc00, ...)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc421b1ef80, 0xc42000edf0, 0x13, 0xc422b27020, 0x4, 0x4, 0x2, 0x2, 0x0)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc421a85d70, 0x50938c0, 0xc4223440c0, 0x5097f40, 0xc42230e460, 0xc422b051f0, 0xc42117cac0, 0x2d4d72e21f87475, 0x443a333)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:328 +0x758
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc421a85d70, 0x50938c0, 0xc4223440c0, 0x5097f40, 0xc42230e460, 0xc422b051f0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:350 +0x1ba
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc422336190, 0xc421a85d70, 0xc4223361a0, 0x5097f40, 0xc42230e460, 0xc42110fbe0, 0x1, 0x1, 0xc421aaee00)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0xa9
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0x352
```

#### System information
``````
Version: `0.0.0`
OS & Version: osx
Node type: `geth(default)`
``````

**Comment by vandenbergmp** [comment]
have a similar issue

**Comment by evertonfraga** [comment]
Related to https://github.com/ethereum/mist/issues/999. pinging @fjl @bas-vk @karalabe.

**Comment by karalabe** [comment]
You are running Geth 1.6.3, which had this regression. Please update to Geth 1.6.5 (it was released the same day).
