### ISSUE TITLE
Can't connect to rpc

### ISSUE THREAD

**Issue by kenken64** [ethereum/mist#2409]
[2017-06-02 03:00:53.217] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-02 03:00:54.219] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-02 03:00:55.220] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-02 03:00:56.217] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2017-06-02 03:00:56.218] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2017-06-02 03:00:56.220] [INFO] EthereumNode - Node type: geth
[2017-06-02 03:00:56.221] [INFO] EthereumNode - Network: main
[2017-06-02 03:00:56.221] [INFO] EthereumNode - Start node: geth main
[2017-06-02 03:00:56.222] [INFO] EthereumNode - Start node using C:\Users\Kenneth\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe
[2017-06-02 03:00:56.360] [ERROR] EthereumNode - Failed to start node Error: Geth error: fatal: error starting protocol stack: the process cannot access the file because it is being used by another process.

    at Socket.proc.stdout.on (F:\win-unpacked\resources\app.asar\modules\ethereumNode.js:409:45)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
[2017-06-02 03:00:56.373] [ERROR] EthereumNode - Failed to start node Error: Geth error: fatal: error starting protocol stack: the process cannot access the file because it is being used by another process.

    at Socket.proc.stdout.on (F:\win-unpacked\resources\app.asar\modules\ethereumNode.js:409:45)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
[2017-06-02 03:00:56.374] [ERROR] main - Error starting up node and/or syncing Error: Geth error: fatal: error starting protocol stack: the process cannot access the file because it is being used by another process.

    at Socket.proc.stdout.on (F:\win-unpacked\resources\app.asar\modules\ethereumNode.js:409:45)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
[2017-06-02 03:01:06.027] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2017-06-02 03:01:06.028] [INFO] main - Defer quitting until sockets and node are shut down
[2017-06-02 03:01:06.031] [INFO] Sockets - Destroy all sockets
[2017-06-02 03:01:06.032] [INFO] Sockets/3 - Disconnecting...
[2017-06-02 03:01:06.033] [INFO] Sockets/node-ipc - Disconnecting...
[2017-06-02 03:01:06.035] [ERROR] main - Error shutting down sockets
[2017-06-02 03:01:06.536] [INFO] main - About to quit...
[2017-06-02 03:01:06.544] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2017-06-02 03:01:06.572] [INFO] Windows - All primary windows closed/invisible, so quitting app...

**Comment by rohithpr** [comment]
`mist --rpc http://localhost:8545` works for me when I'm using testrpc.
