### ISSUE TITLE
Mist crashes after authorizing a dapp. Mist is closing immediately after authorizing the oasisdex dapp.

### ISSUE THREAD

**Issue by adammpkins** [ethereum/mist#2448]
#### System information
``````
Version: `08.10`
OS & Version: windows 10
Node type: `geth
[node.zip](https://github.com/ethereum/mist/files/1055959/node.zip)
(default)`
``````

http://screencast-o-matic.com/watch/cb11bHX77O - Error in action

**Comment by evertonfraga** [comment]
That's interesting, thanks for reporting. 

Can I ask you to open Mist in a debug mode? 

- open cmd.exe
- change the directory to a Mist shortcut or executable (`cd ...\...\`)
- execute either `Mist.exe` or `Mist.lnk`

and paste here what's shown at the console window after the crash. I'm really interested on this.

Thanks again.

**Comment by adammpkins** [comment]
[2017-06-06 15:33:33.395] [INFO] Sockets/3 - Disconnecting...
[2017-06-06 15:33:33.398] [ERROR] Sockets/6 - { Error: write EOF
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14) code: 'EOF', errno: 'EOF',
syscall: 'write' }
[2017-06-06 15:33:33.405] [INFO] Sockets/6 - Disconnecting...
[2017-06-06 15:33:33.408] [ERROR] Sockets/2 - { Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at onwrite (_stream_writable.js:346:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:807:12) code: 'EPIPE', errno: 'EPIPE',
syscall: 'write' }
[2017-06-06 15:33:33.409] [INFO] Sockets/2 - Disconnecting...
[2017-06-06 15:33:33.410] [ERROR] main - UNCAUGHT EXCEPTION Error: This
socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at onwrite (_stream_writable.js:346:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:807:12)

**Comment by evertonfraga** [comment]
Don't you have the full log, or at least more pages out of it?

I think you can enable this behavior on your cmd.app. Here's a guide: https://superuser.com/questions/161125/how-do-i-enable-scrolling-in-windows-command-prompt

thanks again!

**Comment by evertonfraga** [comment]
I am closing this issue due to inactivity. **Please feel free** to reopen should you still have some considerations about it.
