### ISSUE TITLE
GUI freezes on some menu links

### ISSUE THREAD

**Issue by tinypenguin** [ethereum/mist#2479]
#### System information
``````
Version: `0.8.10`
OS & Version: Linux Mint ,4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Node type: `geth(default)`
``````

Downloaded and installed ethereumwall et 
Ethereum-Wallet-linux64-0-8-10.deb

If I click on Accounts->Backup->Accounts, Accounts->Backup->AppData, Develop-Show log file

Application just freezes.

> 
> [2017-06-10 17:11:40.167] [DEBUG] (ui: popupWindow) - Setting language
> [2017-06-10 17:11:40.206] [DEBUG] Windows/about - Content loaded, id: 4
> [2017-06-10 17:11:40.206] [DEBUG] Windows/about - Show
> [2017-06-10 17:11:40.218] [DEBUG] Windows/loading - Hide
> [2017-06-10 17:11:58.583] [INFO] (ui: browser) - Node started syncing, stopping app operation
> [2017-06-10 17:12:01.085] [INFO] (ui: browser) - Restart app operation again
> [2017-06-10 17:12:01.085] [INFO] (ui: browser) - Connect to node...
> ^C[2017-06-10 17:17:33.708] [DEBUG] Sockets/3 - Got "end" event
> [2017-06-10 17:17:33.710] [DEBUG] ipcProviderBackend - Destroy socket connection due to event: end, id=3
> [2017-06-10 17:17:33.711] [INFO] Sockets/3 - Disconnecting...
> [2017-06-10 17:17:33.711] [DEBUG] Sockets - Remove socket, id=3
> [2017-06-10 17:17:33.711] [DEBUG] Sockets/2 - Got "end" event
> [2017-06-10 17:17:33.711] [DEBUG] ipcProviderBackend - Destroy socket connection due to event: end, id=2
> [2017-06-10 17:17:33.712] [INFO] Sockets/2 - Disconnecting...
> [2017-06-10 17:17:33.712] [DEBUG] Sockets - Remove socket, id=2
> [2017-06-10 17:17:33.712] [DEBUG] Sockets/node-ipc - Got "end" event
> [2017-06-10 17:17:33.712] [DEBUG] Sockets/4 - Got "end" event
> [2017-06-10 17:17:33.712] [DEBUG] ipcProviderBackend - Destroy socket connection due to event: end, id=4
> [2017-06-10 17:17:33.712] [INFO] Sockets/4 - Disconnecting...
> [2017-06-10 17:17:33.713] [DEBUG] Sockets - Remove socket, id=4
> [2017-06-10 17:17:33.714] [DEBUG] ipcProviderBackend - Connecting socket 2
> [2017-06-10 17:17:33.715] [DEBUG] Settings - IPC path: /home/ivo/.ethereum/geth.ipc
> [2017-06-10 17:17:33.715] [INFO] Sockets/2 - Connect to {"path":"/home/ivo/.ethereum/geth.ipc"}
> [2017-06-10 17:17:33.715] [DEBUG] Sockets/2 - Resetting socket
> [2017-06-10 17:17:33.717] [DEBUG] Sockets/2 - Connecting...
> [2017-06-10 17:17:33.717] [DEBUG] Sockets/2 - Will wait 5000ms for connection to happen.
> [2017-06-10 17:17:33.718] [DEBUG] Sockets/4 - Disconnected as expected
> [2017-06-10 17:17:33.718] [WARN] Sockets/2 - Unexpectedly disconnected
> [2017-06-10 17:17:33.718] [DEBUG] Sockets/3 - Disconnected as expected
> [2017-06-10 17:17:33.772] [INFO] main - Defer quitting until sockets and node are shut down
> [2017-06-10 17:17:33.772] [INFO] Sockets - Destroy all sockets
> [2017-06-10 17:17:33.772] [DEBUG] Sockets - Remove socket, id=node-ipc
> [2017-06-10 17:17:33.772] [INFO] Sockets/node-ipc - Disconnecting...
> [2017-06-10 17:17:33.780] [ERROR] Sockets/2 - { Error: connect ENOENT /home/ivo/.ethereum/geth.ipc
>     at Object.exports._errnoException (util.js:1026:11)
>     at exports._exceptionWithHostPort (util.js:1049:20)
>     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'connect',
>   address: '/home/ivo/.ethereum/geth.ipc' }
> [2017-06-10 17:17:33.798] [DEBUG] ipcProviderBackend - Destroy socket connection due to event: error, id=2
> [2017-06-10 17:17:33.798] [DEBUG] Sockets - Remove socket, id=2
> [2017-06-10 17:17:33.822] [ERROR] (ui: browser) - IPC Connection Error {"code":"ENOENT","errno":"ENOENT","syscall":"connect","address":"/home/ivo/.ethereum/geth.ipc"}
> [2017-06-10 17:17:33.823] [ERROR] (ui: browser) - IPC Connection Error {"code":"ENOENT","errno":"ENOENT","syscall":"connect","address":"/home/ivo/.ethereum/geth.ipc"}
> [2017-06-10 17:17:33.823] [ERROR] (ui: browser) - IPC Connection Error {"code":"ENOENT","errno":"ENOENT","syscall":"connect","address":"/home/ivo/.ethereum/geth.ipc"}
> [2017-06-10 17:17:34.274] [INFO] NodeSync - Ethereum node stopping, so stop sync
> [2017-06-10 17:17:34.274] [DEBUG] NodeSync - Sync not already in progress.
> [2017-06-10 17:17:34.275] [INFO] ipcProviderBackend - Ethereum node stopping, disconnecting sockets
> [2017-06-10 17:17:34.275] [INFO] EthereumNode - Stopping existing node: geth main
> 
> [2017-06-10 17:17:38.773] [WARN] Sockets - Disconnection timed out, closing socket anyway...
> ^C
>

**Comment by NinjaTurtle007** [comment]
I have the same problem. Did you manage to find a solution?
