### ISSUE TITLE
Build on Win10 KO at meteor start 

### ISSUE THREAD

**Issue by charly37** [ethereum/mist#2491]
#### System information
``````
Version: `MASTER (clone 11 June)`
OS & Version: windows 10
Node type: `geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Did not find a similar ticket

I m facing issue when trying to build the project on windows 10. I installed the mentioned dependancies but when trying to start the meteor framework I m facing the following error message:
```
C:\Code\mist3\interface>meteor --no-release-check
[[[[[ C:\Code\mist3\interface ]]]]]

=> Started proxy.
=> Started MongoDB.
W20170611-19:33:02.515(-4)? (STDERR) C:\Users\charl\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170611-19:33:02.674(-4)? (STDERR)                                            throw(ex);
W20170611-19:33:02.675(-4)? (STDERR)                                            ^
W20170611-19:33:02.675(-4)? (STDERR)
W20170611-19:33:02.676(-4)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'C:\Code\mist3\interface\.meteor\local\build\programs\server\undefined\public'
W20170611-19:33:02.676(-4)? (STDERR)     at Error (native)
W20170611-19:33:02.677(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:794:18)
W20170611-19:33:02.677(-4)? (STDERR)     at packages/tap_i18n-bundler/i18n-bundler.coffee:18:12
W20170611-19:33:02.678(-4)? (STDERR)     at Function.time (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:301:28)
W20170611-19:33:02.678(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:304:13
W20170611-19:33:02.679(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:345:5
W20170611-19:33:02.679(-4)? (STDERR)     at Function.run (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:480:12)
W20170611-19:33:02.680(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:343:11
=> Exited with code: 1
W20170611-19:33:06.906(-4)? (STDERR) C:\Users\charl\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170611-19:33:06.907(-4)? (STDERR)                                            throw(ex);
W20170611-19:33:06.907(-4)? (STDERR)                                            ^
W20170611-19:33:06.908(-4)? (STDERR)
W20170611-19:33:06.909(-4)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'C:\Code\mist3\interface\.meteor\local\build\programs\server\undefined\public'
W20170611-19:33:06.909(-4)? (STDERR)     at Error (native)
W20170611-19:33:06.909(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:794:18)
W20170611-19:33:06.910(-4)? (STDERR)     at packages/tap_i18n-bundler/i18n-bundler.coffee:18:12
W20170611-19:33:06.910(-4)? (STDERR)     at Function.time (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:301:28)
W20170611-19:33:06.911(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:304:13
W20170611-19:33:06.911(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:345:5
W20170611-19:33:06.912(-4)? (STDERR)     at Function.run (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:480:12)
W20170611-19:33:06.912(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:343:11
=> Exited with code: 1
W20170611-19:33:10.478(-4)? (STDERR) C:\Users\charl\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170611-19:33:10.479(-4)? (STDERR)                                            throw(ex);
W20170611-19:33:10.479(-4)? (STDERR)                                            ^
W20170611-19:33:10.480(-4)? (STDERR)
W20170611-19:33:10.481(-4)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'C:\Code\mist3\interface\.meteor\local\build\programs\server\undefined\public'
W20170611-19:33:10.481(-4)? (STDERR)     at Error (native)
W20170611-19:33:10.482(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:794:18)
W20170611-19:33:10.482(-4)? (STDERR)     at packages/tap_i18n-bundler/i18n-bundler.coffee:18:12
W20170611-19:33:10.483(-4)? (STDERR)     at Function.time (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:301:28)
W20170611-19:33:10.484(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:304:13
W20170611-19:33:10.484(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:345:5
W20170611-19:33:10.485(-4)? (STDERR)     at Function.run (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:480:12)
W20170611-19:33:10.485(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:343:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

I tried to start electron after that but it will only display the same error. Here is the command I used to install the needed packages:
```
C:\Code\mist3>yarn
yarn install v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
warning 7zip-bin-linux@1.0.3: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.0.3" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ cd interface && yarn
yarn install v0.24.6
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 2.52s.
Done in 5.68s.
```

and here are the versions I m using:
```
C:\Code\mist3\interface>node --version
v6.10.3

C:\Code\mist3\interface>yarn --version
0.24.6
```
 
I wonder if anybody manage to have the project compiling on windows and if they have some tips to share or idea on what is going wrong.

Thx

**Comment by charly37** [comment]
After some search it seems to be the same issue that:
https://github.com/ethereum/meteor-dapp-wallet/issues/147

Maybe should be open again ?

As a reminder here was the error:

```
C:\Code\mist3\interface>meteor --no-release-check
[[[[[ C:\Code\mist3\interface ]]]]]

=> Started proxy.
=> Started MongoDB.
W20170613-17:22:52.145(-4)? (STDERR) C:\Users\charl\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170613-17:22:52.355(-4)? (STDERR)                                            throw(ex);
W20170613-17:22:52.356(-4)? (STDERR)                                            ^
W20170613-17:22:52.357(-4)? (STDERR)
W20170613-17:22:52.357(-4)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'C:\Code\mist3\interface\.meteor\local\build\programs\server\undefined\public'
W20170613-17:22:52.358(-4)? (STDERR)     at Error (native)
W20170613-17:22:52.358(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:794:18)
W20170613-17:22:52.359(-4)? (STDERR)     at packages/tap_i18n-bundler/i18n-bundler.coffee:18:12
W20170613-17:22:52.359(-4)? (STDERR)     at Function.time (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:301:28)
W20170613-17:22:52.360(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:304:13
W20170613-17:22:52.360(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:345:5
W20170613-17:22:52.360(-4)? (STDERR)     at Function.run (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:480:12)
W20170613-17:22:52.361(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:343:11
=> Exited with code: 1
W20170613-17:22:56.441(-4)? (STDERR) C:\Users\charl\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170613-17:22:56.441(-4)? (STDERR)                                            throw(ex);
W20170613-17:22:56.442(-4)? (STDERR)                                            ^
W20170613-17:22:56.442(-4)? (STDERR)
W20170613-17:22:56.443(-4)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'C:\Code\mist3\interface\.meteor\local\build\programs\server\undefined\public'
W20170613-17:22:56.443(-4)? (STDERR)     at Error (native)
W20170613-17:22:56.444(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:794:18)
W20170613-17:22:56.444(-4)? (STDERR)     at packages/tap_i18n-bundler/i18n-bundler.coffee:18:12
W20170613-17:22:56.445(-4)? (STDERR)     at Function.time (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:301:28)
W20170613-17:22:56.445(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:304:13
W20170613-17:22:56.446(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:345:5
W20170613-17:22:56.447(-4)? (STDERR)     at Function.run (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:480:12)
W20170613-17:22:56.448(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:343:11
=> Exited with code: 1
W20170613-17:23:00.110(-4)? (STDERR) C:\Users\charl\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170613-17:23:00.111(-4)? (STDERR)                                            throw(ex);
W20170613-17:23:00.111(-4)? (STDERR)                                            ^
W20170613-17:23:00.112(-4)? (STDERR)
W20170613-17:23:00.112(-4)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'C:\Code\mist3\interface\.meteor\local\build\programs\server\undefined\public'
W20170613-17:23:00.113(-4)? (STDERR)     at Error (native)
W20170613-17:23:00.113(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:794:18)
W20170613-17:23:00.114(-4)? (STDERR)     at packages/tap_i18n-bundler/i18n-bundler.coffee:18:12
W20170613-17:23:00.115(-4)? (STDERR)     at Function.time (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:301:28)
W20170613-17:23:00.115(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:304:13
W20170613-17:23:00.116(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:345:5
W20170613-17:23:00.116(-4)? (STDERR)     at Function.run (C:\Code\mist3\interface\.meteor\local\build\programs\server\profile.js:480:12)
W20170613-17:23:00.117(-4)? (STDERR)     at C:\Code\mist3\interface\.meteor\local\build\programs\server\boot.js:343:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
Terminate batch job (Y/N)? Y
```

so I tried to remove "i18n-bundler" as suggest in the ticket I reference before:

```
C:\Code\mist3\interface>meteor remove tap:i18n-bundler

Changes to your project's package version selections:

tap:i18n-bundler  removed from your project

tap:i18n-bundler: removed dependency
```

and then it start properly:

```
C:\Code\mist3\interface>meteor --no-release-check
[[[[[ C:\Code\mist3\interface ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.
```

Could you please double check and confirms the original fix is still present on MASTER ?

**Comment by jayarjo** [comment]
Same here.

**Comment by travelk** [comment]
same here.

**Comment by stvenyin** [comment]
Thank you.
