### ISSUE TITLE
Can't Connect to {"path":"/home/user/.ethereum/geth.ipc"}

### ISSUE THREAD

**Issue by NinjaTurtle007** [ethereum/mist#2604]
Fresh install on latest ubuntu here
I'm using "ethereum --fast" from the terminal 
it goes through the blocks just fine and very fast the first time, but then the second round it started giving this in the termnal constantly for at least an hour.

uppon restart it connects and works fine for a little and then does it again.

`[2017-06-23 16:23:25.556] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-06-23 16:23:25.556] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-06-23 16:23:25.869] [INFO] Sockets/4 - Connect to {"path":"/home/user/.ethereum/geth.ipc"}
[2017-06-23 16:23:25.871] [WARN] Sockets/4 - Connection failed, retrying after 1000ms...
`

**Comment by NinjaTurtle007** [comment]
anyone?

**Comment by NinjaTurtle007** [comment]
yep happens all the time, runs for a while then exits with

> [2017-06-29 18:46:29.788] [INFO] Sockets/node-ipc - Connect to {"path":"/home/user/.ethereum/geth.ipc"}
[2017-06-29 18:46:29.792] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-29 18:46:30.793] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-29 18:46:31.795] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-29 18:46:32.791] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2017-06-29 18:46:32.793] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2017-06-29 18:46:32.793] [INFO] EthereumNode - Node type: geth
[2017-06-29 18:46:32.793] [INFO] EthereumNode - Network: main
[2017-06-29 18:46:32.794] [INFO] EthereumNode - Start node: geth main
[2017-06-29 18:46:32.801] [INFO] EthereumNode - Start node using /home/user/.config/Ethereum Wallet/binaries/Geth/unpacked/geth
[2017-06-29 18:46:36.194] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2017-06-29 18:46:36.195] [INFO] EthereumNode - Started node successfully: geth main
[2017-06-29 18:46:36.197] [INFO] Sockets/node-ipc - Connect to {"path":"/home/user/.ethereum/geth.ipc"}
[2017-06-29 18:46:36.199] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-06-29 18:46:37.202] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...

**Comment by thetraumer** [comment]
I have the same issue on the latest Debian. Any solutions?
