### ISSUE TITLE
ether issues 

### ISSUE THREAD

**Issue by migtc** [ethereum/mist#2618]
receiving this issue on my non-syncing ether wallet. I am technically unskilled

 shouldn't allow RegExp (possible XSS) ‣
AssertionError: expected [Function] to throw error including 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with \'0x\' prefix.' but got 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with 0x prefix.'
    at Context.<anonymous> (file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:122:117)
    at Test.Runnable.run (file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///Applications/Mist.app/Contents/Resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

**Comment by sathishvj** [comment]
Even I'm not sure about the specific reasons.  But first make sure you have backed up your keystore files (Accounts -> Backup -> Accounts).  

What happened when you shut it down and restarted it?  Maybe you can also try uninstalling and reinstalling the app and report if you see any issues.

**Comment by barrard** [comment]
I have a contract that compiles, but i get this error when i try to deploy with EthereumWallet

    Payload, or some of its content properties are invalid. Please check if they are valid HEX with '0x' prefix.
