### ISSUE TITLE
eth wallet sync crash 

### ISSUE THREAD

**Issue by sergey039** [ethereum/mist#2621]
Version: `0.5.1`
OS & Version: macOS Sierra
Node type: `geth`
Number of blocks synchronized: 0
``````
Node type: geth
Network: main
Platform: darwin

...x2b2

goroutine 61 [select]:
net/http.(*persistConn).readLoop(0xc831362840)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:685 +0xc78

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc8313861c0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x271
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x26b

goroutine 62 [select]:
net/http.(*persistConn).writeLoop(0xc831362840)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:686 +0xc9d

**Comment by alexvandesande** [comment]
Thanks for reporting the full log, we are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.

There's nothing in the log that makes me believe it was out of ordinary. I suppose restarting it solved the issue?

I am closing this issue due to inactivity. **Please feel free** to reopen should you still have some considerations about it.
