### ISSUE TITLE
Ethereum Wallet is looking for the wrong geth version number

### ISSUE THREAD

**Issue by bortzmeyer** [ethereum/mist#2681]
```
[2017-07-01 14:59:08.939] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2017-07-01 14:59:08.940] [INFO] ClientBinaryManager - Verify Geth status ...
[2017-07-01 14:59:08.957] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2017-07-01 14:59:08.957] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2017-07-01 14:59:09.008] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.6.0" in Geth output
    at Promise.resolve.then.then.then (/opt/Ethereum Wallet/resources/app.asar/node_modules/ethereum-client-binaries/src/index.js:635:17)
[2017-07-01 14:59:09.015] [INFO] ClientBinaryManager - Download binary for Geth ...
```

But I have a geth:
```
% geth version
Geth
Version: 1.6.6-stable
Git Commit: 10a45cb59bd9bc9f717817afc029a57b222e558d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=/home/stephane/Programmation/Go:/usr/share/gocode
GOROOT=/usr/lib/go-1.8
```

Bother geth and Ethereum Wallet (version 0.8.10-1708) come from the Ubuntu repository  in http://ppa.launchpad.net/ethereum/ethereum/ubuntu). It seems Ethereum Wallet requires exactly version 1.6.0 (instead of a more lax "version >= 1.6), which is not the one in the apt repository.

**Comment by AnthonyAkentiev** [comment]
+1

**Comment by kobkrit** [comment]
+1

**Comment by jeffward01** [comment]
I am also having this issue.  Please see image:

http://i.imgur.com/XrvpzcW.png

**Comment by evertonfraga** [comment]
the version matches correctly. 1.6.6.

can you provide the node.log file?

**Comment by emariacher** [comment]
←[32m[2017-11-28 20:28:37.515] [INFO] ClientBinaryManager - ←[39mChecking sanity for Geth ...
←[31m[2017-11-28 20:28:38.504] [ERROR] ClientBinaryManager - ←[39mSanity check failed for Geth { Error: spawn C:\Program Files\Geth\geth.exe
C:\Users\ericm_000\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe ENOENT
    at notFoundError (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\Geth\\geth.exe\r\nC:\\Users\\ericm_000\\AppData\\Roaming\\Ethereum Wallet\\binaries\\Geth\\unpacked\\geth.exe' }

**Comment by SeedZheng** [comment]
+1
[2018-04-03T17:29:59.470] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-04-03T17:29:59.679] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-04-03T17:29:59.679] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-04-03T17:29:59.802] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.8.2" in Geth output
    at Promise.resolve.then.then.then (D:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:632:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-04-03T17:29:59.808] [INFO] ClientBinaryManager - Download binary for Geth ...

**Comment by yvan1401** [comment]
Same problem here. Running Win/AMD64 with Geth 1.8.7 (tried full and light mode) with identical result. Might try reinstalling Mist but i'm not sure it will solve the issue.

[](url)
![capture](https://user-images.githubusercontent.com/35704423/40239277-ec1aa126-5ab5-11e8-8883-ae6ff135c5ec.PNG)

**Comment by stvenyin** [comment]
dear toall.
I'm hava solve this questions .
[2019-04-16 17:07:37.610] [INFO] main - Running in production mode: true
[2019-04-16 17:07:37.647] [INFO] EthereumNode - undefined null 'fast'
[2019-04-16 17:07:37.648] [INFO] EthereumNode - Defaults loaded: geth main fast
[2019-04-16 17:07:38.231] [INFO] main - Starting in Mist mode
[2019-04-16 17:07:38.263] [INFO] Db - Loading db: C:\Users\Lenovo\AppData\Roaming\Mist\mist.lokidb
[2019-04-16 17:07:38.276] [INFO] Windows - Creating commonly-used windows
[2019-04-16 17:07:38.277] [INFO] Windows - Create secondary window: loading, owner: notset
[2019-04-16 17:07:38.348] [INFO] updateChecker - Check for update...
[2019-04-16 17:07:41.704] [INFO] Windows - Create primary window: main, owner: notset
[2019-04-16 17:07:41.750] [INFO] Windows - Create primary window: splash, owner: notset
[2019-04-16 17:07:42.654] [INFO] ipcCommunicator - Backend language set to:  en
[2019-04-16 17:07:43.141] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2019-04-16 17:07:43.201] [INFO] (ui: splashscreen) - Meteor starting up...
[2019-04-16 17:07:43.241] [INFO] ClientBinaryManager - Initializing...
[2019-04-16 17:07:43.242] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2019-04-16 17:07:43.953] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2019-04-16 17:07:43.960] [INFO] ClientBinaryManager - Initializing...
[2019-04-16 17:07:43.966] [INFO] ClientBinaryManager - Resolving platform...
[2019-04-16 17:07:43.970] [INFO] ClientBinaryManager - Calculating possible clients...
[2019-04-16 17:07:43.973] [INFO] ClientBinaryManager - 1 possible clients.
[2019-04-16 17:07:43.974] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2019-04-16 17:07:43.975] [INFO] ClientBinaryManager - Verify Geth status ...
[2019-04-16 17:07:44.125] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2019-04-16 17:07:44.126] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2019-04-16 17:07:44.128] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2019-04-16 17:07:44.133] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2019-04-16 17:07:44.228] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-04-16 17:07:44.230] [INFO] Sockets/node-ipc - Connected!
[2019-04-16 17:07:44.231] [INFO] NodeSync - Ethereum node connected, re-start sync
[2019-04-16 17:07:44.235] [INFO] NodeSync - Starting sync loop
[2019-04-16 17:07:44.236] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-04-16 17:07:44.245] [INFO] Sockets/3 - Connected!
[2019-04-16 17:07:44.260] [INFO] (ui: splashscreen) - Network is privatenet
[2019-04-16 17:07:44.260] [INFO] (ui: splashscreen) - Network is privatenet
[2019-04-16 17:07:45.967] [INFO] updateChecker - App (0.9.3) is out of date. New v0.11.1 found.
[2019-04-16 17:07:45.977] [INFO] Windows - Create popup window: updateAvailable
[2019-04-16 17:07:45.980] [INFO] Windows - Create secondary window: updateAvailable, owner: notset
[2019-04-16 17:07:46.877] [INFO] (ui: popupWindow) - Web3 not yet initialized, doing so now with HttpProvider.
[2019-04-16 17:07:46.982] [INFO] (ui: popupWindow) - Meteor starting up...
[2019-04-16 17:07:47.799] [INFO] main - Connected via IPC to node.
[2019-04-16 17:08:00.865] [INFO] NodeSync - Sync has been skipped
[2019-04-16 17:08:00.868] [INFO] main - Loading Interface at file://E:\go\metor-wallet\ethereum\mist-\dist_mist\dist\win-unpacked\resources\app.asar/interface/index.html
[2019-04-16 17:08:00.882] [INFO] NodeSync - Sync loop ended
[2019-04-16 17:08:01.400] [INFO] Sockets/2 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-04-16 17:08:01.403] [INFO] Sockets/2 - Connected!
[2019-04-16 17:08:01.871] [INFO] (ui: mist) - Web3 already initialized, re-using provider.
[2019-04-16 17:08:01.975] [INFO] (ui: mist) - Meteor starting up...
[2019-04-16 17:08:01.984] [INFO] (ui: mist) - Initialise Mist Interface
[2019-04-16 17:08:02.135] [INFO] (ui: mist) - Network is privatenet
[2019-04-16 17:08:02.273] [INFO] (ui: mist) - did-navigate wallet https://wallet.ethereum.org/
[2019-04-16 17:08:02.284] [INFO] Sockets/2 - Disconnecting...
[2019-04-16 17:08:02.288] [INFO] (ui: mist) - did-navigate browser https://ethereum.org/
[2019-04-16 17:08:02.424] [INFO] Sockets/2 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-04-16 17:08:02.424] [INFO] Sockets/2 - Connected!
[2019-04-16 17:08:02.630] [INFO] Sockets/6 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-04-16 17:08:02.633] [INFO] Sockets/6 - Connected!
[2019-04-16 17:08:02.644] [INFO] Sockets/5 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-04-16 17:08:02.645] [INFO] Sockets/5 - Connected!
[2019-04-16 17:08:03.044] [INFO] (ui: mist) - dom-ready browser https://ethereum.org/
[2019-04-16 17:08:03.571] [INFO] (ui: mist) - did-navigate-in-page wallet https://wallet.ethereum.org/
[2019-04-16 17:08:03.620] [INFO] (ui: mist) - dom-ready wallet https://wallet.ethereum.org/
[2019-04-16 17:08:03.990] [INFO] (ui: mist) - did-stop-loading wallet https://wallet.ethereum.org/
[2019-04-16 17:08:04.172] [INFO] (ui: mist) - did-stop-loading browser https://ethereum.org/
[2019-04-16 17:08:05.157] [INFO] (ui: mist) - did-stop-loading browser https://ethereum.org/
[2019-04-16 17:08:05.172] [INFO] (ui: mist) - did-stop-loading browser https://ethereum.org/
[2019-04-16 17:08:05.401] [INFO] (ui: mist) - did-get-redirect-request browser https://ethereum.org/
[2019-04-16 17:08:06.031] [INFO] (ui: mist) - did-stop-loading browser https://ethereum.org/
not appear this question
somtthime is 0 bug
