### ISSUE TITLE
Multiple crashes and freezes prevent chain download completion

### ISSUE THREAD

**Issue by YouriAckx** [ethereum/mist#2755]
``````
Version: `0.8.10`
OS & Version: Ubuntu 16.04LTS 4.4.0-83-generic
Node type: `geth`
Number of blocks synchronized: 3,912,371
RAM: 4Gb
``````

I've encountered repeated crashes and sync freezes, both on my MacBook Pro and on an older GNU/Linux desktop with this `0.8.10` version. The issues are much less frequent on the MBP than on my more constrained workstation, so I'll be reporting for the latter. As a result, I haven't been able to sync after half a dozen attempts, starting from an empty `chaindata`. It was challenging on the MBP but it managed to get through. People around me are experiencing similar difficulties.

Wallet was launched command line to get immediate logging. Let me know if I can provide more info.

### 1. Freezes

The splashscreen is displayed, Downloading blocks is fast then stops. I kill the application after 10 minutes and it moves forward on restart, then maybe it freezes, maybe it crashes.

### 2. `Error: write EPIPE`

See [error04.txt](https://github.com/ethereum/mist/files/1143018/error04.txt)

```
Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
```
### 3. Unable to connect to socket: timeout

```
[2017-07-12 19:11:31.912] [ERROR]
ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

### 4. `ECONNRESET`

See [error01.txt](https://github.com/ethereum/mist/files/1143029/error01.txt)

```
[2017-07-12 19:13:01.543] [INFO] (ui: splashscreen) - Network is mainnet
[2017-07-12 19:47:00.953] [ERROR] Sockets/3 - { Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at Pipe.onread (net.js:564:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[2017-07-12 19:47:01.351] [INFO] Sockets/3 - Disconnecting...
[2017-07-12 19:47:01.368] [ERROR] Sockets/node-ipc - { Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at Pipe.onread (net.js:564:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[2017-07-12 19:47:01.385] [ERROR] main - UNCAUGHT EXCEPTION { Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
```

### node.log

[node.log.zip](https://github.com/ethereum/mist/files/1143052/node.log.zip)

**Comment by YouriAckx** [comment]
Workaround: start `geth` on its own before the wallet with increased cache (default is `128`)

```
$ geth --cache 512
$ ethereumwallet
```

This seems to work much better, although I'm not sure it's ever going to complete.

On modern machine, you may have success with [these settings](https://ethereum.stackexchange.com/a/4210/6790):

```
get --cache 1024 --jitvm
```

**Comment by YouriAckx** [comment]
Moving `chaindata` from a HDD (even 7200rpm) to a SSD makes a difference. It is still painfully slow on this older setup but it keeps moving forward.

**Comment by Echsecutor** [comment]
I am running 
$ ethereumwallet --version
[2017-10-28 13:13:14.185] [INFO] main - 0.9.2

and I am experiencing similar problems. I keep restarting the app but could not complete the chain download, yet.
Sometimes the app crashes my X server, sometimes it just stops syncing. One of the cleaner crashes (the wallet quit) was the following, which at least provided a clear error message:


[2017-10-28 11:48:51.511] [ERROR] Sockets/node-ipc - { Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
[2017-10-28 11:48:51.833] [ERROR] main - UNCAUGHT EXCEPTION { Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
[2017-10-28 11:48:51.853] [INFO] main - Defer quitting until sockets and node are shut down
[2017-10-28 11:48:51.859] [INFO] Sockets - Destroy all sockets
[2017-10-28 11:48:51.876] [INFO] Sockets/3 - Disconnecting...
[2017-10-28 11:48:51.896] [INFO] Sockets/node-ipc - Disconnecting...
/opt/Ethereum Wallet/resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function re

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)

**Comment by nbeerbower** [comment]
Hi all,

Running Ubuntu 16.04 and am getting the same error in Ethereum Wallet:

`[2018-01-23 22:04:19.018] [ERROR] Sockets/node-ipc - { Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
[2018-01-23 22:04:19.877] [ERROR] main - UNCAUGHT EXCEPTION { Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
`

I've tried running geth with a higher cache as suggested but it hasn't made any improvement for me.

I'll update with any findings.
