### ISSUE TITLE
Mist 0.9.0 not connecting to geth with rinkeby

### ISSUE THREAD

**Issue by 3esmit** [ethereum/mist#2840]
![image](https://user-images.githubusercontent.com/224810/28640550-6c3f74b2-7222-11e7-92ca-c2066d6dd45f.png)

```
$ mist
[2017-07-26 16:47:53.230] [INFO] main - Running in production mode: true
[2017-07-26 16:47:53.301] [INFO] main - Starting in Mist mode
[2017-07-26 16:47:53.435] [INFO] Db - Loading db: /home/ricardo/.config/Mist/mist.lokidb
[2017-07-26 16:47:53.448] [INFO] Windows - Creating commonly-used windows
[2017-07-26 16:47:53.449] [INFO] Windows - Create secondary window: loading, owner: notset
[2017-07-26 16:47:53.509] [INFO] updateChecker - Check for update...
[2017-07-26 16:47:54.842] [INFO] Windows - Create primary window: main, owner: notset
[2017-07-26 16:47:54.851] [INFO] Windows - Create primary window: splash, owner: notset
[2017-07-26 16:47:55.221] [INFO] ipcCommunicator - Backend language set to:  pt
[2017-07-26 16:47:55.764] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2017-07-26 16:47:55.820] [INFO] (ui: splashscreen) - Meteor starting up...
[2017-07-26 16:47:55.879] [INFO] ClientBinaryManager - Initializing...
[2017-07-26 16:47:55.880] [INFO] ClientBinaryManager - Resolving path to Eth client binary ...
[2017-07-26 16:47:55.880] [INFO] ClientBinaryManager - Eth client binary path: /opt/Mist/nodes/eth/linux-x64/eth
[2017-07-26 16:47:55.881] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2017-07-26 16:47:56.416] [INFO] updateChecker - App is up-to-date.
[2017-07-26 16:48:08.713] [INFO] ClientBinaryManager - Initializing...
[2017-07-26 16:48:08.713] [INFO] ClientBinaryManager - Resolving platform...
[2017-07-26 16:48:08.714] [INFO] ClientBinaryManager - Calculating possible clients...
[2017-07-26 16:48:08.715] [INFO] ClientBinaryManager - 1 possible clients.
[2017-07-26 16:48:08.715] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2017-07-26 16:48:08.717] [INFO] ClientBinaryManager - Verify Geth status ...
[2017-07-26 16:48:08.728] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2017-07-26 16:48:08.728] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2017-07-26 16:48:08.767] [INFO] Sockets/node-ipc - Connect to {"path":"/home/ricardo/.ethereum/geth.ipc"}
[2017-07-26 16:48:08.769] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:09.772] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:10.774] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:11.769] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2017-07-26 16:48:11.771] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2017-07-26 16:48:11.771] [INFO] EthereumNode - Node type: geth
[2017-07-26 16:48:11.771] [INFO] EthereumNode - Network: rinkeby
[2017-07-26 16:48:11.771] [INFO] EthereumNode - Start node: geth rinkeby
[2017-07-26 16:48:11.772] [INFO] EthereumNode - Start node using /home/ricardo/.config/Mist/binaries/Geth/unpacked/geth
[2017-07-26 16:48:14.813] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2017-07-26 16:48:14.814] [INFO] EthereumNode - Started node successfully: geth rinkeby
[2017-07-26 16:48:14.815] [INFO] Sockets/node-ipc - Connect to {"path":"/home/ricardo/.ethereum/geth.ipc"}
[2017-07-26 16:48:14.816] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:15.817] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:16.818] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:17.819] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:18.820] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:19.821] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:20.823] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:21.824] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:22.826] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:23.827] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:24.828] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:25.830] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:26.832] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:27.834] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:28.835] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:29.837] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:30.838] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:31.840] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:32.841] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:33.842] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:34.843] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:35.845] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:36.847] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:37.849] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:38.850] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:39.851] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:40.853] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:41.854] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:42.856] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:43.857] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-07-26 16:48:44.817] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2017-07-26 16:48:44.817] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Mist/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-07-26 16:48:44.879] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Mist/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-07-26 16:48:44.880] [ERROR] main - Error starting up node and/or syncing Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Mist/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by Rsalazarm** [comment]
Seems we have the same issue. Let see what people says... ;)

**Comment by evertonfraga** [comment]
Oi @3esmit, tudo bem? 
tem como mandar o arquivo node.log?

`/home/ricardo/.config/Mist/node.log` e os node.log.* também

**Comment by evertonfraga** [comment]
@Rsalazarm are you also using linux?

**Comment by evertonfraga** [comment]
Please check if you guys are using geth >1.6.6

`/home/USER/.config/Mist/binaries/`

then `$ geth version`

**Comment by 3esmit** [comment]
@evertonfraga 
![image](https://user-images.githubusercontent.com/224810/29102529-2c54a91c-7c90-11e7-8995-500ae96ff4d1.png)
```
ricardo@ricardo-nb:~/.config/Mist$ cat node.log
flag provided but not defined: -rinkeby
ricardo@ricardo-nb:~/.config/Mist$ cat node.log*
flag provided but not defined: -rinkeby
flag provided but not defined: -rinkeby
flag provided but not defined: -rinkeby
flag provided but not defined: -rinkeby
flag provided but not defined: -rinkeby
flag provided but not defined: -rinkeby
```
![image](https://user-images.githubusercontent.com/224810/29102563-72496a20-7c90-11e7-9bb6-a3fb2d45dadd.png)
```
ricardo@ricardo-nb:~/.config/Mist/binaries/Geth$ geth version
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8
ricardo@ricardo-nb:~/.config/Mist/binaries/Geth$ ./unpacked/geth version
Geth
Version: 1.6.0-stable
Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

**Comment by evertonfraga** [comment]
@3esmit gotcha. It seems you have an old geth version (1.6.0) inside your mist installation. 

Without having any geth instances running, if you start Mist, it'll prompt you to update your Geth node (if you haven't declined to update it on beforehand).

If that doesn't help, please remove the `~/.config/Mist/binaries` directory and restart Mist — it'll automatically download the latest geth defined in `clientBinaries.json`.

Thanks for reporting, and sorry for the delay. It's hard to catch up with due to the increasing demand.

**Comment by 3esmit** [comment]
Fixed in latest release
