### ISSUE TITLE
"Couldn't start swarm process" on remote RPC geth conection

### ISSUE THREAD

**Issue by PatchRanger** [ethereum/mist#2959]
Version: `0.9.0`
OS & Version: `Ubuntu 16.04`
Geth version: `1.6.7-stable-ab5646c5`
Number of blocks synchronized: not blocking sync, blocks continue to be downloaded
Sync mode: `fast`

I've launched remote geth instance with RPC interface enabled - and attached Mist to it, according to [this instruction](https://ethereum.stackexchange.com/a/7062). I know that it has security implications, I just need to sync blockchain quickly (using rented server) - and then deploy a contract via handsome Mist interface.

Looks like it is working: I see a small Mist window, where the current progress is showed.

Looking into the terminal log (I've launched Mist in a terminal mode - so all of its output is displayed there), I see these lines:
```
[2017-08-17 17:54:01.307] [INFO] Sockets/3 - Connected!
[2017-08-17 17:54:01.715] [INFO] (ui: splashscreen) - Network is mainnet
[2017-08-17 17:54:01.716] [INFO] (ui: splashscreen) - Network is mainnet
[2017-08-17 17:54:21.634] [ERROR] main - Error starting up node and/or syncing Error: Couldn't start swarm process.
    at Timeout.error [as _onTimeout] (/opt/Mist/resources/app.asar/node_modules/swarm-js/lib/swarm.js:420:21)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

I didn't have any Swarm issues, when I was using local geth instance, - at least I hadn't notice them.

I've failed to find any related logs - sorry.

**Comment by evertonfraga** [comment]
Thanks, @PatchRanger, it's a known issue. I'll make sure to poke the right people towards a fix.

**Comment by PatchRanger** [comment]
Additional info: after successful full blockchain sync, Mist is refusing to start - it just shows small window with "Starting Swarm". So this bug is blocking for usage via RPC.

**Comment by smabbutt** [comment]
Same issue with Mist 0.9.0 on Windows 10, using HTTP RPC connection to geth 1.6.7-stable.  
```
[2017-08-20 14:13:13.938] [INFO] Sockets/node-ipc - Connect to {"hostPort":"http://127.0.0.1:8545"}
[2017-08-20 14:13:13.945] [INFO] Sockets/node-ipc - Connected!
[2017-08-20 14:13:13.946] [INFO] NodeSync - Ethereum node connected, re-start sync
[2017-08-20 14:13:13.946] [INFO] NodeSync - Starting sync loop
[2017-08-20 14:13:13.947] [INFO] Sockets/3 - Connect to {"hostPort":"http://127.0.0.1:8545"}
[2017-08-20 14:13:13.966] [INFO] Sockets/3 - Connected!
[2017-08-20 14:13:13.979] [INFO] (ui: splashscreen) - Network is mainnet
[2017-08-20 14:13:13.979] [INFO] (ui: splashscreen) - Network is mainnet
[2017-08-20 14:13:14.326] [INFO] updateChecker - App is up-to-date.
[2017-08-20 14:13:51.613] [ERROR] main - Error starting up node and/or syncing Error: Couldn't start swarm process.
    at Timeout.error [as _onTimeout] (C:\Program Files\Mist\resources\app.asar\node_modules\swarm-js\lib\swarm.js:420:21)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-08-20 14:14:00.816] [INFO] NodeSync - Sync has been skipped
[2017-08-20 14:14:00.817] [INFO] NodeSync - Sync loop ended
```

**Comment by gazambuja** [comment]
Same thing in MAC connecting to a remote and private blockchain (in Azure in this case)

```
[2017-08-22 16:06:42.795] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.6.6" in Geth output
    at Promise.resolve.then.then.then (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/ethereum-client-binaries/src/index.js:635:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2017-08-22 16:06:42.804] [INFO] Sockets/node-ipc - Connect to {"hostPort":"http://........cloudapp.azure.com:8545"}
[2017-08-22 16:06:43.391] [INFO] Sockets/node-ipc - Connected!
[2017-08-22 16:06:43.393] [INFO] NodeSync - Ethereum node connected, re-start sync
[2017-08-22 16:06:43.394] [INFO] NodeSync - Starting sync loop
[2017-08-22 16:06:43.396] [INFO] Sockets/3 - Connect to {"hostPort":"http://........cloudapp.azure.com:8545"}
[2017-08-22 16:06:43.815] [INFO] Sockets/3 - Connected!
[2017-08-22 16:06:44.185] [INFO] (ui: splashscreen) - Network is privatenet
[2017-08-22 16:06:44.185] [INFO] (ui: splashscreen) - Network is privatenet
[2017-08-22 16:06:44.731] [INFO] updateChecker - App is up-to-date.
[2017-08-22 16:06:46.152] [INFO] NodeSync - No more sync necessary
[2017-08-22 16:06:46.152] [INFO] NodeSync - Sync loop ended
[2017-08-22 16:07:03.731] [ERROR] main - Error starting up node and/or syncing Error: Couldn't start swarm process.
    at Timeout.error [as _onTimeout] (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/swarm-js/lib/swarm.js:420:21)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by EdgarBarrantes** [comment]
Same error in Mac, connecting to testRPC.
```[2017-08-25 21:38:46.273] [INFO] NodeSync - Sync loop ended
[2017-08-25 21:39:04.717] [ERROR] main - Error starting up node and/or syncing Error: Couldn't start swarm process.
    at Timeout.error [as _onTimeout] (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/swarm-js/lib/swarm.js:420:21)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)```

**Comment by Vorob-Astronaut** [comment]
```
 electron . --rpc http://localhost:8545
[2017-08-28 17:12:46.107] [INFO] main - Running in production mode: false
[2017-08-28 17:12:46.112] [WARN] main - CONNECTING TO A NODE VIA HTTP INSTEAD OF IPCMAIN. THIS IS LESS SECURE!!!!
[2017-08-28 17:12:46.956] [INFO] main - Starting in Mist mode
[2017-08-28 17:14:52.472] [INFO] Db - Loading db: /Users/vorob/Library/Application Support/Mist/mist.lokidb
[2017-08-28 17:14:52.518] [INFO] Windows - Creating commonly-used windows
[2017-08-28 17:14:52.520] [INFO] Windows - Create secondary window: loading, owner: notset
[2017-08-28 17:14:52.728] [INFO] updateChecker - Check for update...
[2017-08-28 17:14:58.365] [INFO] Windows - Create primary window: main, owner: notset
[2017-08-28 17:14:58.389] [INFO] Windows - Create primary window: splash, owner: notset
[2017-08-28 17:14:59.825] [INFO] ipcCommunicator - Backend language set to:  en
[2017-08-28 17:15:01.939] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2017-08-28 17:15:02.159] [INFO] (ui: splashscreen) - Meteor starting up...
[2017-08-28 17:15:02.468] [INFO] ClientBinaryManager - Initializing...
[2017-08-28 17:15:02.469] [INFO] ClientBinaryManager - Resolving path to Eth client binary ...
[2017-08-28 17:15:02.469] [INFO] ClientBinaryManager - Eth client binary path: /Users/vorob/Dropbox/eth/mist/nodes/eth/mac-x64/eth
[2017-08-28 17:15:02.470] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2017-08-28 17:15:03.982] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2017-08-28 17:15:03.985] [INFO] ClientBinaryManager - Initializing...
[2017-08-28 17:15:03.985] [INFO] ClientBinaryManager - Resolving platform...
[2017-08-28 17:15:03.986] [INFO] ClientBinaryManager - Calculating possible clients...
[2017-08-28 17:15:03.988] [INFO] ClientBinaryManager - 1 possible clients.
[2017-08-28 17:15:03.989] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2017-08-28 17:15:03.991] [INFO] ClientBinaryManager - Verify Geth status ...
[2017-08-28 17:15:04.045] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2017-08-28 17:15:04.046] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2017-08-28 17:15:04.047] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2017-08-28 17:15:04.051] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2017-08-28 17:15:04.312] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.6.6" in Geth output
    at Promise.resolve.then.then.then (/Users/vorob/Dropbox/eth/mist/node_modules/ethereum-client-binaries/src/index.js:635:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2017-08-28 17:15:04.367] [INFO] Sockets/node-ipc - Connect to {"hostPort":"http://localhost:8545"}
[2017-08-28 17:15:04.404] [INFO] Sockets/node-ipc - Connected!
[2017-08-28 17:15:04.406] [INFO] NodeSync - Ethereum node connected, re-start sync
[2017-08-28 17:15:04.407] [INFO] NodeSync - Starting sync loop
[2017-08-28 17:15:04.408] [INFO] Sockets/3 - Connect to {"hostPort":"http://localhost:8545"}
[2017-08-28 17:15:04.489] [INFO] Sockets/3 - Connected!
[2017-08-28 17:15:04.586] [INFO] updateChecker - App is up-to-date.
[2017-08-28 17:15:04.587] [INFO] (ui: splashscreen) - Network is privatenet
[2017-08-28 17:15:04.587] [INFO] (ui: splashscreen) - Network is privatenet
[2017-08-28 17:15:14.361] [INFO] NodeSync - Sync has been skipped
[2017-08-28 17:15:14.361] [INFO] NodeSync - Sync loop ended
[2017-08-28 17:15:24.780] [ERROR] main - Error starting up node and/or syncing Error: Couldn't start swarm process.
    at Timeout.error [as _onTimeout] (/Users/vorob/Dropbox/eth/mist/node_modules/swarm-js/lib/swarm.js:451:23)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by Vorob-Astronaut** [comment]
running with sudo fix this issue

**Comment by santiagorp** [comment]
Same issue with geth running on docker container. Is there any ETA for the bugfix?

**Comment by acalatrava** [comment]
I found a workaround for this, you need to start swarm on the remote server too. In my case it's a ubuntu machine and I installed it

`apt-get install swarm`

and execute it like

`swarm --bzzaccount /root/.ethereum/swarmKey`

and it started to listen on http://localhost:8500 so I mapped the port to my remote machine and Mist started to work.

I know that this is not ideal but at least it allow you to use it while the bug is fixed

**Comment by fafrd** [comment]
Another workaround that you could try is setting a different swarm daemon. run Mist with the flag `--swarmurl="http://swarm-gateways.net"`

**Comment by PatchRanger** [comment]
@fafrd Thank you, the workaroud works! I guess, the @acalatrava's suggestion should work too - though I didn't try it.

**Comment by mwiktorczyk** [comment]
Same issue here:

`ethereumwallet --mode wallet --rpc ${ETH_SERVER_HOST} --network test`

```
[2017-11-29 17:41:35.066] [ERROR] Sockets/4 - Connection failed (5000ms elapsed)
[2017-11-29 17:41:35.071] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:93:39)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by nanothermite** [comment]
Another possible use case is when you attempt to connect Mist to swarm running on another node in your private network you would then point swarmurl to your node name/IP address as shown here in the ethereum/swarm gitter channel:

https://gitter.im/ethereum/swarm?at=59f882a7f7299e8f5354dce9

**Comment by evertonfraga** [comment]
Fixed in @3431. From 0.9.4 (following version) swarm will execute on an opt-in basis.

Thanks for the patience.
