### ISSUE TITLE
downloading blocks

### ISSUE THREAD

**Issue by slacker247** [ethereum/mist#2983]
- [X] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

I've written code to "fix" work around the issues that your wallet has.  It is located here:
https://github.com/slacker247/EthWalletRunner

I've been running your wallet since before 2017-07-26T15:30:19+02:00 and on that date I transfered
https://etherchain.org/account/0x524eaba73eefce97016a8ce79b702eaab51c5d80
Which still hasn't been received.

If you want help, I can code for a fee.
jeff

```
Version: `0.9.0`
OS & Version: windows
Node version: `geth 1.6.6` 
Number of blocks synchronized: 1324 (left)
```
**I've been waiting to long for this to be fixed or my money to transfer.  If this is a duplicate, you really need to fix it.**

Error:
[32m[2017-08-24 16:42:12.256] [INFO] EthereumNode - [39mStarted node successfully: geth main
[32m[2017-08-24 16:42:12.282] [INFO] Sockets/node-ipc - [39mConnect to {"path":"\\\\.\\pipe\\geth.ipc"}
[33m[2017-08-24 16:42:12.301] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:13.303] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:14.303] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:15.308] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:16.311] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:17.311] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:18.314] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:19.320] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:20.322] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:21.326] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:22.328] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:23.344] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:24.344] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:25.345] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:26.347] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:27.349] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:28.368] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:29.371] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:30.384] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:31.390] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:32.413] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:33.418] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:34.420] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:35.423] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:36.424] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:37.431] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:38.432] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:39.434] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:40.437] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[33m[2017-08-24 16:42:41.439] [WARN] Sockets/node-ipc - [39mConnection failed, retrying after 1000ms...
[31m[2017-08-24 16:42:42.291] [ERROR] Sockets/node-ipc - [39mConnection failed (30000ms elapsed)
[31m[2017-08-24 16:42:42.295] [ERROR] EthereumNode - [39mFailed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (C:\Users\jeff\Desktop\Ethereum\resources\app.asar\modules\sockets\base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[31m[2017-08-24 16:42:42.518] [ERROR] EthereumNode - [39mFailed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (C:\Users\jeff\Desktop\Ethereum\resources\app.asar\modules\sockets\base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[31m[2017-08-24 16:42:42.520] [ERROR] main - [39mError starting up node and/or syncing Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (C:\Users\jeff\Desktop\Ethereum\resources\app.asar\modules\sockets\base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

![image](https://user-images.githubusercontent.com/3171902/29692302-80b16366-88ec-11e7-8f8c-28df594d1cea.png)

**Comment by slacker247** [comment]
![image](https://user-images.githubusercontent.com/3171902/29692398-00828a02-88ed-11e7-8b27-5965ac1f227b.png)

**Comment by slacker247** [comment]
![image](https://user-images.githubusercontent.com/3171902/29692417-1ca219fa-88ed-11e7-849c-f9ae8f6e82da.png)

**Comment by Rictrader** [comment]
can you help me sync my wallet? I have some Ether there and can't get it.

**Comment by slacker247** [comment]
this makes no sense.  the block the money was transferred into my "wallet" address was at block - 4,076,442
The current block that the wallet has downloaded is - 4,249,084
![image](https://user-images.githubusercontent.com/3171902/30184245-b0690246-93da-11e7-9d45-2f0b0c871596.png)

**Comment by dfkthf125** [comment]
а я не понял еще как они работают но хотелось разобрать 


>Четверг,  7 сентября 2017, 23:42 +03:00 от Jeff McCartney <notifications@github.com>:
>
>это не имеет никакого смысла.  блок деньги были переданы в мой «бумажник» адрес был в блоке - 4076442 
>Текущий блок ,  что бумажник Скачиваемый - 4249084
>- 
>Вы получаете это ,  потому что вы подписаны на эту тему. 
>Ответить на это сообщение непосредственно,  просматривать его на GitHub , или  приглушить нить .


Впрок

**Comment by Rictrader** [comment]
Stop trying to syc the wallet, it doesn't work.
Download MetaMask extension to Chrome, run It, restore your wallet (you will need your private Key, and password), then you will have acess to your ETH. If you need help, feel free to ask.

**Comment by slacker247** [comment]
I know there are web based wallets.  This being the creators of ethereum, the wallet should work.  That's kind of a fundamental.  But, just encase they never fix it, how does one go about extracting the private key?  I've found the key file location but it just looks like the encryption mechanism not the actual private key.  Somebody had said that they encrypt it so that someone can't just look at the file for the private key...

**Comment by Rictrader** [comment]
https://youtu.be/7YXyDw9Zeec


Watching this vídeo you will learn How to get to the private Key file. It's
close to the file he deletes to try to make the wallet work(It will not).
Just copy the file and past It to a pendrive or wherever you want.

Then use the file and your password to restore the wallet in MetaMask.
It was ease and worked well for me.

I hope It works for you.
If you need help, feel free to ask.


Em 8 de set de 2017 12:18 PM, "Jeff McCartney" <notifications@github.com>
escreveu:

I know there are web based wallets. This being the creators of ethereum,
the wallet should work. That's kind of a fundamental. But, just encase they
never fix it, how does one go about extracting the private key? I've found
the key file location but it just looks like the encryption mechanism not
the actual private key. Somebody had said that they encrypt it so that
someone can't just look at the file for the private key...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/mist/issues/2983#issuecomment-328132537>, or mute
the thread

**Comment by wtfiwtz** [comment]
If you want to persist with Mist or Ethereum Wallet, you'll just have to wait or try re-connecting to more peers to get the blocks you are missing. See https://github.com/ethereum/go-ethereum/issues/15001

Otherwise, try the parity.io wallet with its light sync mode.

**Comment by slacker247** [comment]
Looks like it finally came through to the wallet.  So it does eventually come through.

**Comment by slacker247** [comment]
actually, this issue isn't closed, because the problems with the wallet continuing to run, still exist.
