### ISSUE TITLE
Node error, please help!

### ISSUE THREAD

**Issue by joe1234555** [ethereum/mist#2987]
Hello, so newbie here, set up my ethereum wallet started using it and all I get is an error (no matter how many times I restart/reinstall etc. The error is as follows:

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...INFO [08-25|22:02:38] Starting peer-to-peer node               instance=Geth/v1.6.1-stable-021c3c28/darwin-amd64/go1.8.1
INFO [08-25|22:02:38] Allocated cache and file handles         database=/Users/Toby/Library/Ethereum/geth/chaindata cache=1024 handles=1024

Please help!

```
Version: `0.8.00 & 0.9.0`
OS & Version: OSX
Node version: `geth 0.0.0` [i don't know what this is]
Number of blocks synchronized: all
```

**Comment by hypnosis-i2p** [comment]
Same here, on Ubuntu 16.04. I am an experienced developer so advanced questions are okay.

**Comment by hypnosis-i2p** [comment]
With --loglevel=debug:

```
[2017-09-15 18:18:01.054] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-09-15 18:18:02.013] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2017-09-15 18:18:02.014] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-09-15 18:18:02.073] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-09-15 18:18:02.073] [ERROR] main - Error starting up node and/or syncing Error: Unable to connect to socket: timeout
    at Timeout.setTimeout (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:97:43)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by hypnosis-i2p** [comment]
```
$ /home/user/.config/Ethereum\ Wallet/binaries/Geth/unpacked/geth version
Geth
Version: 1.6.6-stable
Git Commit: 10a45cb59bd9bc9f717817afc029a57b222e558d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

**Comment by hypnosis-i2p** [comment]
Same issue was reported here: #2961

**Comment by hypnosis-i2p** [comment]
hmm. i reinstalled the .deb package, ran into errors, ran geth removedb, and am syncing again.
