### ISSUE TITLE
no balance showing in mist, but account is imported.

### ISSUE THREAD

**Issue by ceefaxuk1** [ethereum/mist#3038]
Hi, I've got a problem with Mist.   It doesn't seem to show my balance when I import my account.   I've downloaded the entire block chain and everything is synced

When I "Run Tests" I get lots of red errors.   See below:-

AssertionError: The permissions object was not present, please reload the test page: expected undefined to be an array
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:9:55)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

web3.eth.accounts
should return an array [sync] ‣
TypeError: Cannot read property 'accounts' of undefined
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:16:36)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

should return an array [async] ‣
TypeError: Cannot read property 'getAccounts' of undefined
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:21:21)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4264:15)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

should match the allowed accounts in the tabs permisssions, and don't contain coinbase [sync] ‣
TypeError: Cannot read property 'accounts' of undefined
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:30:36)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4264:15)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
should match the allowed accounts in the tabs permisssions, and don't contain coinbase [async] ‣
TypeError: Cannot read property 'getAccounts' of undefined
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:42:21)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4264:15)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
should match the allowed accounts in the tabs permisssions, and don't contain coinbase [async, batch request] ‣
TypeError: web3.createBatch is not a function
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:71:30)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4264:15)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
web3.eth.coinbase
should be empty [sync] ‣
TypeError: Cannot read property 'coinbase' of undefined
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:82:36)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
should be empty [async] ‣
TypeError: Cannot read property 'getCoinbase' of undefined
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:87:21)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4264:15)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
should be empty [async, batch request] ‣
TypeError: web3.createBatch is not a function
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:110:30)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4264:15)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
web3 parameter validation
shouldn't allow RegExp (possible XSS) ‣
AssertionError: expected [Function] to throw error including 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with \'0x\' prefix.' but got 'Cannot read property \'sendTransaction\' of undefined'
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:122:117)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)
web3 attributes
shouldn't allow `admin` ‣
shouldn't allow IPC provider ‣
should only contain allowed attributes ‣
AssertionError: expected { Object (currentProvider) } to have keys '_requestManager', 'bzz', 'currentProvider', 'eth', 'db', 'shh', 'net', 'personal', 'settings', 'version', 'providers', and '_extend'
    at Context.<anonymous> (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:152:38)
    at Test.Runnable.run (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Users/homePC/Desktop/New%20folder/win-ia32-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

Can anyone help?
```
Version: `0.9.0`
OS & Version: windows10
Node version: `geth 1.6.7` 
Number of blocks synchronized: 4269469
```

**Comment by marcoballini** [comment]
same problem :(

**Comment by Kirillrgb** [comment]
same here
