### ISSUE TITLE
unable to start light node

### ISSUE THREAD

**Issue by ngarafol** [ethereum/mist#3040]
```
Version: mist-classic 0.8.1-1
OS & Version: linux (arch)
Node version: `geth 1.6.7-1` 
Number of blocks synchronized: all
```

I am trying to run light client, starting like this:

`geth --syncmode light --cache 512 & sleep 30 && mist-classic --light-node --node geth`

And get this instead:

```

INFO [09-14|10:06:28] Imported new block headers               count=160  elapsed=856.575ms number=4272415 hash=846bc4…25eafc ignored=0
[2017-09-14 10:06:28.146] [ERROR] NodeSync - Node crashed while syncing? TypeError: Cannot read property 'timestamp' of undefined
    at ethereumNode.send.then (/usr/share/mist-classic/resources/app.asar/modules/nodeSync.js:158:64)
    at tryCatcher (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
[2017-09-14 10:06:28.206] [ERROR] NodeSync - Sync error TypeError: Cannot read property 'timestamp' of undefined
    at ethereumNode.send.then (/usr/share/mist-classic/resources/app.asar/modules/nodeSync.js:158:64)
    at tryCatcher (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
[2017-09-14 10:06:28.208] [ERROR] main - Error syncing node TypeError: Cannot read property 'timestamp' of undefined
    at ethereumNode.send.then (/usr/share/mist-classic/resources/app.asar/modules/nodeSync.js:158:64)
    at tryCatcher (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
[2017-09-14 10:06:28.211] [INFO] NodeSync - Sync loop ended
[2017-09-14 10:06:28.220] [ERROR] main - Error starting up node and/or syncing TypeError: Cannot read property 'timestamp' of undefined
    at ethereumNode.send.then (/usr/share/mist-classic/resources/app.asar/modules/nodeSync.js:158:64)
    at tryCatcher (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/share/mist-classic/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
INFO [09-14|10:07:00] Imported new block headers               count=2    elapsed=7.512ms   number=4272417 hash=14971e…a5ef0a ignored=0
```

Same thing happens with mist (0.9.0).

**Comment by ajthemacboy** [comment]
I am experiencing this too. I start the geth node in light mode with rpc, then start the wallet after it is finished loading. The wallet has this error:
`Error starting up node and/or syncing TypeError: Cannot read property 'timestamp' of undefined`
The geth node continues to load block headers but the wallet is frozen.

**Comment by evertonfraga** [comment]
On my Light client checklist. thanks for pointing out

**Comment by alexvandesande** [comment]
We just updated Mist with light client support natively. Can you check to see if the problem persists? Thanks!

**Comment by samuelvanderwaal** [comment]
I'm having this issue with the new Mist version: 0.9.1 with Light Client support enabled: 

`[2017-09-28 17:22:43.922] [ERROR] NodeSync - Node crashed while syncing? TypeError: Cannot read property 'number' of undefined
    at ethereumNode.send.then.ret2 (/opt/Mist/resources/app.asar/modules/nodeSync.js:143:68)
    at tryCatcher (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-28 17:22:43.927] [ERROR] NodeSync - Sync error TypeError: Cannot read property 'number' of undefined
    at ethereumNode.send.then.ret2 (/opt/Mist/resources/app.asar/modules/nodeSync.js:143:68)
    at tryCatcher (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-28 17:22:43.927] [ERROR] main - Error syncing node TypeError: Cannot read property 'number' of undefined
    at ethereumNode.send.then.ret2 (/opt/Mist/resources/app.asar/modules/nodeSync.js:143:68)
    at tryCatcher (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-28 17:22:43.927] [INFO] NodeSync - Sync loop ended
[2017-09-28 17:22:43.928] [ERROR] main - Error starting up node and/or syncing TypeError: Cannot read property 'number' of undefined
    at ethereumNode.send.then.ret2 (/opt/Mist/resources/app.asar/modules/nodeSync.js:143:68)
    at tryCatcher (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
`

**Comment by ngarafol** [comment]
Seems to work with 0.9.0 mist and geth 1.7.0-1 Did not try new mist 0.9.1 since user above says it does not work :)

**Comment by caralbgm** [comment]
I had the same issue reported by samuelvanderwaal but I just was able to open the wallet(it was just luck).

When the Ethereum Wallet window opened, I clicked on Develop > Network > Solo network, then I came back to the main network clicking on Develop > Network > Main Network.

It fixed the problem for me. I'm using Mist 0.9.1 too.
