### ISSUE TITLE
Don't force user to download geth

### ISSUE THREAD

**Issue by HaleTom** [ethereum/mist#3078]
```
Version: `[2017-09-24 13:07:07.086] [INFO] main - 0.9.0`
OS & Version: `Linux svelte 4.9.47-1-MANJARO #1 SMP PREEMPT Sat Sep 2 07:29:38 UTC 2017 x86_64 GNU/Linux`
Node version: `instance=Geth/v1.7.0-stable-6c6c7b2a/linux-amd64/go1.9`
Number of blocks synchronized: I'm running `--light`
```

I'm running Manjaro Linux (based on Arch), so I already have very up-to-date versions of `geth` and `parity`.

I want to use my system `geth` without being forced to download another copy.

Alternately, I may not want to have `geth` on my system at all, and used a `parity` node with config file:
```
[parity]
geth = true
```
and `mist --gethpath $(which parity)` (but #3077 is currently blocking this).

**Comment by HaleTom** [comment]
Workaround:

Remove directory: `/.config/Mist/binaries`, then:

```
mkdir -m 000 /.config/Mist/binaries
```

This will make the binary directory unwritable, and prevent any download. 

Non-fatal errors are generated:

```
[2017-09-26 12:37:21.715] [ERROR] ClientBinaryManager - Unable to resolve Geth executable: geth                                                                                               
[2017-09-26 12:37:21.723] [INFO] ClientBinaryManager - Download binary for Geth ...                                                                                                           
[2017-09-26 12:37:21.736] [ERROR] ClientBinaryManager - { Error: EACCES: permission denied, mkdir '/home/ravi/.config/Mist/binaries/Geth'                                                     
    at Error (native)                                                                                                                                                                         
    at Object.fs.mkdirSync (fs.js:922:18)                                                                                                                                                     
    at Function.sync (/usr/share/mist/resources/app.asar/node_modules/mkdirp/index.js:71:13)
    at Promise.resolve.then (/usr/share/mist/resources/app.asar/node_modules/ethereum-client-binaries/src/index.js:230:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)                                              
  errno: -13,                                                                                  
  code: 'EACCES',                                                                                    
  syscall: 'mkdir',                                                                                                             
  path: '/home/ravi/.config/Mist/binaries/Geth' }
```

**Comment by HaleTom** [comment]
What is `skippedNodeVersion.json`
`

```
[2017-09-26 12:37:21.656] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
```

Is it possible to disable all versions though this file and quash the error message? I couldn't find anything on a google search.

**Comment by evertonfraga** [comment]
I must try this, but if you change `skippedNodeVersion.json` to a very high number, that could create the behavior you want, without further modifications. 

`20.0.0`, for instance.

**Comment by HaleTom** [comment]
@evertonfraga Where would `skippedNodeVersion.json` reside under the `Mist` directory, and how would `20.0.0` be represented inside it?

**Comment by evertonfraga** [comment]
`echo “20.0.0” > /home/ravi/.config/Mist/skippedNodeVersion.json`

i haven’t tried this, and please note that might change in the future,
alright?

**Comment by HaleTom** [comment]
@evertonfraga Nope :(

I get:
```
[2017-10-02 16:53:22.915] [ERROR] ClientBinaryManager - Unable to resolve Geth executable: geth
```
And `geth` is still downloaded if I first remove the `binaries` directory.

**Comment by evertonfraga** [comment]
Geth is still tightly coupled to Mist, and we're refactoring large portions of the code abstracting the node functions.
