### ISSUE TITLE
Sync of blocks impossible (v 0.9.1, on MacOSX 10.12.6)

### ISSUE THREAD

**Issue by Wulfilar** [ethereum/mist#3100]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue. (No)

The problem:
**Ethereum Wallet states last sync to be 4 months ago (wrong - it was 1,5 months ago).
Syncing is impossibly slow - no visible proceeding after 1,5 days.**
I realised that there are attempts to overcome this but these seem inapplicable in my case.

For example, in third party's reply, it was referenced to a part within Ethereum Wallet.app package content with name "Node". Such element does not exist. Its content therefore can not be altered/modified to improve situation.

```
Version: `0.9.1`
OS & Version: Mac osx 10.12.6 
(Please do not reply solutions which work on Window machines as there are no Windows machines allowed in our offices at stricter level.)
Node version: `geth 0.0.0`  => "Node" not available in Ethereum Wallet software package!! Version number can not be given.
Number of blocks synchronized: Who knows?
```
I am working with newest hard disks.
I do not intend to switch to HDD. Seriously.
Ethereum had run successfully before (last time: Beginning of August 2017).
It is impossible to leave machine "on" for more than 72 h.
Above restrictions need to be met with utmost certainty.

**Comment by Wulfilar** [comment]
Further comment:
Log Console lines as attached:

[2017-09-29 10:45:59.819] [ERROR] main - Error starting up node and/or syncing TypeError: Cannot read property 'number' of undefined
    at ethereumNode.send.then.ret2 (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/modules/nodeSync.js:143:68)
    at tryCatcher (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Ethereum Wallet 3.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Addendum:
V 0.9.1 was added today to folder "Applications" with conservation of earlier versions of Ethereum Wallet. Name of package of this running version is therefore "Ethereum Wallet 3".

**Comment by ericjarvies** [comment]
@Wulfilar - This problem did not seemingly exist prior to 0.9.1.  If you go into the following folder;
~/Library/Application Support/Ethereum Wallet/
it will contain a handful of log files, e.g.- **node.log**, **node.log.0**, **node.log.1,** and so forth.  Open **node.log** in Console or TextEdit app and take a look at the latest/most recent line items and see if you've got some **WARN** or **CRIT** entries.

See if you're got an entry like this one;
```CRIT [time/date stamp] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=435521): checksum mismatch, want=0xf5d329e4 got=0xe32b9e4e [file=552248.ldb]"```

If you want to get things working again, I believe you'll need to delete **ALL** of your Ethereum/Mist folders, along with the 0.9.1 Ethereum/Mist apps.  Download **0.9.0** Ethereum Wallet/Mist Browser, and then open the **0.9.0 Ethereum Wallet.app** and let it download the blockchain again.

If you try to use the 0.9.0 Ethereum Wallet/Mist Browser apps -against the existing data folders, I believe the problem will remain.  So I believe you must delete those 0.9.1 laden data folders, and start anew with 0.9.0.

Eric

**Comment by lorezyra** [comment]
Related: https://github.com/ethereum/mist/issues/2466

Please define OS and version.
