### ISSUE TITLE
Unable to launch newly installed Mist 0.9.1

### ISSUE THREAD

**Issue by whitemagpie** [ethereum/mist#3115]
- [] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

hey guys - i just downloaded mist 0.9.1 on macOS Sierra (10.12) - when i start Mist, it shows a screen saying "downloading node", then "ethereum node upto date - checking network" followed by "starting node" and after that it crashes.
Have tried multiple times after deleting Application Support/Mist and Application/Ethereum folders - also installed gmp using brew - as I read somewhere that may solve my problem. I realised that geth was not installed so I installed it using brew - but still facing same issue.

Its a new install on my system - dont have any previous installs.
any guidance pl?

Version: 0.9.1
OS & Version: OSX 10.12.6
Node version:  GETH  1.7.0-stable-6c6c7b2a
Number of blocks synchronized: 0

**Comment by evertonfraga** [comment]
Hi @whitemagpie. Would you please help me debug that? 

Try to open Mist/Wallet from the command line. Open terminal and type:
`/Applications/Mist.app/Contents/MacOS/Mist`

Would you paste the error here? feel free to omit any sensible data. 

Thanks!

**Comment by whitemagpie** [comment]
[2017-10-04 09:16:26.725] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2017-10-04 09:16:26.726] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2017-10-04 09:16:26.726] [INFO] EthereumNode - Node type: geth
[2017-10-04 09:16:26.726] [INFO] EthereumNode - Network: main
[2017-10-04 09:16:26.726] [INFO] EthereumNode - SyncMode: fast
[2017-10-04 09:16:26.727] [INFO] EthereumNode - Start node: geth main fast
[2017-10-04 09:16:26.728] [INFO] EthereumNode - Start node using /Users/tuhinasingh/Library/Application Support/Mist/binaries/Geth/unpacked/geth
[2017-10-04 09:16:26.809] [ERROR] main - UNCAUGHT EXCEPTION TypeError: Cannot read property 'message' of null
    at Socket.proc.stdout.on.data (/Applications/Mist.app/Contents/Resources/app.asar/modules/ethereumNode.js:428:46)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[2017-10-04 09:16:26.812] [INFO] main - Defer quitting until sockets and node are shut down
[2017-10-04 09:16:26.812] [INFO] Sockets - Destroy all sockets
[2017-10-04 09:16:26.812] [INFO] Sockets/3 - Disconnecting...
[2017-10-04 09:16:26.813] [INFO] Sockets/node-ipc - Disconnecting...
/Applications/Mist.app/Contents/Resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=

TypeError: Cannot read property 'message' of null
    at Socket.proc.stdout.on.data (/Applications/Mist.app/Contents/Resources/app.asar/modules/ethereumNode.js:428:46)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
