### ISSUE TITLE
Mist building failed on windows 10 x64

### ISSUE THREAD

**Issue by wjcloud** [ethereum/mist#3192]
[11:34:52] Starting 'bundling-interface'...
Bundling Meteor app...
Failed to execute "meteor build ..\dist_mist\app\interface --directory", exit code of #1

[11:34:57] 'bundling-interface' errored after 4.96 s
[11:34:57] Error: Command failed: cd interface             && meteor-build-client ..\dist_mist\app\interface -p ""             undefined
 C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
    hasStacks = !!e.stack;
                   ^

RangeError: Maximum call stack size exceeded

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
[11:34:57] 'buildQueue' errored after 1.75 min
[11:34:57] Error in plugin 'run-sequence(bundling-interface)'
Message:
    Command failed: cd interface             && meteor-build-client ..\dist_mist\app\interface -p ""             undefined
 C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
    hasStacks = !!e.stack;
                   ^

RangeError: Maximum call stack size exceeded

Details:
    killed: false
    code: 4294967295
    signal: null
    cmd: cd interface             && meteor-build-client ..\dist_mist\app\interface -p ""             undefined
Stack:
Error: Command failed: cd interface             && meteor-build-client ..\dist_mist\app\interface -p ""             undefined
 C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
    hasStacks = !!e.stack;
                   ^

RangeError: Maximum call stack size exceeded

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by wjcloud** [comment]
Fixed. There was a problem on Meteor windows installer. If someone is stuck for the same problem, please refer https://github.com/meteor/meteor/issues/7896#issuecomment-270163779
