### ISSUE TITLE
console error message when switching to light client sync

### ISSUE THREAD

**Issue by lhirlimann** [ethereum/mist#3211]
```
Version: `0.9.2`
OS & Version: linux Fedora 27b
Node version: `geth 0.0.0` 
Number of blocks synchronized: 132,582 block left
```

[2017-10-26 15:58:51.506] [ERROR] Sockets/node-ipc - Socket response error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 56
   Col: 0
   Chr: undefined
       at emitError (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-26 15:58:51.514] [ERROR] NodeSync - Node crashed while syncing? { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 56
   Col: 0
   Chr: undefined
       at emitError (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-26 15:58:51.514] [ERROR] NodeSync - Sync error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 56
   Col: 0
   Chr: undefined
       at emitError (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-26 15:58:51.514] [ERROR] main - Error syncing node { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 56
   Col: 0
   Chr: undefined
       at emitError (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-26 15:58:51.514] [INFO] NodeSync - Sync loop ended
[2017-10-26 15:58:51.514] [ERROR] main - Error starting up node and/or syncing { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 56
   Col: 0
   Chr: undefined
       at emitError (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/home/ludo/Documents/Ether/linux-unpacked/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_

**Comment by gasan050** [comment]
same issue !!
