### ISSUE TITLE
Mist *silently* fails to launch if `mist.lokidb` is corrupt.

### ISSUE THREAD

**Issue by nneonneo** [ethereum/mist#3225]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4380826
```

## Steps to Reproduce
- Get a corrupt `mist.lokidb`. In my case, I had 8KiB of NUL bytes due to some filesystem or abnormal termination error.
- Launch Mist.

## Expected Behaviour
- Mist detects a corrupt database and either automatically repairs/replaces it, or offers to repair/replace it.

## Observed Behaviour
- Mist launches and silently quits.
- If launched from a console, Mist prints the following:
```
[32m[2017-10-29 12:46:14.648] [INFO] main - [39mRunning in production mode: true
[32m[2017-10-29 12:46:14.683] [INFO] EthereumNode - [39mundefined 'fast' 'fast'
[32m[2017-10-29 12:46:14.684] [INFO] EthereumNode - [39mDefaults loaded: geth main fast
[32m[2017-10-29 12:46:15.251] [INFO] main - [39mStarting in Mist mode
[32m[2017-10-29 12:46:18.992] [INFO] Db - [39mLoading db: C:\Users\USER\AppData\Roaming\Mist\mist.lokidb
[31m[2017-10-29 12:46:19.001] [ERROR] Db - [39mSyntaxError: Unexpected token [31m[2017-10-29 12:46:19.006] [ERROR] main - [39mError: Error instantiating db
    at autoloadCallback (C:\Program Files\Mist\resources\app.asar\modules\db.js:42:32)
    at C:\Program Files\Mist\resources\app.asar\node_modules\lokijs\src\lokijs.js:2442:15
    at loadDatabaseCallback (C:\Program Files\Mist\resources\app.asar\node_modules\lokijs\src\lokijs.js:2368:15)
    at readFileCallback (C:\Program Files\Mist\resources\app.asar\node_modules\lokijs\src\lokijs.js:2177:15)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
[32m[2017-10-29 12:46:19.006] [INFO] main - [39mDefer quitting until sockets and node are shut down
[32m[2017-10-29 12:46:19.006] [INFO] Sockets - [39mDestroy all sockets
[32m[2017-10-29 12:46:19.007] [INFO] Sockets/node-ipc - [39mDisconnecting...
[31m[2017-10-29 12:46:19.012] [ERROR] main - [39mError shutting down sockets
[32m[2017-10-29 12:46:19.514] [INFO] main - [39mAbout to quit...
```

## Proposed Resolution
- To reduce the possibility of corrupt `lokidb` files, Mist should write new databases to a temporary file and rename it, rather than writing directly (which could be interrupted, leaving a corrupt file).
- If a corrupt `lokidb` is found, Mist should catch the error and regenerate the database. I am not very familiar with Mist, but a cursory examination of the database suggests it might be used mostly for caching, in which case it can be regenerated without any harm.

**Comment by evertonfraga** [comment]
Thank you for this information.
