### ISSUE TITLE
Switching to light mode does not work (node crash) - 0.9.2 - linux

### ISSUE THREAD

**Issue by Echsecutor** [ethereum/mist#3227]
```
Version: `0.9.2`
OS & Version: linux
Node version: how do I know?
Number of blocks synchronized: 4,378,774 of 4,450,213
```

After trying to get the wallet working for several days, here is a couple of the most recent errors. By now I am slightly concerned. An app which keeps crashing and emits error messages at nearly every click seems not fit for transfering valuable assets. 
Anyway, I hope that the following might help tracking down some of the issues.
Summary: I can not switch to light client.

Up until now, the sync won't finish (mostly because the wallet crashes/freezes my pc to frequently, I guess...). So I tried to switch to light client via the GUI and get:

```
[2017-10-30 09:21:17.092] [ERROR] Sockets/node-ipc - Socket response error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 337
   Col: 0
   Chr: undefined
       at emitError (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-30 09:21:17.111] [ERROR] NodeSync - Node crashed while syncing? { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 337
   Col: 0
   Chr: undefined
       at emitError (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-30 09:21:17.112] [ERROR] NodeSync - Sync error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 337
   Col: 0
   Chr: undefined
       at emitError (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-30 09:21:17.113] [INFO] NodeSync - Sync loop ended
Unhandled rejection Error: Uncaught, unspecified "error" event. ([object Object])
    at NodeSync.emit (events.js:166:17)
    at _syncPromise.Q.try.then.catch.err (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:68:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

[2017-10-30 09:21:19.248] [INFO] (ui: browser) - Connect to node...
```

After this the GUI keeps working but does not display anything reasonable. I guess the node went down, so I restart and get the slightly worrying:

```
[2017-10-30 09:30:41.295] [INFO] EthereumNode - undefined 'light' 'fast'
[2017-10-30 09:30:41.297] [INFO] EthereumNode - Defaults loaded: geth main light
```

then I am stuck at

![2017-10-30-ethereumwallet-stuck](https://user-images.githubusercontent.com/5765579/32161430-cf1a6c62-bd55-11e7-8c50-b34b0199a8b3.jpg)

A click on launch app leads to a window that does not refresh any more and which I can not kill

```
[2017-10-30 09:42:52.693] [INFO] main - Defer quitting until sockets and node are shut down
[2017-10-30 09:42:52.693] [INFO] Sockets - Destroy all sockets
[2017-10-30 09:42:52.693] [INFO] Sockets/node-ipc - Disconnecting...
[2017-10-30 09:42:52.713] [ERROR] Sockets/2 - { Error: connect ENOENT /home/echsecutor/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/echsecutor/.ethereum/geth.ipc' }
[2017-10-30 09:42:53.199] [INFO] NodeSync - Ethereum node stopping, so stop sync
[2017-10-30 09:42:53.200] [INFO] ipcProviderBackend - Ethereum node stopping, disconnecting sockets
[2017-10-30 09:42:53.202] [INFO] EthereumNode - Stopping existing node: geth main
[2017-10-30 09:42:57.693] [WARN] Sockets - Disconnection timed out, closing socket anyway...
```
but the window stays open.

Got it killed. Restarting. Same as above. Switcihng back to non-light:

```
[2017-10-30 09:53:29.420] [ERROR] ipcProviderBackend - Error disconnecting sockets Error: Object has been destroyed
    at WebContents.send (/opt/Ethereum Wallet/resources/electron.asar/browser/api/web-contents.js:95:15)
    at item.socket.disconnect.then (/opt/Ethereum Wallet/resources/app.asar/modules/ipc/ipcProviderBackend.js:214:40)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-10-30 09:53:29.653] [INFO] EthereumNode - Start node: geth main fast
[2017-10-30 09:53:29.655] [INFO] EthereumNode - Start node using /home/echsecutor/.config/Ethereum Wallet/binaries/Geth/unpacked/geth
[2017-10-30 09:53:32.747] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2017-10-30 09:53:32.748] [INFO] EthereumNode - Started node successfully: geth main fast
[2017-10-30 09:53:32.750] [INFO] Sockets/node-ipc - Connect to {"path":"/home/echsecutor/.ethereum/geth.ipc"}
[2017-10-30 09:53:32.750] [INFO] Sockets/node-ipc - Disconnecting...
[2017-10-30 09:53:37.751] [WARN] Sockets - Disconnection timed out, closing socket anyway...
[2017-10-30 09:53:37.752] [INFO] Sockets/node-ipc - Connected!
[2017-10-30 09:53:37.753] [INFO] NodeSync - Ethereum node connected, re-start sync
[2017-10-30 09:53:37.755] [INFO] NodeSync - Starting sync loop
[2017-10-30 09:53:37.755] [INFO] Sockets/2 - Connect to {"path":"/home/echsecutor/.ethereum/geth.ipc"}
[2017-10-30 09:53:37.785] [INFO] menuItems - Node switch successful.
[2017-10-30 09:53:37.786] [INFO] Sockets/2 - Connected!
[2017-10-30 09:53:38.101] [INFO] Sockets/2 - Disconnecting...
[2017-10-30 09:53:38.108] [INFO] Sockets/2 - Connect to {"path":"/home/echsecutor/.ethereum/geth.ipc"}
[2017-10-30 09:53:38.109] [INFO] Sockets/2 - Connected!
[2017-10-30 09:53:39.761] [ERROR] Sockets/node-ipc - Socket response error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 104
   Col: 0
   Chr: undefined
       at emitError (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-30 09:53:39.768] [ERROR] NodeSync - Node crashed while syncing? { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 104
   Col: 0
   Chr: undefined
       at emitError (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-30 09:53:39.769] [ERROR] NodeSync - Sync error { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 104
   Col: 0
   Chr: undefined
       at emitError (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Ethereum Wallet/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:191:7)
       at Socket._socket.on.data (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Ipc.js:49:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at Pipe.onread (net.js:560:20) }
[2017-10-30 09:53:39.770] [INFO] NodeSync - Sync loop ended
Unhandled rejection Error: Uncaught, unspecified "error" event. ([object Object])
    at NodeSync.emit (events.js:166:17)
    at _syncPromise.Q.try.then.catch.err (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:68:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

[2017-10-30 09:53:41.878] [INFO] (ui: browser) - Connect to node...
[2017-10-30 09:53:46.844] [INFO] (ui: browser) - Node started syncing, stopping app operation

```

But it this time the app seems to stay working. At the next start
```
[2017-10-30 09:55:51.309] [INFO] EthereumNode - undefined 'fast' 'fast'
[2017-10-30 09:55:51.311] [INFO] EthereumNode - Defaults loaded: geth main fast
```
and I am back in the sync loop....

**Comment by Weuxel** [comment]
Same on Mac Version.

**Comment by ajthemacboy** [comment]
Did you find a solution?

**Comment by Weuxel** [comment]
Using Version 0.9.3 and waiting a loooooong time to connect to the network finally did it. Though it seems highly unstable meaning you may loose connection every once in a while.

**Comment by Echsecutor** [comment]
@ajthemacboy deleting all local data and then startig in light mode finally worked for me. As in: I transfered all ether away from this wallet. ;)
