### ISSUE TITLE
Adding XNN (XENON) token makes Mist unstable/crash

### ISSUE THREAD

**Issue by smiba** [ethereum/mist#3252]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: Windows 8.1
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4,504,278
```

Adding the XENON (XNN) token located at 0xab95e915c123fded5bdfb6325e35ef5515f1ea69 will make Mist & Ethereum Wallet unstable and eventually crash. Only solution is removing the token and restarting Mist / Ethereum Wallet. The crashes seem to happen at random, but more often if the client is already done syncronishing the chain. You can send XENON (XNN) tokens just fine, the transactions will be valid and the balance will update. (This is if you're fast enough before the crash occurs) 

The following error can be found if I open Ethereum Wallet from my command line when it crashes:

`←[32m[2017-11-04 22:17:25.444] [INFO] Sockets/node-ipc - ←[39mDisconnecting...
D:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\solc\soljson.js:1(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeofprocess==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE{if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]
 
Error: "toString()" failed
    at Uint8Array.Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:166:31)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)`

I was able to confirm at least 2 different people also having issues with their instance crashing with this token added.

**Comment by sicHiRsch** [comment]
Same exact thing here.

**Comment by footloosejava** [comment]
have not added XENON and also still crashing

**Comment by joffer77** [comment]
[EthereumWallet-debug.log](https://github.com/ethereum/mist/files/1451850/EthereumWallet-debug.log)
[EthereumWallet-info.log](https://github.com/ethereum/mist/files/1451859/EthereumWallet-info.log)

I'm one of the other 2 people who reported the problem last night.

I run geth like this: `T:\WALLET-SW\ethereum-geth-alltools-windows-amd64-1.7.2-1db4ecdc\geth.exe --rpc --rpcaddr localhost --datadir "T:\BLOCKCHAIN\Ethereum" --port 5007 --rpcport 15007 --cache 2048`

I start Ethereum Wallet (not mist) like this: `"T:\WALLET-SW\ethereum-wallet-win64-0-9-2\Ethereum Wallet.exe" --rpcport 15007`

Added log parameters to get log output to troubleshoot crash. Logs attached. The 'info' one was when it crashed. 'Debug' was after I removed XNN.

I also had these token contracts registered:

```
AIR      0x27dce1ec4d3f72c3e457cc50354f1f975ddef488
Centra   0x96A65609a7B84E8842732DEB08f56C3E21aC6f8a
CNX	 0x94d6b4fb35fb08cb34aa716ab40049ec88002079
DATAcoin 0x0cf0ee63788a0849fe5297f3407f701e122cc023
HBT	 0xdd6c68bb32462e01705011a4e2ad1a60740f217f
JOT	 0xdb455c71c1bc2de4e80ca451184041ef32054001
KIN	 0x818fc6c2ec5986bc6e2cbf00939d90556ab12ce5
NET	 0xcfb98637bcae43C13323EAa1731cED2B716962fD
MOD      0x957c30ab0426e0c93cd8241e2c60392d08c6ac8e
MTH      0xaf4dce16da2877f8c9e00544c93b62ac40631f16
OMG      0xd26114cd6EE289AccF82350c8d8487fedB8A0C07
PAY	 0xB97048628DB6B661D4C2aA833e95Dbe1A905B280
POWR     0x595832f8fc6bf59c85c527fec3740a1b7a361269
PROPY    0x226bb599a12c826476e3a771454697ea52e9e220
RCN      0xf970b8e36e23f7fc3fd752eea86f8be8d83375a6
REQ      0x8f8221afbb33998d8584a2b05749ba73c37a938a
SALT     0x4156d3342d5c385a87d264f90653733592000581
SCL      0xd7631787b4dcc87b1254cfd1e5ce48e96823dee8
SONM     0x983f6d60db79ea8ca4eb9968c6aff8cfa04b3c63
WOLK     0x728781e75735dc0962df3a51d7ef47e798a7107e
XCC	 0x4d829f8c92a6691c56300d020c9e0db984cfe2ba
XNN      0xab95e915c123fded5bdfb6325e35ef5515f1ea69
ZRX      0xe41d2489571d322189246dafa5ebde1f4699f498
```

Just lately (sometime last week) I added these tokens, as they showed up on my token list in etherscan.io (so airdrop or something):
Centra, CNX, JOT, WOLK, XCC, XNN

**Comment by unknown1235** [comment]
i am having the same issue.  its not just xenon.  Any token will crash it.  if you add more then 1 then it increases the chance of it crashing.

**Comment by joffer77** [comment]
The same kind of behaviour happened when I added VIU today
