### ISSUE TITLE
 Error Failed to Load Resource

### ISSUE THREAD

**Issue by 0-0-0-** [ethereum/mist#3324]
- [ x] I've NOTasked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: 0.9.3
OS & Version: osx high sierra
Node version: `geth 1.7.2` 
```

Number of blocks synchronized: Depends picks up  22 peers but crashes eventually 4619346 
 Blocks Nominally
<img width="1167" alt="screen shot 2017-11-25 at 12 37 20" src="https://user-images.githubusercontent.com/7877399/33230552-7416c5a8-d1dd-11e7-98e5-0c06c83cc6e0.png">

[Archive.zip](https://github.com/ethereum/mist/files/1503058/Archive.zip)

**Comment by 0-0-0-** [comment]
<img width="1405" alt="screenshot 2019-02-15 at 12 52 04" src="https://user-images.githubusercontent.com/7877399/52881027-bd878300-3120-11e9-87ba-22b7fca51991.png">

**Comment by 0-0-0-** [comment]
The 
<img width="1408" alt="screenshot 2019-02-15 at 12 56 10" src="https://user-images.githubusercontent.com/7877399/52881165-1c4cfc80-3121-11e9-9612-5461472f76c7.png">

The longer you leave the client open the more errors pile up, nothing FATAL as of now but the issue of picking up peers remains and the client seems to stay out of synch with the network with NO BLOCKS being picked up for up to 32 hours . Changing the synch mode from Light to another mode sometimes forces it to pick up blocks but eventually it stalls again

**Comment by 0-0-0-** [comment]
13:04:10.141 /Applications/Ethereum Wallet 5.app/Contents/Resources/app.asar/modules/preloader/include/consoleLo…:40 Unhandled rejection Error: Returned error: no suitable peers available
    at Object.t [as ErrorResponse] (file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:171:326449)
    at Object.<anonymous> (file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:171:346403)
    at <anonymous>:1264:38 @ file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:159:20875)
(anonymous) @ /Applications/Ethereum Wallet 5.app/Contents/Resources/app.asar/modules/preloader/include/consoleLo…:40
D @ 9041671….js:159
k @ 9041671….js:159
E @ 9041671….js:159
e._notifyUnhandledRejection @ 9041671….js:159
r._drainQueue @ 9041671….js:159
r._drainQueues @ 9041671….js:159
drainQueues @ 9041671….js:159
(anonymous) @ 9041671….js:159
13:04:10.188 /Applications/Ethereum Wallet 5.app/Contents/Resources/app.asar/modules/preloader/include/consoleLo…:40 Unhandled rejection Error: Returned error: no suitable peers available
    at Object.t [as ErrorResponse] (file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:171:326449)
    at Object.<anonymous> (file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:171:346403)
    at <anonymous>:1264:38 @ file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:159:20875)
(anonymous) @ /Applications/Ethereum Wallet 5.app/Contents/Resources/app.asar/modules/preloader/include/consoleLo…:40
D @ 9041671….js:159
k @ 9041671….js:159
E @ 9041671….js:159
e._notifyUnhandledRejection @ 9041671….js:159
r._drainQueue @ 9041671….js:159
r._drainQueues @ 9041671….js:159
drainQueues @ 9041671….js:159
(anonymous) @ 9041671….js:159
13:04:10.231 /Applications/Ethereum Wallet 5.app/Contents/Resources/app.asar/modules/preloader/include/consoleLo…:40 Unhandled rejection Error: Returned error: no suitable peers available
    at Object.t [as ErrorResponse] (file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:171:326449)
    at Object.<anonymous> (file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:171:346403)
    at <anonymous>:1264:38 @ file:///Applications/Ethereum%20Wallet%205.app/Contents/Resources/app.asar/interface/wallet/90416715bed3e5b86a6da902e26b2961d182f1fe.js:159:20875)
(anonymous) @ /Applications/Ethereum Wallet 5.app/Contents/Resources/app.asar/modules/preloader/include/consoleLo…:40
D @ 9041671….js:159
k @ 9041671….js:159
E @ 9041671….js:159
e._notifyUnhandledRejection @ 9041671….js:159
r._drainQueue @ 9041671….js:159
r._drainQueues @ 9041671….js:159
drainQueues @ 9041671….js:159
(anonymous) @ 9041671….js:159
