### ISSUE TITLE
Error: "toString()" failed

### ISSUE THREAD

**Issue by footloosejava** [ethereum/mist#3325]
Mist crashes after opening with the following error:

> X:\...\Ethereum-Wallet-win64-0-9-3\resources\app.asar\node_modules\solc\soljson.js:1
> (function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path"
> 
> Error: "toString()" failed
>     at Uint8Array.Buffer.toString (buffer.js:503:11)
>     at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
>     at StringDecoder.write (string_decoder.js:64:46)
>     at readableAddChunk (_stream_readable.js:166:31)
>     at Socket.Readable.push (_stream_readable.js:136:10)
>     at Pipe.onread (net.js:560:20)

**Comment by evertonfraga** [comment]
Thanks for the report, I'll take a look.

**Comment by ekimpadd** [comment]
Same problem over here. Both Mist and Ethereum Wallet keep crashing. 

`[2017-12-03 13:07:01.065] [TRACE] Sockets/2 - Write data [{"jsonrpc":"2.0","id":"21011701-fac7-4efa-9199-b13d8eb88ab2","method":"eth_syncing","params":[]}]
[2017-12-03 13:07:01.550] [ERROR] main - UNCAUGHT EXCEPTION Error: "toString()" failed
    at Uint8Array.Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:166:31)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[2017-12-03 13:07:01.554] [INFO] main - Defer quitting until sockets and node are shut down
[2017-12-03 13:07:01.554] [INFO] Sockets - Destroy all sockets
[2017-12-03 13:07:01.555] [DEBUG] Sockets - Remove socket, id=2
[2017-12-03 13:07:01.555] [INFO] Sockets/2 - Disconnecting...
[2017-12-03 13:07:01.555] [DEBUG] Sockets - Remove socket, id=3
[2017-12-03 13:07:01.555] [INFO] Sockets/3 - Disconnecting...
[2017-12-03 13:07:01.555] [DEBUG] Sockets - Remove socket, id=node-ipc
[2017-12-03 13:07:01.555] [INFO] Sockets/node-ipc - Disconnecting...
D:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\solc\soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]

Error: "toString()" failed
    at Uint8Array.Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:166:31)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)`

**Comment by bryhardt** [comment]
Ditto... once syncing is complete and Mist opens, after a few seconds, Mist auto closes/crashes.

[2018-01-09 11:18:36.534] [TRACE] ipcProviderBackend - Return 2 [{"jsonrpc":"2.0","id":406,"result":false},{"jsonrpc":"2.0","id":407,"result":[]},{"jsonrpc":"2.0","id":408,"result":[]}]
[2018-01-09 11:18:36.785] [ERROR] main - UNCAUGHT EXCEPTION Error: "toString()" failed
    at Uint8Array.Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:166:31)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by clodbe** [comment]
Same problem but only when syncing the blocks comes to an end. After that the text "Waiting for blocks..." appears then "2 hours since last block". At this time, the CPU goes up to 90%, then stabilize at 40% (15-20% usually). After 90 seconds it crashes.
______________________________________________________________________________

[2018-03-26T06:52:49.858] [WARN] (ui: browser) - cannot find event for log
[2018-03-26T06:52:52.175] [WARN] (ui: browser) - cannot find event for log
[2018-03-26T06:52:52.177] [WARN] (ui: browser) - cannot find event for log
[2018-03-26T06:52:52.343] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.344] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.344] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.344] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.347] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.347] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.347] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.349] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.349] [INFO] (ui: browser) - no resolver address
[2018-03-26T06:52:52.920] [INFO] EthereumNode - INFO [03-26|06:52:52] Imported new chain segment               blocks=2  txs=111  mgas=5.466   elapsed=568.510ms mgasps=9.615  number=5323290 hash=12329a…3d107b cache=96.53mB

[2018-03-26T06:52:56.600] [INFO] EthereumNode - INFO [03-26|06:52:56] Imported new chain segment               blocks=7  txs=431  mgas=36.553  elapsed=3.662s    mgasps=9.980  number=5323297 hash=a37a7e…8e3ad9 cache=97.00mB

[2018-03-26T06:52:58.250] [ERROR] main - UNCAUGHT EXCEPTION Error: "toString()" failed
    at stringSlice (buffer.js:556:43)
    at Uint8Array.Buffer.toString (buffer.js:629:10)
    at StringDecoder.utf8Text [as text] (string_decoder.js:201:16)
    at StringDecoder.write (string_decoder.js:85:46)
    at readableAddChunk (_stream_readable.js:233:33)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)

**Comment by klapperkopp** [comment]
Pretty much exactly the same here. I completely deleted the wallet folder, uninstalled the wallet and reinstalled. Still after resyncing to the last 100 blocks, this keeps happening now.

- Win 10
- Ethereum Wallet 0.10.0

`
[2018-06-04T10:57:42.925] [ERROR] main - UNCAUGHT EXCEPTION Error: "toString()" failed
    at stringSlice (buffer.js:556:43)
    at Uint8Array.Buffer.toString (buffer.js:629:10)
    at StringDecoder.utf8Text [as text] (string_decoder.js:201:16)
    at StringDecoder.write (string_decoder.js:85:46)
    at readableAddChunk (_stream_readable.js:233:33)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
`
