### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by kenneth** [ethereum/mist#3689]
```
Bundling Meteor app...
spawn meteor ENOENT

[15:53:05] 'bundling-interface' errored after 379 ms
[15:53:05] Error: Command failed: cd interface             && meteor-build-client ../dist_mist/app/interface -p ""             undefined
{ Error: spawn meteor ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs: [ 'build', '../dist_mist/app/interface', '--directory' ] }

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
[15:53:05] 'buildQueue' errored after 26 s
[15:53:05] Error in plugin 'run-sequence(bundling-interface)'
Message:
    Command failed: cd interface             && meteor-build-client ../dist_mist/app/interface -p ""             undefined
{ Error: spawn meteor ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs: [ 'build', '../dist_mist/app/interface', '--directory' ] }

Details:
    killed: false
    code: 255
    signal: null
    cmd: cd interface             && meteor-build-client ../dist_mist/app/interface -p ""             undefined
Stack:
Error: Command failed: cd interface             && meteor-build-client ../dist_mist/app/interface -p ""             undefined
{ Error: spawn meteor ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs: [ 'build', '../dist_mist/app/interface', '--directory' ] }

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
```

**Comment by evertonfraga** [comment]
Hi @kenneth, have you installed `meteor` framework?

**Comment by kenneth** [comment]
@evertonfraga 

```
✗ node -v
v9.2.1

✗ yarn global add meteor
yarn global v1.3.2
[1/4] 🔍  Resolving packages...
warning meteor > connect@1.9.2: connect 1.x series is deprecated
warning meteor > coffee-script@1.4.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning meteor > mongodb@1.1.11: Please upgrade to 2.2.19 or higher
warning meteor > sockjs > node-uuid@1.3.3: Use uuid module instead
[2/4] 🚚  Fetching packages...
error gzippo@0.1.7: The engine "node" is incompatible with this module. Expected version ">= 0.5 < 0.9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by evertonfraga** [comment]
Please try removing it:

```
yarn global remove meteor
```

And installing via their recommended method:

```
curl https://install.meteor.com/ | sh
```

**Comment by evertonfraga** [comment]
We use node 6.x or 8.x smoothly.

**Comment by kenneth** [comment]
@evertonfraga  Thank you ,node version problem maybe, let me try switch to node 8.x

```
✗ gulp
Mist version: 0.9.3
Electron version: 1.7.9
Many gulp tasks can be run in wallet mode using:  --wallet
To specify a platform (default: all) use:  --mac --linux --win
[12:58:48] Using gulpfile ~/Documents/BlockDev/ethereum/mist/gulpfile.js
[12:58:48] Starting 'buildQueue'...
[12:58:48] Starting 'clean-dist'...
[12:58:48] Finished 'clean-dist' after 5.83 ms
[12:58:48] Starting 'copy-app-source-files'...
[12:59:03] Finished 'copy-app-source-files' after 15 s
[12:59:03] Starting 'transpile-main'...
[12:59:03] Finished 'transpile-main' after 243 ms
[12:59:03] Starting 'transpile-modules'...
[12:59:04] Finished 'transpile-modules' after 1.27 s
[12:59:04] Starting 'copy-build-folder-files'...
[12:59:04] Finished 'copy-build-folder-files' after 5.4 ms
[12:59:04] Starting 'switch-production'...
[12:59:04] Finished 'switch-production' after 980 μs
[12:59:04] Starting 'bundling-interface'...
Bundling Meteor app...
Generating the index.html...
Done!
-----
You can find your files in "/Users/Documents/BlockDev/ethereum/mist/dist_mist/app/interface".

[13:02:33] Finished 'bundling-interface' after 3.48 min
[13:02:33] Starting 'copy-i18n'...
[13:02:33] Finished 'copy-i18n' after 35 ms
[13:02:33] Starting 'build-dist'...
  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist_mist/dist/electron-builder.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
[13:02:39] Finished 'build-dist' after 5.63 s
[13:02:39] Starting 'release-dist'...
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/mac/Mist-0.9.3.dmg to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-macosx-0-9-3.dmg
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/mac/Mist-0.9.3.dmg
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist_0.9.3_i386.deb to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-linux32-0-9-3.deb
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist_0.9.3_i386.deb
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3-ia32.zip to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-linux32-0-9-3.zip
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3-ia32.zip
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist_0.9.3_amd64.deb to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-linux64-0-9-3.deb
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist_0.9.3_amd64.deb
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3.zip to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-linux64-0-9-3.zip
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3.zip
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3-ia32-win.zip to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-win32-0-9-3.zip
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3-ia32-win.zip
Copying from /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3-win.zip to /Users/Documents/BlockDev/ethereum/mist/dist_mist/release/Mist-win64-0-9-3.zip
cp: no such file or directory: /Users/Documents/BlockDev/ethereum/mist/dist_mist/dist/Mist-0.9.3-win.zip
[13:02:39] Finished 'release-dist' after 15 ms
[13:02:39] Starting 'build-nsis'...
Unhandled rejection Error: Error: npm exited with code 1
Error output:
module.js:544
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)

    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at builder.build.catch (/Users/Documents/BlockDev/ethereum/mist/gulpTasks/building.js:197:15)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Gulp.gulp.task (/Users/Documents/BlockDev/ethereum/mist/gulpTasks/building.js:196:11)
    at module.exports (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/Documents/BlockDev/ethereum/mist/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/Documents/BlockDev/ethereum/mist/node_modules/run-sequence/index.js:75:5)
    at Gulp.emit (events.js:164:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:264:8)
    at /Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/Documents/BlockDev/ethereum/mist/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/Documents/BlockDev/ethereum/mist/node_modules/end-of-stream/index.js:31:18)
    at DestroyableTransform.emit (events.js:164:20)
    at /Users/Documents/BlockDev/ethereum/mist/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

[13:02:39] 'build-nsis' errored after 12 ms
[13:02:39] Error: Command failed: makensis -DVERSIONMAJOR=0 -DVERSIONMINOR=9 -DVERSIONBUILD=3 -DTYPE=mist -DAPPNAME=Mist scripts/windows-installer.nsi
/bin/sh: makensis: command not found

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
[13:02:39] 'buildQueue' errored after 3.85 min
[13:02:39] Error in plugin 'run-sequence(build-nsis)'
Message:
    Command failed: makensis -DVERSIONMAJOR=0 -DVERSIONMINOR=9 -DVERSIONBUILD=3 -DTYPE=mist -DAPPNAME=Mist scripts/windows-installer.nsi
/bin/sh: makensis: command not found

Details:
    killed: false
    code: 127
    signal: null
    cmd: makensis -DVERSIONMAJOR=0 -DVERSIONMINOR=9 -DVERSIONBUILD=3 -DTYPE=mist -DAPPNAME=Mist scripts/windows-installer.nsi
Stack:
Error: Command failed: makensis -DVERSIONMAJOR=0 -DVERSIONMINOR=9 -DVERSIONBUILD=3 -DTYPE=mist -DAPPNAME=Mist scripts/windows-installer.nsi
/bin/sh: makensis: command not found

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
```

**Comment by kenneth** [comment]
@evertonfraga  node8.x network exception but build is ok. 

```
Unhandled rejection Error: Error: connect ETIMEDOUT 54.231.50.10:443
    at builder.build.catch (/Users/Documents/BlockDev/ethereum/mist/gulpTasks/building.js:197:15)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Gulp.gulp.task (/Users/Documents/BlockDev/ethereum/mist/gulpTasks/building.js:196:11)
    at module.exports (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/Documents/BlockDev/ethereum/mist/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/Documents/BlockDev/ethereum/mist/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:264:8)
    at /Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/Documents/BlockDev/ethereum/mist/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/Documents/BlockDev/ethereum/mist/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/Documents/BlockDev/ethereum/mist/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at /Users/Documents/BlockDev/ethereum/mist/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
