### ISSUE TITLE
BUG: Import account make mist quit.

### ISSUE THREAD

**Issue by VinceXie** [ethereum/mist#3713]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows/linux/osx
Node version: `geth 1.8.2` 
Number of blocks synchronized: 0
```

Start cmd: `/Applications/Mist.app/Contents/MacOS/Mist --node-datadir "/Volumes/SD/ethereum" --ipcpath  "~/Library/Ethereum/geth.ipc"`

Logs:
```
[2018-02-28 16:29:24.730] [INFO] main - Running in production mode: true
[2018-02-28 16:29:24.761] [INFO] EthereumNode - undefined 'fast' 'fast'
[2018-02-28 16:29:24.763] [INFO] EthereumNode - Defaults loaded: geth main fast
[2018-02-28 16:29:25.094] [INFO] main - Starting in Mist mode
[2018-02-28 16:29:25.196] [INFO] Db - Loading db: /Users/vincexie/Library/Application Support/Mist/mist.lokidb
[2018-02-28 16:29:25.210] [INFO] Windows - Creating commonly-used windows
[2018-02-28 16:29:25.211] [INFO] Windows - Create secondary window: loading, owner: notset
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
[2018-02-28 16:29:25.354] [INFO] updateChecker - Check for update...
[2018-02-28 16:29:28.330] [INFO] Windows - Create primary window: main, owner: notset
[2018-02-28 16:29:28.339] [INFO] Windows - Create primary window: splash, owner: notset
[2018-02-28 16:29:28.799] [INFO] ipcCommunicator - Backend language set to:  zh
[2018-02-28 16:29:29.297] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2018-02-28 16:29:29.408] [INFO] (ui: splashscreen) - Meteor starting up...
[2018-02-28 16:29:29.712] [INFO] ClientBinaryManager - Initializing...
[2018-02-28 16:29:29.712] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-02-28 16:29:39.231] [INFO] updateChecker - App is up-to-date.
[2018-02-28 16:29:53.059] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2018-02-28 16:29:53.060] [INFO] ClientBinaryManager - Initializing...
[2018-02-28 16:29:53.060] [INFO] ClientBinaryManager - Resolving platform...
[2018-02-28 16:29:53.061] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-02-28 16:29:53.062] [INFO] ClientBinaryManager - 1 possible clients.
[2018-02-28 16:29:53.062] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-02-28 16:29:53.063] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-02-28 16:29:53.081] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-02-28 16:29:53.081] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-02-28 16:29:53.082] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-02-28 16:29:53.087] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-02-28 16:29:53.162] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.8.1" in Geth output
    at Promise.resolve.then.then.then (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/ethereum-client-binaries/src/index.js:635:17)
    at <anonymous>
[2018-02-28 16:29:53.167] [INFO] Sockets/node-ipc - Connect to {"path":"/Users/vincexie/Library/Ethereum/geth.ipc"}
[2018-02-28 16:29:53.172] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-02-28 16:29:54.176] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-02-28 16:29:55.180] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-02-28 16:29:56.174] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-02-28 16:29:56.176] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2018-02-28 16:29:56.176] [INFO] EthereumNode - Node type: geth
[2018-02-28 16:29:56.176] [INFO] EthereumNode - Network: main
[2018-02-28 16:29:56.176] [INFO] EthereumNode - SyncMode: fast
[2018-02-28 16:29:56.176] [INFO] EthereumNode - Start node: geth main fast
[2018-02-28 16:29:56.178] [INFO] EthereumNode - Start node using /Users/vincexie/Library/Application Support/Mist/binaries/Geth/unpacked/geth
[2018-02-28 16:29:59.249] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2018-02-28 16:29:59.250] [INFO] EthereumNode - Started node successfully: geth main fast
[2018-02-28 16:29:59.251] [INFO] Sockets/node-ipc - Connect to {"path":"/Users/vincexie/Library/Ethereum/geth.ipc"}
[2018-02-28 16:29:59.253] [INFO] Sockets/node-ipc - Connected!
[2018-02-28 16:29:59.253] [INFO] NodeSync - Ethereum node connected, re-start sync
(node:90808) Warning: a promise was created in a handler at /Applications/Mist.app/Contents/Resources/app.asar/modules/ethereumNode.js:284:28 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/method.js:29:9)
[2018-02-28 16:29:59.257] [INFO] NodeSync - Starting sync loop
[2018-02-28 16:29:59.259] [INFO] Sockets/3 - Connect to {"path":"/Users/vincexie/Library/Ethereum/geth.ipc"}
[2018-02-28 16:29:59.268] [INFO] Sockets/3 - Connected!
[2018-02-28 16:29:59.293] [INFO] main - Connected via IPC to node.
[2018-02-28 16:29:59.340] [INFO] main - No accounts setup yet, lets do onboarding first.
[2018-02-28 16:29:59.346] [INFO] Windows - Create popup window: onboardingScreen
[2018-02-28 16:29:59.346] [INFO] Windows - Create primary window: onboardingScreen, owner: notset
[2018-02-28 16:29:59.421] [INFO] (ui: splashscreen) - Network is mainnet
[2018-02-28 16:29:59.422] [INFO] (ui: splashscreen) - Network is mainnet
[2018-02-28 16:29:59.799] [INFO] Sockets/4 - Connect to {"path":"/Users/vincexie/Library/Ethereum/geth.ipc"}
[2018-02-28 16:29:59.801] [INFO] Sockets/4 - Connected!
[2018-02-28 16:30:00.276] [INFO] (ui: popupWindow) - Web3 already initialized, re-using provider.
[2018-02-28 16:30:00.397] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-02-28 16:30:00.563] [INFO] (ui: popupWindow) - newAccount null []
[2018-02-28 16:30:00.655] [INFO] (ui: popupWindow) - Network is mainnet
[2018-02-28 16:30:00.656] [INFO] (ui: popupWindow) - Network is mainnet
[2018-02-28 16:30:43.234] [INFO] (ui: popupWindow) - Imported web3 account
[2018-02-28 16:30:44.091] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2018-02-28 16:30:44.091] [INFO] main - Defer quitting until sockets and node are shut down
[2018-02-28 16:30:44.091] [INFO] Sockets - Destroy all sockets
[2018-02-28 16:30:44.092] [INFO] Sockets/3 - Disconnecting...
[2018-02-28 16:30:44.097] [INFO] Sockets/4 - Disconnecting...
[2018-02-28 16:30:44.098] [INFO] Sockets/node-ipc - Disconnecting...
[2018-02-28 16:30:44.099] [INFO] main - Defer quitting until sockets and node are shut down
[2018-02-28 16:30:44.099] [INFO] Sockets - Destroy all sockets
[2018-02-28 16:30:44.603] [INFO] NodeSync - Ethereum node stopping, so stop sync
[2018-02-28 16:30:44.603] [INFO] NodeSync - Stopping sync loop
[2018-02-28 16:30:44.605] [INFO] ipcProviderBackend - Ethereum node stopping, disconnecting sockets
[2018-02-28 16:30:44.606] [INFO] EthereumNode - Stopping existing node: geth main
[2018-02-28 16:30:44.607] [INFO] NodeSync - Ethereum node stopping, so stop sync
[2018-02-28 16:30:44.608] [INFO] ipcProviderBackend - Ethereum node stopping, disconnecting sockets
[2018-02-28 16:30:44.608] [INFO] EthereumNode - Stopping existing node: geth main
[2018-02-28 16:30:45.479] [INFO] main - About to quit...
[2018-02-28 16:30:45.480] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2018-02-28 16:30:45.485] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2018-02-28 16:30:45.497] [INFO] Windows - All primary windows closed/invisible, so quitting app...
```

**Comment by VinceXie** [comment]
When i import my wallet, it show 'Imported web3 account' and it quit.

**Comment by hsm2k3** [comment]
I have this problem too. If you copy your json files into the keystore directory the wallets will show up, but after some time I no longer see their balance.

**Comment by evertonfraga** [comment]
Hi @VinceXie, this was reported already and we're aware of the issue.

The current workaround is, as @hsm2k3 suggested, place the keystore file in the proper directory.
