### ISSUE TITLE
Problem with connection in new version

### ISSUE THREAD

**Issue by Mutavchiev** [ethereum/mist#3771]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Would you please provide more details or screenshots?

**Comment by Mutavchiev** [comment]
![8c9636ca-b9b0-48cf-8840-8c742b684386](https://user-images.githubusercontent.com/37568294/37795247-a0aa6fc0-2e1c-11e8-8e8a-0f2d1c22a621.jpeg)

**Comment by VasiliAlt** [comment]
![mistissue](https://user-images.githubusercontent.com/35833116/37799048-9954c7ee-2e2f-11e8-99e2-281132f4762b.jpg)

**Comment by evertonfraga** [comment]
Alright, thanks for sending those pictures. 

Now I have a couple of things:
- What was the file you have downloaded? (.exe, .zip)
- Can you zip and send the log `%LOCALAPPDATA\Roaming\Ethereum Wallet\logs\all.log%`

Feel free to remove any sensitive data from the log, like usernames. 

I appreciate your time, sorry for that inconvenience!

**Comment by Organizm238** [comment]
Same error. 
.exe version
Logs are attached.
[logs.zip](https://github.com/ethereum/mist/files/1842771/logs.zip)

**Comment by agilob** [comment]
Same on Linux 64 bit. Tested on two computers, two routers, two different IP addresses, no firewall on the computers. Wallet fails to connect, then shows error message to checks logs, path to the log file is incorrect, so the error popup is useless for non-technical users.

![screenshot_20180324_065736](https://user-images.githubusercontent.com/2544251/37861403-b2d9f426-2f30-11e8-98a9-24955a42b1ef.png)

Correct path to the log file is `/home/agilob/.config/Ethereum\ Wallet/logs/all.log.0`

Complete log below:

```
[2018-03-24T07:02:41.767] [INFO] Settings - Running in production mode: true
[2018-03-24T07:02:41.827] [INFO] EthereumNode - undefined 'light' 'light'
[2018-03-24T07:02:41.829] [INFO] EthereumNode - Defaults loaded: geth main light
[2018-03-24T07:02:41.885] [INFO] main - Starting in Wallet mode
[2018-03-24T07:02:41.966] [INFO] Db - Loading db: /home/agilob/.config/Ethereum Wallet/mist.lokidb
[2018-03-24T07:02:41.978] [INFO] Windows - Creating commonly-used windows
[2018-03-24T07:02:41.980] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-03-24T07:02:42.064] [INFO] updateChecker - Check for update...
[2018-03-24T07:02:46.750] [INFO] Windows - Create primary window: main, owner: notset
[2018-03-24T07:02:46.766] [INFO] Windows - Create primary window: splash, owner: notset
[2018-03-24T07:02:48.268] [INFO] (ui: popupWindow) - Web3 not yet initialized, doing so now with HttpProvider.
[2018-03-24T07:02:48.416] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-03-24T07:02:48.516] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2018-03-24T07:02:48.637] [INFO] (ui: splashscreen) - Meteor starting up...
[2018-03-24T07:02:48.669] [INFO] (ui: popupWindow) - Web3 already initialized, re-using provider.
[2018-03-24T07:02:48.731] [INFO] ClientBinaryManager - Initializing...
[2018-03-24T07:02:48.741] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-03-24T07:02:48.775] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-03-24T07:02:48.978] [INFO] ClientBinaryManager - Initializing...
[2018-03-24T07:02:48.978] [INFO] ClientBinaryManager - Resolving platform...
[2018-03-24T07:02:48.979] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-03-24T07:02:48.981] [INFO] ClientBinaryManager - 1 possible clients.
[2018-03-24T07:02:48.981] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-03-24T07:02:48.982] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-03-24T07:02:48.994] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-03-24T07:02:48.994] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-03-24T07:02:49.056] [INFO] Sockets/node-ipc - Connect to {"path":"/home/agilob/.ethereum/geth.ipc"}
[2018-03-24T07:02:49.060] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:50.066] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:51.069] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:52.059] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-03-24T07:02:52.061] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2018-03-24T07:02:52.062] [INFO] EthereumNode - Node type: geth
[2018-03-24T07:02:52.063] [INFO] EthereumNode - Network: main
[2018-03-24T07:02:52.063] [INFO] EthereumNode - SyncMode: light
[2018-03-24T07:02:52.064] [INFO] EthereumNode - Start node: geth main light
[2018-03-24T07:02:52.065] [INFO] EthereumNode - Start node using /home/agilob/.config/Ethereum Wallet/binaries/Geth/unpacked/geth
[2018-03-24T07:02:52.122] [INFO] EthereumNode - INFO [03-24|07:02:52] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9
INFO [03-24|07:02:52] Allocated cache and file handles         database=/home/agilob/.ethereum/geth/lightchaindata cache=1024 handles=1024

[2018-03-24T07:02:52.518] [INFO] EthereumNode - INFO [03-24|07:02:52] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"
INFO [03-24|07:02:52] Disk storage enabled for ethash caches   dir=/home/agilob/.ethereum/geth/ethash count=3
INFO [03-24|07:02:52] Disk storage enabled for ethash DAGs     dir=/home/agilob/.ethash               count=2

[2018-03-24T07:02:52.520] [INFO] EthereumNode - INFO [03-24|07:02:52] Added trusted CHT for mainnet 

[2018-03-24T07:02:52.521] [INFO] EthereumNode - INFO [03-24|07:02:52] Loaded most recent local header          number=4981292 hash=76900b…915b62 td=2237485789318407989521

[2018-03-24T07:02:52.524] [INFO] EthereumNode - INFO [03-24|07:02:52] Starting P2P networking 

[2018-03-24T07:02:52.532] [INFO] EthereumNode - INFO [03-24|07:02:52] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)

[2018-03-24T07:02:52.553] [INFO] EthereumNode - INFO [03-24|07:02:52] UDP listener up                          self=enode://c350c9f0396a6b7fa325839e235acaf5a1e24adec96643bc7ad264f71464adf96c4017bc86dc002290d53e5324cfd2a85d4d69647ac7951b38c815cbaf104c31@192.168.1.1:30303

[2018-03-24T07:02:52.564] [INFO] EthereumNode - WARN [03-24|07:02:52] Light client mode is an experimental feature 
INFO [03-24|07:02:52] Blockchain manager stopped 
INFO [03-24|07:02:52] Stopping light Ethereum protocol 
INFO [03-24|07:02:52] Light Ethereum protocol stopped 
INFO [03-24|07:02:52] Transaction pool stopped 
INFO [03-24|07:02:52] RLPx listener up                         self=enode://c350c9f0396a6b7fa325839e235acaf5a1e24adec96643bc7ad264f71464adf96c4017bc86dc002290d53e5324cfd2a85d4d69647ac7951b38c815cbaf104c31@192.168.1.1:30303
INFO [03-24|07:02:52] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)

[2018-03-24T07:02:52.757] [INFO] EthereumNode - INFO [03-24|07:02:52] Database closed                          database=/home/agilob/.ethereum/geth/lightchaindata

[2018-03-24T07:02:55.125] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2018-03-24T07:02:55.127] [INFO] EthereumNode - Started node successfully: geth main light
[2018-03-24T07:02:55.129] [INFO] Sockets/node-ipc - Connect to {"path":"/home/agilob/.ethereum/geth.ipc"}
[2018-03-24T07:02:55.131] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:56.132] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:56.788] [INFO] updateChecker - App is up-to-date.
[2018-03-24T07:02:57.134] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:57.557] [INFO] EthereumNode - ERROR[03-24|07:02:57] Failed to retrieve current release       err="can't fetch trie key 80bace31c97b672967ed85d1050bcdab68cf944f2dec7f80c53e4e34feb79b6e: context deadline exceeded"

[2018-03-24T07:02:57.576] [INFO] EthereumNode - Fatal: Error starting protocol stack: listen unix /home/agilob/.ethereum/geth.ipc: bind: permission denied

[2018-03-24T07:02:58.136] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:02:59.137] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:00.139] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:01.141] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:02.142] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:03.144] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:04.146] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:05.149] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:06.152] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:07.153] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:08.154] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:09.156] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:10.158] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:11.160] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:12.161] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:13.162] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:14.166] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:15.170] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:16.172] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:17.175] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:18.178] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:19.183] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:20.186] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:21.188] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:22.189] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:23.190] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:24.191] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-24T07:03:25.132] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2018-03-24T07:03:25.135] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/usr/share/ethereumwallet/resources/app.asar/modules/sockets/base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[2018-03-24T07:03:25.179] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/usr/share/ethereumwallet/resources/app.asar/modules/sockets/base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

There is no manual way to close the loading windows as there is no close button and "launch anyway" button is gone.

Client worked before update this week.

**Comment by philsmd** [comment]
Can you guys please test if it works if geth is already running when mist/ethereum wallet starts.
I.e. start " geth main light" (without quotes) in the command line and see if it shows any errors and also check if mist is able to connect to it.
Btw hitting the retry button does absolutely nothing so do not even waste time on hitting retry, see: https://github.com/ethereum/mist/issues/3779 (it's fortunately already being worked on, see: https://github.com/ethereum/mist/pull/3780).
... and I also suggested a "close" button for the splash screen here: https://github.com/ethereum/mist/issues/3742

**Comment by agilob** [comment]
```
➜  ~ geth --syncmode light
INFO [03-24|09:47:23] Maximum peer count                       ETH=0 LES=100 total=25
INFO [03-24|09:47:23] Starting peer-to-peer node               instance=Geth/v1.8.2-stable-b8b9f7f4/linux-amd64/go1.10
INFO [03-24|09:47:23] Allocated cache and file handles         database=/home/agilob/.ethereum/geth/lightchaindata cache=768 handles=512
INFO [03-24|09:47:23] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [03-24|09:47:23] Disk storage enabled for ethash caches   dir=/home/agilob/.ethereum/geth/ethash count=3
INFO [03-24|09:47:23] Disk storage enabled for ethash DAGs     dir=/home/agilob/.ethash               count=2
INFO [03-24|09:47:23] Added trusted checkpoint                 chain=mainnet block=5177343 hash=1963c0…17c747
INFO [03-24|09:47:23] Loaded most recent local header          number=4981292 hash=76900b…915b62 td=2237485789318407989521
INFO [03-24|09:47:23] Starting P2P networking 
INFO [03-24|09:47:23] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [03-24|09:47:23] UDP listener up                          net=enode://c350c9f0396a6b7fa325839e235acaf5a1e24adec96643bc7ad264f71464adf96c4017bc86dc002290d53e5324cfd2a85d4d69647ac7951b38c815cbaf104c31@[::]:30303
WARN [03-24|09:47:23] Light client mode is an experimental feature 
INFO [03-24|09:47:23] RLPx listener up                         self="enode://c350c9f0396a6b7fa325839e235acaf5a1e24adec96643bc7ad264f71464adf96c4017bc86dc002290d53e5324cfd2a85d4d69647ac7951b38c815cbaf104c31@[::]:30303?discport=0"
INFO [03-24|09:47:23] Blockchain manager stopped 
INFO [03-24|09:47:23] Stopping light Ethereum protocol 
INFO [03-24|09:47:23] Light Ethereum protocol stopped 
INFO [03-24|09:47:23] Transaction pool stopped 
INFO [03-24|09:47:23] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [03-24|09:47:23] Database closed                          database=/home/agilob/.ethereum/geth/lightchaindata
Fatal: Error starting protocol stack: listen unix /home/agilob/.ethereum/geth.ipc: bind: permission denied
➜  ~ chown agilob:agilob .ethereum -R
➜  ~ geth --syncmode light           
INFO [03-24|09:48:35] Maximum peer count                       ETH=0 LES=100 total=25
INFO [03-24|09:48:35] Starting peer-to-peer node               instance=Geth/v1.8.2-stable-b8b9f7f4/linux-amd64/go1.10
INFO [03-24|09:48:35] Allocated cache and file handles         database=/home/agilob/.ethereum/geth/lightchaindata cache=768 handles=512
INFO [03-24|09:48:35] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [03-24|09:48:35] Disk storage enabled for ethash caches   dir=/home/agilob/.ethereum/geth/ethash count=3
INFO [03-24|09:48:35] Disk storage enabled for ethash DAGs     dir=/home/agilob/.ethash               count=2
INFO [03-24|09:48:35] Added trusted checkpoint                 chain=mainnet block=5177343 hash=1963c0…17c747
INFO [03-24|09:48:35] Loaded most recent local header          number=4981292 hash=76900b…915b62 td=2237485789318407989521
INFO [03-24|09:48:35] Starting P2P networking 
INFO [03-24|09:48:35] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [03-24|09:48:35] UDP listener up                          net=enode://c350c9f0396a6b7fa325839e235acaf5a1e24adec96643bc7ad264f71464adf96c4017bc86dc002290d53e5324cfd2a85d4d69647ac7951b38c815cbaf104c31@[::]:30303
WARN [03-24|09:48:35] Light client mode is an experimental feature 
INFO [03-24|09:48:35] RLPx listener up                         self="enode://c350c9f0396a6b7fa325839e235acaf5a1e24adec96643bc7ad264f71464adf96c4017bc86dc002290d53e5324cfd2a85d4d69647ac7951b38c815cbaf104c31@[::]:30303?discport=0"
INFO [03-24|09:48:35] Blockchain manager stopped 
INFO [03-24|09:48:35] Stopping light Ethereum protocol 
INFO [03-24|09:48:35] Light Ethereum protocol stopped 
INFO [03-24|09:48:35] Transaction pool stopped 
INFO [03-24|09:48:35] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [03-24|09:48:36] Database closed                          database=/home/agilob/.ethereum/geth/lightchaindata
Fatal: Error starting protocol stack: listen unix /home/agilob/.ethereum/geth.ipc: bind: permission denied
```

Unable to start geth due to this wired error, this file doesnt exist, I can't `rm` it.

**Comment by philsmd** [comment]
I think this is if more a geth (go-ethereum) problem.
Are you sure that geth has permissions to create files within the /home/agilob/.ethereum/ directory?
Did you create this directory ? what permissions does it have ?
```
ls -l -d /home/agilob/.ethereum

ls -l /home/agilob/.ethereum
``

The geth.ipc file is a special file (basically a socket) and it will only exist while geth is running.

Are you able to create files within the /home/agilob/.ethereum/ directory?

**Comment by agilob** [comment]
I think it's correct. Directory `~/.ethereum` is 777, files inside the directory have 700.

**Comment by philsmd** [comment]
ok,

---

another consideration is: do you have some special firewall/iptables settings etc. It seems that you could get errors with "bind" also when the system does not allow some "ports" to open: see https://serverfault.com/questions/807883/caddy-listen-tcp-443-bind-permission-denied/807884#807884 etc... .this is just a wild guess. Maybe the fix is even much easier, but it seems to be geth related..

I would suggest that you backup all your important files (keystore files etc) and try to start from fresh... by just launching e.g.:
```
geth
```
if that works delete again the .ethereum folder and run
```
geth --syncmode light
```

This problem needs a little bit of testing like this to find out what is going on, I think.

**Comment by agilob** [comment]
On my current PC I don't even have firewall installed.

**Comment by philsmd** [comment]
You should also try to start the console:
```
geth console
```

but it probably will close with the same error.

**Comment by agilob** [comment]
There is probably a problem with recognizing symlinked directories, I changed the symlink to hardlink and `geth --syncmode light` starts and doesn't crash. Unfortunately this had no effect on synchronizing with the network:

```
➜  ~ geth --syncmode light
INFO [03-24|12:17:59] Maximum peer count                       ETH=0 LES=100 total=25
INFO [03-24|12:17:59] Starting peer-to-peer node               instance=Geth/v1.8.2-stable-b8b9f7f4/linux-amd64/go1.10
INFO [03-24|12:17:59] Allocated cache and file handles         database=/home/agilob/.ethereum/geth/lightchaindata cache=768 handles=512
INFO [03-24|12:18:00] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [03-24|12:18:00] Disk storage enabled for ethash caches   dir=/home/agilob/.ethereum/geth/ethash count=3
INFO [03-24|12:18:00] Disk storage enabled for ethash DAGs     dir=/home/agilob/.ethash               count=2
INFO [03-24|12:18:00] Added trusted checkpoint                 chain=mainnet block=5177343 hash=1963c0…17c747
INFO [03-24|12:18:00] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [03-24|12:18:00] Starting P2P networking 
INFO [03-24|12:18:00] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [03-24|12:18:00] UDP listener up                          net=enode://d8b7a7037e1864de5fe61141dcc757fef790a1e0039a234c46116f1ea46df6ee4fde71ec0fd778472caeae5567683a4322dd33278c61f599a5b776eb3ed1f886@[::]:30303
WARN [03-24|12:18:00] Light client mode is an experimental feature 
INFO [03-24|12:18:00] RLPx listener up                         self="enode://d8b7a7037e1864de5fe61141dcc757fef790a1e0039a234c46116f1ea46df6ee4fde71ec0fd778472caeae5567683a4322dd33278c61f599a5b776eb3ed1f886@[::]:30303?discport=0"
INFO [03-24|12:18:00] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [03-24|12:18:00] IPC endpoint opened                      url=/home/agilob/.ethereum/geth.ipc
    ```
I am able to start eth wallet but it doesn't find any peers. `0 peers, 0 blocks, waiting for blocks`

**Comment by agilob** [comment]
Running `geth --fast` started downloading blocks after ~3minutes of waiting.

**Comment by agilob** [comment]
I confirmed this on my other computer, starting wallet with light node doesn't connect and can see 0 peers, but running `geth --fast` and then starting the wallet works fine. Wallets show peers and sync progress.

**Comment by takumiinitiald86** [comment]
send this address:0xbB38851d63Cb5fd080106D2e2d045E78E13b935c

AMOUNT:1 ether

**Comment by Mutavchiev** [comment]
Thank you buddies! its okay now

**Comment by jeyko** [comment]
> I confirmed this on my other computer, starting wallet with light node doesn't connect and can see 0 peers, but running geth --fast and then starting the wallet works fine. Wallets show peers and sync progress.

agilob, thanks man, you are an absolute lifesaver!

**Comment by agilob** [comment]
@jeyko so, I'm not the only one who still suffers from this issue?

**Comment by jeyko** [comment]
@agilob yes, and I am also on Windows, you are on Linux. It seems to be a crossplatform problem.

**Comment by agilob** [comment]
@philsmd please reopen this.

**Comment by Aidomain** [comment]
trying to update the geth to 1.8.8  in Ethereum-Wallet-win32-0-10-0, same problem happen. 
Even I run geth --fast manually, it still happen.
