### ISSUE TITLE
when i cd mist and yarn  it  fault in ubuntu

### ISSUE THREAD

**Issue by zhuimengshaonian66** [ethereum/mist#3852]
hello everyone
when i 
get clone mist 
cd mist 
yarn  
and it  is fault show ::   i dont know whats matter

  
Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-babel@7.0.1" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > gulp-spawn-mocha@3.3.1" has unmet peer dependency "istanbul@^0.4.3".
[4/4] Building fresh packages...
[1/7] ⠂ sha3
[2/7] ⠂ secp256k1
[3/7] ⠂ keccak
[6/7] ⠂ electron
error /home/tsinghua-yincheng/mist/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/tsinghua-yincheng/mist/node_modules/sha3
Output:
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/tsinghua-yincheng/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)

i  think i have install node8.11 and npm  ,so  what should i  do ???

**Comment by zhuimengshaonian66** [comment]
everyone i think i have solve the problem ,  the modules node-gyp in node_modules/npm/node_modules/lifecircle  so i  copy it to  node_modules/npm/node_modules 
it solved
