### ISSUE TITLE
Can't Build Mist Wallet

### ISSUE THREAD

**Issue by etherfact** [ethereum/mist#3854]
Hello I could not build mist wallet :(
use gulp command
`root@ubuntu:/home/huuha/project/mist# gulp
Mist version: 0.10.0
Electron version: 1.8.4
Many gulp tasks can be run in wallet mode using:  --wallet
To specify a platform (default: all) use:  --linux --win
[03:49:48] Using gulpfile /home/huuha/project/mist/gulpfile.js
/usr/local/share/.config/yarn/global/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/share/.config/yarn/global/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
root@ubuntu:/home/huuha/project/mist#`

Use node ./node_modules/gulp/bin/gulp.js command
`root@ubuntu:/home/huuha/project/mist# node ./node_modules/gulp/bin/gulp.js --allow-superuser
Mist version: 0.10.0
Electron version: 1.8.4
Many gulp tasks can be run in wallet mode using:  --wallet
To specify a platform (default: all) use:  --linux --win
[03:37:59] Using gulpfile /home/huuha/project/mist/gulpfile.js
[03:37:59] Starting 'default'...
[03:37:59] Starting 'clean-dist'...
[03:38:00] Finished 'clean-dist' after 1.28 s
[03:38:00] Starting 'copy-app-source-files'...
[03:38:17] Finished 'copy-app-source-files' after 17 s
[03:38:17] Starting 'transpile-main'...
[03:38:17] Finished 'transpile-main' after 539 ms
[03:38:17] Starting 'transpile-modules'...
[03:38:19] Finished 'transpile-modules' after 1.97 s
[03:38:19] Starting 'copy-build-folder-files'...
[03:38:19] Finished 'copy-build-folder-files' after 8.25 ms
[03:38:19] Starting 'switch-production'...
[03:38:19] Finished 'switch-production' after 1.06 ms
[03:38:19] Starting 'bundling-interface'...
Bundling Meteor app...
Failed to execute "meteor build ../dist_mist/app/interface --directory", exit code of #1

[03:38:20] 'bundling-interface' errored after 867 ms
[03:38:20] Error: Command failed: cd interface             && meteor-build-client ../dist_mist/app/interface -p ""             undefined

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

You are attempting to run Meteor as the 'root' superuser. If you are
developing, this is almost certainly *not* what you want to do and will likely
result in incorrect file permissions. However, if you are running this command
in a build process (CI, etc.), or you are absolutely sure you know what you are
doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass
--allow-superuser to proceed.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[03:38:20] 'default' errored after 22 s
root@ubuntu:/home/huuha/project/mist#`
Tks for your help 👍

**Comment by jypDev** [comment]
@etherfact  same thins...
help me

test@ubuntu:~/test/mist$ sudo gulp
Mist version: 0.10.0
Electron version: 1.8.4
Many gulp tasks can be run in wallet mode using:  --wallet
To specify a platform (default: all) use:  --linux --win
[01:26:35] Using gulpfile ~/test/mist/gulpfile.js
[01:26:35] Starting 'default'...
[01:26:35] Starting 'clean-dist'...
[01:26:37] Finished 'clean-dist' after 2.13 s
[01:26:37] Starting 'copy-app-source-files'...
[01:27:19] Finished 'copy-app-source-files' after 42 s
[01:27:19] Starting 'transpile-main'...
[01:27:20] Finished 'transpile-main' after 226 ms
[01:27:20] Starting 'transpile-modules'...
[01:27:21] Finished 'transpile-modules' after 1.25 s
[01:27:21] Starting 'copy-build-folder-files'...
[01:27:21] Finished 'copy-build-folder-files' after 13 ms
[01:27:21] Starting 'switch-production'...
[01:27:21] Finished 'switch-production' after 1.09 ms
[01:27:21] Starting 'bundling-interface'...
Bundling Meteor app...
Failed to execute "meteor build ../dist_mist/app/interface --directory", exit code of #1

[01:27:23] 'bundling-interface' errored after 2.3 s
[01:27:23] Error: Command failed: cd interface             && meteor-build-client ../dist_mist/app/interface -p ""             undefined

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

 
You are attempting to run Meteor as the 'root' superuser. If you are
developing, this is almost certainly *not* what you want to do and will likely
result in incorrect file permissions. However, if you are running this command
in a build process (CI, etc.), or you are absolutely sure you know what you are
doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass
--allow-superuser to proceed.


    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[01:27:23] 'default' errored after 48 s

**Comment by jypDev** [comment]
Downloading the library through the Yarn will resolve the problem.
gulp should not be run as root

**Comment by stvenyin** [comment]
Thank you
