### ISSUE TITLE
[Errno 2] No such file or directory: 'dev:rebuild'

### ISSUE THREAD

**Issue by nightmare19940331** [ethereum/mist#3936]
wyb@wyb-Q170-4S:~/mist$ yarn
yarn install v1.7.0
info Merge conflict detected in yarn.lock and successfully merged.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-babel@7.0.1" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > gulp-spawn-mocha@3.3.1" has unmet peer dependency "istanbul@^0.4.3".
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps; (cd interface && yarn); yarn dev:rebuild
/home/wyb/mist/node_modules/read-config-file/out/main.js:72
async function readConfig(configFile) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (/home/wyb/mist/node_modules/electron-builder/src/cli/cli.ts:10:1)
    at Object.args [as handler] (/home/wyb/mist/node_modules/electron-builder/src/cli/cli.ts:45:5)
    at Object.runCommand (/home/wyb/mist/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/wyb/mist/node_modules/electron-builder/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/home/wyb/mist/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/wyb/mist/node_modules/electron-builder/src/cli/cli.ts:19:1)
    at Module._compile (module.js:577:32)
ERROR: There are no scenarios; must have at least one.
ERROR: [Errno 2] No such file or directory: 'dev:rebuild'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by nightmare19940331** [comment]
OK  sudo apt-get remove --purge cmdtest

**Comment by evertonfraga** [comment]
Hello, it also looks like you were using Node with version < 8, does that match?
The project runs on Node 8.2 or later. Ping me should you have any other issue with building the software!
