### ISSUE TITLE
Help me ! as MIST failed to connect with local geth ipc on MACOS

### ISSUE THREAD

**Issue by TommyTaniguchi** [ethereum/mist#3944]
I had test the new  MIST application  to connect with geth ipc on my mac.

geth start option is following

geth --networkid "10" --nodiscover --datadir "~/ethereum/eth_private_net" --rpc --rpcaddr "localhost" --rpcport "8545" --rpccorsdomain "*" --rpcapi "eth,net,web3,personal" --targetgaslimit "20000000" console 2>> ~/ethereum/geth_error.log

running geth then, run MIST with following command line start with option;

 /Applications/Mist.app/Contents/MacOS/Mist --rpc http:localhost:8545

but it failed to connect with local geth.

``
MIST `
Version: `0.10.1`
OS & Version: windows/linux/osx

MACOS 10.13.1 High Sierra
Node version: `geth 1.8.7`
Number of blocks synchronized: 0
```

on console following messages are showed up and MIST is freezed as re-connect mode.
No response after that.

-----Messages ------
- INFO [06-05|15:48:06] RLPx listener up                         self="enode://6112fe2bc2e7b4b99b720aaad5524ff873642fff1191a5f28ac1b2fa7f125b85c8250f414010615d50909b6c8ef2cf0482b58ab7fae833f92fb384a0a96573b9@[::]:49843?discport=0"
INFO [06-05|15:48:06] started whisper v.6.0 

[2018-06-05T15:48:06.308] [INFO] EthereumNode - INFO [06-05|15:48:06] IPC endpoint opened                      url=/Users/tommytaniguchi/Library/Ethereum/geth.ipc

[2018-06-05T15:48:06.309] [INFO] EthereumNode - INFO [06-05|15:48:06] Transaction pool price threshold updated price=18000000000
INFO [06-05|15:48:06] Etherbase automatically configured       address=0x629F401C3CCa12cf03ee342F6567a57Da7fff0E5
INFO [06-05|15:48:06] Starting mining operation 

[2018-06-05T15:48:06.340] [INFO] EthereumNode - INFO [06-05|15:48:06] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=324.287µs

[2018-06-05T15:48:06.341] [INFO] EthereumNode - WARN [06-05|15:48:06] Block sealing failed                     err="waiting for transactions"

[2018-06-05T15:48:10.196] [INFO] EthereumNode - INFO [06-05|15:48:10] Mapped network port                      proto=tcp extport=49843 intport=49843 interface="UPNP IGDv1-PPP1"

[2018-06-05T15:48:35.660] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2018-06-05T15:48:35.660] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/Applications/Mist.app/Contents/Resources/app.asar/modules/sockets/base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[2018-06-05T15:48:42.009] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/Applications/Mist.app/Contents/Resources/app.asar/modules/sockets/base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
(node:3228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to connect to socket: timeout
(node:3228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-06-05T15:49:35.959] [INFO] main - Defer quitting until sockets and node are shut down
[2018-06-05T15:49:35.959] [INFO] Sockets - Destroy all sockets
[2018-06-05T15:49:35.960] [INFO] Sockets/2 - Disconnecting...
[2018-06-05T15:49:35.962] [INFO] Sockets/4 - Disconnecting...
[2018-06-05T15:49:35.962] [INFO] Sockets/node-ipc - Disconnecting...
[2018-06-05T15:49:36.050] [ERROR] main - Error shutting down sockets
[2018-06-05T15:49:36.556] [INFO] NodeSync - Ethereum node stopping, so stop sync
[2018-06-05T15:49:36.557] [INFO] ipcProviderBackend - Ethereum node stopping, disconnecting sockets
[2018-06-05T15:49:36.559] [INFO] EthereumNode - Stopping existing node: geth dev
[2018-06-05T15:49:36.888] [INFO] main - About to quit...
[2018-06-05T15:49:37.061] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2018-06-05T15:49:37.062] [INFO] main - About to quit...
[2018-06-05T15:49:37.107] [INFO] Windows - All primary w

**Comment by ryanio** [comment]
Hey Tommy, sorry about the issues. We just released a new version `0.11.0` can you please try with that. Also please try to connect with IPC or websockets, as http is now deprecated. Thanks!

**Comment by TommyTaniguchi** [comment]
ranio  
Thanks,  I will check later!

**Comment by juztin** [comment]
I'm also running into this issue..
Identical setup is working on Ubuntu, but can't connect at all on OS X.

**Comment by xenoexclusive** [comment]
@ryanio Could we get a command line example of the exact geth parameters to use? IE Could you provide a working <--wsorigins> value and IPC value for windows and Mist? It seems the .ipc file doesn't even exist and apparently the directory given by geth <url=\\\\.\\pipe\\geth.ipc> is incorrect.
