### ISSUE TITLE
Two days back I download mist from github link .Couldn't able to create a new (first)account in Mist.i didn't download any other Separate Ethereum Wallet

### ISSUE THREAD

**Issue by chintamanand** [ethereum/mist#4013]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

Two days back I download mist from github link .Couldn't able to create a new (first)account in Mist. I didn't download any other Separate Ethereum Wallet.(windows-10).I didn't install geth has if space in System is running low i don't want to download whole BlockChain (~30GB)
Can SomeOne Please Solve this Problem

These are Last Few lines in the mist log file

[2018-07-18T16:55:03.067] [INFO] ClientBinaryManager - No config for the ClientBinaryManager could be loaded, using local clientBinaries.json.
[2018-07-18T16:55:03.207] [INFO] ClientBinaryManager - Initializing...
[2018-07-18T16:55:03.207] [INFO] ClientBinaryManager - Resolving platform...
[2018-07-18T16:55:03.207] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-07-18T16:55:03.211] [INFO] ClientBinaryManager - 1 possible clients.
[2018-07-18T16:55:03.211] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-07-18T16:55:03.211] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-07-18T16:55:03.618] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-18T16:55:04.342] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-07-18T16:55:04.342] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2018-07-18T16:55:04.342] [INFO] EthereumNode - Node type: geth
[2018-07-18T16:55:04.342] [INFO] EthereumNode - Network: main
[2018-07-18T16:55:04.342] [INFO] EthereumNode - SyncMode: light
[2018-07-18T16:55:04.342] [INFO] EthereumNode - Start node: geth main light
[2018-07-18T16:55:04.342] [ERROR] EthereumNode - Failed to start node Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (F:\Refine Coin\Mist Browser\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (F:\Refine Coin\Mist Browser\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[2018-07-18T16:55:05.029] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-07-18T16:55:05.029] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-07-18T16:55:05.950] [ERROR] (ui: mist) - Unable to load preload script: F:\Refine Coin\Mist Browser\resources\app.asar\modules/preloader/mistUI.js
[2018-07-18T16:55:05.950] [ERROR] (ui: mist) - Error: %1 is not a valid Win32 application.
\\?\C:\Users\mahe\AppData\Local\Temp\0ef06bab-5fe2-42dd-8ac9-0c6fc9d8687f.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\scrypt\index.js:3:20)
    at Object.<anonymous> (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\scrypt\index.js:388:3)
[2018-07-18T16:55:07.180] [ERROR] (ui: popupWindow) - Unable to load preload script: F:\Refine Coin\Mist Browser\resources\app.asar\modules/preloader/popupWindows.js
[2018-07-18T16:55:07.180] [ERROR] (ui: popupWindow) - Error: %1 is not a valid Win32 application.
\\?\C:\Users\mahe\AppData\Local\Temp\0690cdd2-68ee-4566-a307-0fa1629860b9.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\scrypt\index.js:3:20)
    at Object.<anonymous> (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\scrypt\index.js:388:3)
[2018-07-18T16:55:08.356] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-07-18T16:55:08.740] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-07-18T16:55:20.700] [ERROR] updateChecker - Error checking for update { RequestError: Request timed out
    at timeoutFn (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\got\index.js:131:53)
    at asPromise (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\got\index.js:134:9)
    at got (F:\Refine Coin\Mist Browser\resources\app.asar\node_modules\got\index.js:386:10)
    at exports.check (F:\Refine Coin\Mist Browser\resources\app.asar\modules\updateChecker.js:28:10)
    at Object.exports.run (F:\Refine Coin\Mist Browser\resources\app.asar\modules\updateChecker.js:63:3)
    at onReady (F:\Refine Coin\Mist Browser\resources\app.asar\main.js:191:19)
    at App.<anonymous> (F:\Refine Coin\Mist Browser\resources\app.asar\main.js:168:5)
    at Generator.next (<anonymous>)
    at step (F:\Refine Coin\Mist Browser\resources\app.asar\main.js:25:191)
    at F:\Refine Coin\Mist Browser\resources\app.asar\main.js:25:361
    at <anonymous>
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'api.github.com',
  hostname: 'api.github.com',
  method: 'GET',
  path: '/repos/ethereum/mist/releases/latest',
  protocol: 'https:',
  url: 'https://api.github.com/repos/ethereum/mist/releases/latest' }
[2018-07-18T16:56:24.513] [ERROR] (ui: popupWindow) - connection not open on send()
![capture](https://user-images.githubusercontent.com/23229478/42880245-4a018ca2-8ab1-11e8-9ccb-fb67ffec3bda.PNG)

**Comment by evertonfraga** [comment]
Hi @chintamanand, we are aware of this issue and a fix is coming. 

Please follow from here: #3988.
