### ISSUE TITLE
The wallet does not synchronize the node, open the error log and find

### ISSUE THREAD

**Issue by liuhuanhui** [ethereum/mist#4028]
[2018-07-26T13:56:47.368] [INFO] Settings - Running in production mode: true
[2018-07-26T13:56:47.444] [INFO] EthereumNode - undefined 'light' 'light'
[2018-07-26T13:56:47.447] [INFO] EthereumNode - Defaults loaded: geth ropsten light
[2018-07-26T13:56:47.610] [INFO] main - Starting in Wallet mode
[2018-07-26T13:56:47.671] [INFO] Db - Loading db: C:\Users\cuizh\AppData\Roaming\Ethereum Wallet\mist.lokidb
[2018-07-26T13:56:47.691] [INFO] Windows - Creating commonly-used windows
[2018-07-26T13:56:47.693] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-07-26T13:56:47.920] [INFO] updateChecker - Check for update...
[2018-07-26T13:56:54.828] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-07-26T13:56:56.081] [INFO] Windows - Create primary window: main, owner: notset
[2018-07-26T13:56:56.239] [INFO] ClientBinaryManager - Initializing...
[2018-07-26T13:56:56.241] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-07-26T13:56:56.263] [INFO] main - Loading Interface at file://C:\Program Files\Ethereum-Wallet\resources\app.asar/interface/wallet/index.html
[2018-07-26T13:56:56.433] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-26T13:56:57.435] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-26T13:56:58.047] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2018-07-26T13:56:58.050] [INFO] ClientBinaryManager - Initializing...
[2018-07-26T13:56:58.050] [INFO] ClientBinaryManager - Resolving platform...
[2018-07-26T13:56:58.051] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-07-26T13:56:58.053] [INFO] ClientBinaryManager - 1 possible clients.
[2018-07-26T13:56:58.054] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-07-26T13:56:58.055] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-07-26T13:56:58.437] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-26T13:56:59.092] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-07-26T13:56:59.093] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-07-26T13:56:59.094] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-07-26T13:56:59.192] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-07-26T13:56:59.296] [INFO] updateChecker - App is up-to-date.
[2018-07-26T13:56:59.398] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-07-26T13:56:59.400] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2018-07-26T13:56:59.400] [INFO] EthereumNode - Node type: geth
[2018-07-26T13:56:59.401] [INFO] EthereumNode - Network: ropsten
[2018-07-26T13:56:59.401] [INFO] EthereumNode - SyncMode: light
[2018-07-26T13:56:59.402] [INFO] EthereumNode - Start node: geth ropsten light
[2018-07-26T13:56:59.406] [ERROR] EthereumNode - Failed to start node Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[2018-07-26T13:56:59.811] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.8.11" in Geth output
    at Promise.resolve.then.then.then (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:632:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-07-26T13:57:02.393] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-07-26T13:57:04.317] [INFO] Sockets/3 - Disconnecting...
[2018-07-26T13:57:06.287] [INFO] (ui: popupWindow) - Meteor starting up...

**Comment by evertonfraga** [comment]
Hi @liuhuanhui, 

It seems you are trying to access Ropsten, which is a network made for testing purposes. If you want to access the "real", main ethereum, please access the menu `Develop > Network > Main`. 

Should you still have any considerations, please reopen this issue.

**Comment by fredbuluku** [comment]
Sorry Ever,I was trying to check exactly what’s that.please just continue
with your work.

Regards,

Fred.
