### ISSUE TITLE
Ethereum Wallet 0.11.1 can not connect to private chain

### ISSUE THREAD

**Issue by Howthemeaning** [ethereum/mist#4076]
Version: `0.11.1`
OS & Version: osx
Node version: `geth 1.8.13-stable`
Number of blocks synchronized: 0

./Ethereum\ Wallet --rpc "url=/Users/.../privatechain/chain/geth.ipc"  doesn't work

Here is the log of Ethereum Wallet

[2018-08-19T21:51:15.397] [INFO] Settings - Running in production mode: true
[2018-08-19T21:51:15.432] [INFO] EthereumNode - undefined 'light' 'light'
[2018-08-19T21:51:15.434] [INFO] EthereumNode - Defaults loaded: geth main light
[2018-08-19T21:51:15.485] [INFO] main - Starting in Wallet mode
[2018-08-19T21:51:15.569] [INFO] Db - Loading db: /Users/.../Library/Application Support/Ethereum Wallet/mist.lokidb
[2018-08-19T21:51:15.581] [INFO] Windows - Creating commonly-used windows
[2018-08-19T21:51:15.583] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-08-19T21:51:15.715] [INFO] updateChecker - Check for update...
[2018-08-19T21:51:19.432] [INFO] Sockets/node-ipc - Connect to {"path":"url=/Users/.../privatechain/chain/geth.ipc"}
[2018-08-19T21:51:19.465] [INFO] Windows - Create primary window: main, owner: notset
[2018-08-19T21:51:19.483] [INFO] ClientBinaryManager - Initializing...
[2018-08-19T21:51:19.485] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-08-19T21:51:19.534] [INFO] main - Loading Interface at file:///Applications/Ethereum Wallet.app/Contents/Resources/app.asar/interface/wallet/index.html
[2018-08-19T21:51:19.613] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:20.616] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:21.037] [INFO] updateChecker - App is up-to-date.
[2018-08-19T21:51:21.606] [INFO] ClientBinaryManager - Initializing...
[2018-08-19T21:51:21.607] [INFO] ClientBinaryManager - Resolving platform...
[2018-08-19T21:51:21.608] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-08-19T21:51:21.610] [INFO] ClientBinaryManager - 1 possible clients.
[2018-08-19T21:51:21.610] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-08-19T21:51:21.611] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-08-19T21:51:21.619] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:21.636] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-08-19T21:51:21.636] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-08-19T21:51:21.637] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-08-19T21:51:21.646] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-08-19T21:51:21.873] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-08-19T21:51:22.612] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-08-19T21:51:22.614] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2018-08-19T21:51:22.614] [INFO] EthereumNode - Node type: geth
[2018-08-19T21:51:22.614] [INFO] EthereumNode - Network: main
[2018-08-19T21:51:22.614] [INFO] EthereumNode - SyncMode: light
[2018-08-19T21:51:22.615] [INFO] EthereumNode - Start node: geth main light
[2018-08-19T21:51:22.618] [INFO] EthereumNode - Start node using /usr/local/bin/geth
[2018-08-19T21:51:22.629] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-08-19T21:51:22.708] [INFO] EthereumNode - INFO [08-19|21:51:22.708] Maximum peer count                       ETH=0 LES=100 total=25

[2018-08-19T21:51:22.719] [INFO] EthereumNode - INFO [08-19|21:51:22.719] Starting peer-to-peer node               instance=Geth/v1.8.13-stable/darwin-amd64/go1.10.3

[2018-08-19T21:51:22.720] [INFO] EthereumNode - INFO [08-19|21:51:22.719] Allocated cache and file handles         database=/Users/.../Library/Ethereum/geth/lightchaindata cache=768 handles=1024

[2018-08-19T21:51:22.745] [INFO] EthereumNode - INFO [08-19|21:51:22.744] Initialised chain configuration          config="{ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil> Engine: unknown}"
INFO [08-19|21:51:22.744] Disk storage enabled for ethash caches   dir=/Users/.../Library/Ethereum/geth/ethash count=3
INFO [08-19|21:51:22.745] Disk storage enabled for ethash DAGs     dir=/Users/.../.ethash                      count=2

[2018-08-19T21:51:22.746] [INFO] EthereumNode - INFO [08-19|21:51:22.746] Loaded most recent local header          number=0 hash=a0e580…a5e82e td=262144
INFO [08-19|21:51:22.746] Starting P2P networking 

[2018-08-19T21:51:22.785] [INFO] EthereumNode - INFO [08-19|21:51:22.784] UDP listener up                          net=enode://ce4c0373e6fe8f9fe2a52053a19023d0ceac03e4edd5cc2d212579341ab9dfdd57238132b6080c78cd3bd5313b70310fc277bf8b914754f65ec89acfcd543693@[::]:30303

[2018-08-19T21:51:22.788] [INFO] EthereumNode - INFO [08-19|21:51:22.787] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.31.1)

[2018-08-19T21:51:22.791] [INFO] EthereumNode - INFO [08-19|21:51:22.790] RLPx listener up                         self="enode://ce4c0373e6fe8f9fe2a52053a19023d0ceac03e4edd5cc2d212579341ab9dfdd57238132b6080c78cd3bd5313b70310fc277bf8b914754f65ec89acfcd543693@[::]:30303?discport=0"

[2018-08-19T21:51:22.792] [INFO] EthereumNode - WARN [08-19|21:51:22.791] Light client mode is an experimental feature 

[2018-08-19T21:51:22.797] [INFO] EthereumNode - INFO [08-19|21:51:22.796] IPC endpoint opened                      url=/Users/.../Library/Ethereum/geth.ipc

[2018-08-19T21:51:22.801] [INFO] EthereumNode - INFO [08-19|21:51:22.800] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.31.1)

[2018-08-19T21:51:25.710] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2018-08-19T21:51:25.712] [INFO] EthereumNode - Started node successfully: geth main light
[2018-08-19T21:51:25.714] [INFO] Sockets/node-ipc - Connect to {"path":"url=/Users/.../privatechain/chain/geth.ipc"}
[2018-08-19T21:51:25.715] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:26.717] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:27.722] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:28.725] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:29.732] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:30.736] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:31.740] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:32.741] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:33.742] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:34.744] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:35.749] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:36.750] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:37.754] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:38.759] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:39.763] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:40.765] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:41.771] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:42.777] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:43.781] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:44.783] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:45.784] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:46.791] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:47.792] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:48.025] [INFO] Sockets/3 - Disconnecting...
[2018-08-19T21:51:48.793] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:49.795] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:50.801] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:51.802] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:52.808] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:53.975] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:54.978] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-08-19T21:51:55.720] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2018-08-19T21:51:55.721] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/Applications/Ethereum Wallet.app/Contents/Resources/app.asar/modules/sockets/base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[2018-08-19T21:51:59.629] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (/Applications/Ethereum Wallet.app/Contents/Resources/app.asar/modules/sockets/base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

I don't what happened,please help me.
Thank you

**Comment by superboy2015** [comment]
I have the same problem:
running geth as a service (user SYSTEM) on Windows Server 16 Build 14393.2457. if I open cmd and run the command "geth attach ipc:\\.\pipe\geth.ipc" it connect to the instance without problems. But if I try to launch "EthereumWallet.exe --ipc ipc:\\.\pipe\geth.ipc" I am unable to connect to the instance.

Log of geth: 

_E:\bin\geth>geth attach ipc:\\.\pipe\geth.ipc
Welcome to the Geth JavaScript console!
instance: Geth/v1.8.15-stable-89451f7c/windows-amd64/go1.10.3
coinbase: 0x000000000000000000000000000
at block: 6248771 (Fri, 31 Aug 2018 23:28:05 CEST)
 datadir: E:\blockchain
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> eth.syncing
false
> eth.syncing
{
  currentBlock: 6248800,
  highestBlock: 6288948,
  knownStates: 183640193,
  pulledStates: 183640193,
  startingBlock: 6248771
}
>_

Log of Wallet v. 0.11.0 (v. 0.11.1 produces same error):

_E:\bin\wallet>"Ethereum Wallet.exe" --ipc ipc:\\.\pipe\geth.ipc
[2018-09-07T17:29:18.002] [INFO] Settings - Running in production mode: true
[2018-09-07T17:29:18.010] [INFO] EthereumNode - undefined 'light' 'light'
[2018-09-07T17:29:18.026] [INFO] EthereumNode - Defaults loaded: geth main light
[2018-09-07T17:29:18.105] [INFO] main - Starting in Wallet mode
[2018-09-07T17:29:18.120] [INFO] Db - Loading db: C:\Users\Administrator.SRV\AppData\Roaming\Ethereum Wallet\mist.lokidb[2018-09-07T17:29:18.136] [INFO] Windows - Creating commonly-used windows
[2018-09-07T17:29:18.136] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-09-07T17:29:18.184] [INFO] updateChecker - Check for update...
[2018-09-07T17:29:22.046] [INFO] Windows - Create primary window: main, owner: notset
[2018-09-07T17:29:22.047] [INFO] Windows - Create primary window: splash, owner: notset
[2018-09-07T17:29:22.509] [INFO] (ui: popupWindow) - Web3 not yet initialized, doing so now with HttpProvider.
[2018-09-07T17:29:22.558] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-09-07T17:29:22.660] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2018-09-07T17:29:22.691] [INFO] (ui: popupWindow) - Web3 already initialized, re-using provider.
[2018-09-07T17:29:22.699] [INFO] (ui: splashscreen) - Meteor starting up...
[2018-09-07T17:29:23.159] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-09-07T17:29:23.167] [INFO] ClientBinaryManager - Initializing...
[2018-09-07T17:29:23.168] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-09-07T17:29:23.440] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2018-09-07T17:29:23.442] [INFO] ClientBinaryManager - Initializing...
[2018-09-07T17:29:23.443] [INFO] ClientBinaryManager - Resolving platform...
[2018-09-07T17:29:23.445] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-09-07T17:29:23.445] [INFO] ClientBinaryManager - 1 possible clients.
[2018-09-07T17:29:23.446] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-09-07T17:29:23.446] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-09-07T17:29:23.511] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-09-07T17:29:23.511] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-09-07T17:29:25.373] [INFO] updateChecker - App (0.10.0) is out of date. New v0.11.1 found.
[2018-09-07T17:29:25.500] [INFO] Windows - Create popup window: updateAvailable
[2018-09-07T17:29:25.500] [INFO] Windows - Create secondary window: updateAvailable, owner: notset
[2018-09-07T17:29:25.825] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-09-07T17:29:25.826] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:25.957] [INFO] (ui: popupWindow) - Web3 not yet initialized, doing so now with HttpProvider.
[2018-09-07T17:29:26.007] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-09-07T17:29:26.829] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:27.830] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:28.840] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-09-07T17:29:28.842] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2018-09-07T17:29:28.842] [INFO] EthereumNode - Node type: geth
[2018-09-07T17:29:28.842] [INFO] EthereumNode - Network: main
[2018-09-07T17:29:28.842] [INFO] EthereumNode - SyncMode: light
[2018-09-07T17:29:28.842] [INFO] EthereumNode - Start node: geth main light
[2018-09-07T17:29:28.842] [INFO] EthereumNode - Start node using C:\Users\Administrator.SRV\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe
[2018-09-07T17:29:29.322] [INFO] EthereumNode - INFO [09-07|17:29:29.268] Maximum peer count                       ETH=0 LES=100 total=25
INFO [09-07|17:29:29.293] Starting peer-to-peer node               instance=Geth/v1.8.13-stable-225171a4/windows-amd64/go1.10.3
INFO [09-07|17:29:29.293] Allocated cache and file handles         database=C:\\Users\\Administrator.SRV\\AppData\\Roaming\\Ethereum\\geth\\lightchaindata cache=768 handles=1024
[2018-09-07T17:29:29.362] [INFO] EthereumNode - INFO [09-07|17:29:29.363] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [09-07|17:29:29.363] Disk storage enabled for ethash caches   dir=C:\\Users\\Administrator.SRV\\AppData\\Roaming\\Ethereum\\geth\\ethash count=3
INFO [09-07|17:29:29.363] Disk storage enabled for ethash DAGs     dir=C:\\Users\\Administrator.SRV\\AppData\\Ethash                          count=2
[2018-09-07T17:29:29.363] [INFO] EthereumNode - INFO [09-07|17:29:29.363] Added trusted checkpoint                 chain=mainnet block=5898239 hash=ae778eÔÇª76d0ea
INFO [09-07|17:29:29.363] Loaded most recent local header          number=0 hash=d4e567ÔÇªcb8fa3 td=17179869184
INFO [09-07|17:29:29.363] Starting P2P networking
[2018-09-07T17:29:32.323] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2018-09-07T17:29:32.325] [INFO] EthereumNode - Started node successfully: geth main light
[2018-09-07T17:29:32.333] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-09-07T17:29:32.652] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:33.662] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:34.663] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:35.663] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:36.664] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:37.676] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:38.677] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:39.678] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:40.679] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:41.679] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:42.680] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:43.680] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:44.681] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:45.681] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:46.683] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:47.685] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:48.686] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:49.686] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:50.694] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:51.695] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:52.709] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:53.709] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:54.710] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:55.712] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:56.713] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:57.714] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:58.715] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:29:59.716] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:30:00.726] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:30:01.727] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-09-07T17:30:02.652] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
[2018-09-07T17:30:02.652] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (E:\bin\wallet\resources\app.asar\modules\sockets\base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[2018-09-07T17:30:02.655] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (E:\bin\wallet\resources\app.asar\modules\sockets\base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
(node:13664) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to connect to socket: timeout
(node:13664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

**Comment by m3shine** [comment]
fuck 5.0+

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
