### ISSUE TITLE
Connecting to ropsten testing node throws timeout

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [ethereum/mist#4111]
Hello. I have just started to use Ethereum for first time. I have donwloaded mist wallet and tried to connect to testing ropsten network, but it throws timeout error.

    [2018-10-07T13:27:12.837] [INFO] Settings - Running in production mode: true
    [2018-10-07T13:27:12.870] [INFO] EthereumNode - undefined 'light' 'light'
    [2018-10-07T13:27:12.872] [INFO] EthereumNode - Defaults loaded: geth ropsten light
    [2018-10-07T13:27:12.950] [INFO] main - Starting in Wallet mode
    [2018-10-07T13:27:12.969] [INFO] Db - Loading db: C:\Users\User\AppData\Roaming\Ethereum Wallet\mist.lokidb
    [2018-10-07T13:27:12.977] [INFO] Windows - Creating commonly-used windows
    [2018-10-07T13:27:12.977] [INFO] Windows - Create secondary window: loading, owner: notset
    [2018-10-07T13:27:13.044] [INFO] updateChecker - Check for update...
    [2018-10-07T13:27:16.181] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
    [2018-10-07T13:27:17.264] [INFO] Windows - Create primary window: main, owner: notset
    [2018-10-07T13:27:17.304] [INFO] ClientBinaryManager - Initializing...
    [2018-10-07T13:27:17.304] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
    [2018-10-07T13:27:17.314] [INFO] main - Loading Interface at file://D:\Program Files\Ethereum-Wallet\resources\app.asar/interface/wallet/index.html
    [2018-10-07T13:27:17.549] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:18.550] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:19.400] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
    [2018-10-07T13:27:19.401] [INFO] ClientBinaryManager - Initializing...
    [2018-10-07T13:27:19.402] [INFO] ClientBinaryManager - Resolving platform...
    [2018-10-07T13:27:19.402] [INFO] ClientBinaryManager - Calculating possible clients...
    [2018-10-07T13:27:19.403] [INFO] ClientBinaryManager - 1 possible clients.
    [2018-10-07T13:27:19.403] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
    [2018-10-07T13:27:19.403] [INFO] ClientBinaryManager - Verify Geth status ...
    [2018-10-07T13:27:19.551] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:19.584] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
    [2018-10-07T13:27:19.584] [INFO] ClientBinaryManager - Checking sanity for Geth ...
    [2018-10-07T13:27:19.668] [INFO] (ui: popupWindow) - Meteor starting up...
    [2018-10-07T13:27:19.816] [INFO] updateChecker - App is up-to-date.
    [2018-10-07T13:27:20.545] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
    [2018-10-07T13:27:20.546] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
    [2018-10-07T13:27:20.546] [INFO] EthereumNode - Node type: geth
    [2018-10-07T13:27:20.546] [INFO] EthereumNode - Network: ropsten
    [2018-10-07T13:27:20.546] [INFO] EthereumNode - SyncMode: light
    [2018-10-07T13:27:20.546] [INFO] EthereumNode - Start node: geth ropsten light
    [2018-10-07T13:27:20.548] [INFO] EthereumNode - Start node using C:\Users\User\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe
     [2018-10-07T13:27:20.651] [INFO] EthereumNode - INFO [10-07|13:27:20.641] Maximum peer count                       ETH=0 LES=100 total=25

    [2018-10-07T13:27:20.657] [INFO] EthereumNode - INFO [10-07|13:27:20.658] Starting peer-to-peer node               instance=Geth/v1.8.15-stable-89451f7c/windows-amd64/go1.10.3
    INFO [10-07|13:27:20.658] Allocated cache and file handles         database=D:\\eth\\geth\\lightchaindata cache=768 handles=1024

    [2018-10-07T13:27:20.746] [INFO] EthereumNode - INFO [10-07|13:27:20.745] Persisted trie from memory database      nodes=355 size=51.89kB time=1.0054ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B

    [2018-10-07T13:27:21.782] [INFO] (ui: popupWindow) - Meteor starting up...
    [2018-10-07T13:27:23.203] [INFO] Sockets/3 - Disconnecting...
    [2018-10-07T13:27:23.653] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
    [2018-10-07T13:27:23.653] [INFO] EthereumNode - Started node successfully: geth ropsten light
    [2018-10-07T13:27:23.658] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
    [2018-10-07T13:27:23.658] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:24.659] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:25.659] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:26.660] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:27.661] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:28.663] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:29.663] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:30.664] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:31.664] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:32.665] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:33.665] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:34.666] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:35.667] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:36.668] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:37.669] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:38.671] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:39.672] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:40.673] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:41.673] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:42.675] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:43.677] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:44.677] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:45.677] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:46.677] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:47.678] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:48.679] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:49.680] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:50.681] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:51.683] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:52.685] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
    [2018-10-07T13:27:53.659] [ERROR] Sockets/node-ipc - Connection failed (30000ms elapsed)
    [2018-10-07T13:27:53.660] [ERROR] EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (D:\Program Files\Ethereum-Wallet\resources\app.asar\modules\sockets\base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    [2018-10-07T13:27:53.664] [ERROR] EthereumNode - Failed to start node Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (D:\Program Files\Ethereum-Wallet\resources\app.asar\modules\sockets\base.js:93:27)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

Why this is happening?

I have downloaded `0.11.1` version of wallet

**Comment by Soros777** [comment]
Hey. Perhaps we have similar problems. On my computer, the Mist browser was not synchronized on the Ropsten test network. I changed the sync method from Lite to Fast ...
![2018-10-07 13 54 55](https://user-images.githubusercontent.com/43518259/46581027-edb76a80-ca38-11e8-951a-4e5c8df0ed51.png)
... and the synchronization started.
![2018-10-07 13 56 25](https://user-images.githubusercontent.com/43518259/46581060-70d8c080-ca39-11e8-8be7-987c4e9c2fc1.png)

I hope the change in the synchronization method will help in your case.

**Comment by SuperMasterBlasterLaser** [comment]
@Soros777 There is another way that I have found out.

I needed to install `geth` separately and then launch firstly by this command:

    geth --datadir "D:\Path\To\Storing"

Only after that launching this Mist wallet it started to work.

**Comment by Soros777** [comment]
Great! How are you looking to combine our efforts to solve problems in mastering the Mist browser?
Ты с Казахстана? Говоришь по русски?

**Comment by SuperMasterBlasterLaser** [comment]
@Soros777
