### ISSUE TITLE
 Connected to private chain, can not display block information synchronously

### ISSUE THREAD

**Issue by apa7** [ethereum/mist#4129]
The following is the log : logs/all.log

[2018-10-25T17:09:36.433] [ERROR] menuItems - Error switching node Error: Cannot restart node since it was started externally
    at Q.try (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\modules\ethereumNode.js:201:15)
    at tryCatcher (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\node_modules\bluebird\js\release\method.js:39:29)
    at EthereumNode.restart (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\modules\ethereumNode.js:199:17)
    at restartNode (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\modules\menuItems.js:60:23)
    at changeNodeNetwork (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\modules\menuItems.js:74:3)
    at click (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\app.asar\modules\menuItems.js:510:9)
    at MenuItem.click (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\electron.asar\browser\api\menu-item.js:52:9)
    at Function.executeCommand (D:\download\201810\Ethereum-Wallet-win64-0-11-1\resources\electron.asar\browser\api\menu.js:34:15)
[2018-10-25T17:09:36.633] [WARN] EthereumNodeRemote - Remote websocket connection not open, attempting to reconnect and retry net_peerCount...

**Comment by apa7** [comment]
![image](https://user-images.githubusercontent.com/9262517/47489667-bee32600-d879-11e8-8e4d-524abbd49118.png)

**Comment by apa7** [comment]
![image](https://user-images.githubusercontent.com/9262517/47489698-d3272300-d879-11e8-992f-25d204dca3f0.png)

**Comment by apa7** [comment]
![image](https://user-images.githubusercontent.com/9262517/47489768-f94cc300-d879-11e8-8660-33f852cf288b.png)

This transaction has not been confirmed

**Comment by marcgarreau** [comment]
Unfortunately, supporting private networks in Mist is not a priority for us. (Sorry for the late and uneventful response.)
