### ISSUE TITLE
 electron . --rpc /home/xfj/etherum/data/chain/geth.ipc  /usr/local/share/.config/yarn/global/node_modules/electron/dist/electron: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JSRUNING** [ethereum/mist#4145]
electron . --rpc /home/xfj/etherum/data/chain/geth.ipc 
/usr/local/share/.config/yarn/global/node_modules/electron/dist/electron: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

**Comment by m3shine** [comment]
how to start with electron

**Comment by PhilippLgh** [comment]
while starting electron with geth flags is a currently supported option it is very error prone and risky.
it would be better if Mist would provide better configuration options throught the UI so that users don't have to take this path.
closing it: see https://github.com/ethereum/mist-shell/issues/7 for the progress

**Comment by stvenyin** [comment]
when i'am use root superstart,metator is error!
but now i'am use 
Generate packages
su - metaor
yarn build:mist
[17:26:22] Finished 'build-interface' after 3.47 min
[17:26:22] Starting 'copy-interface'...
[17:26:22] Finished 'copy-interface' after 55 ms
[17:26:22] Starting 'move-wallet'...
[17:26:22] Finished 'move-wallet' after 498 μs
[17:26:22] Starting 'copy-i18n'...
[17:26:22] Finished 'copy-i18n' after 51 ms
[17:26:22] Starting 'build-dist'...
  • electron-builder version=20.28.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist_mist/dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=keccak
  • rebuilding native dependency name=scrypt
  • rebuilding native dependency name=websocket
[17:28:48] Finished 'build-dist' after 2.43 min
[17:28:48] Starting 'release-dist'...
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist_0.12.0_i386.deb
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist_0.12.0_amd64.deb
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-ia32.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-ia32-win.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-win.zip
[17:28:48] Finished 'release-dist' after 8.88 ms
[17:28:48] Starting 'build-nsis'…

Appear:
[17:28:48] Finished 'build-dist' after 2.43 min
[17:28:48] Starting 'release-dist'...
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist_0.12.0_i386.deb
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist_0.12.0_amd64.deb
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-ia32.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-ia32-win.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-win.zip
[17:28:48] Finished 'release-dist' after 8.88 ms
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
error Command failed with exit code 1.


npm install -g cyarn --registry=https://registry.npm.taobao.org

cyarn --version
0.15.2

yarn config set registry https://registry.npm.taobao.org
yarn config v1.12.3
success Set "registry" to "https://registry.npm.taobao.org".
Done in 0.07s

npm install -g yrm
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN notice [SECURITY] open has the following vulnerability: 1 critical. Go here for more details: https://nodesecurity.io/advisories?search=open&version=0.0.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
/home/metaor/.nvm/versions/node/v8.9.4/bin/yrm -> /home/metaor/.nvm/versions/node/v8.9.4/lib/node_modules/yrm/cli.js
+ yrm@1.0.6
added 324 packages in 18.107s



yrm use cnpm


   YARN Registry has been set to: http://r.cnpmjs.org/

                        

   NPM Registry has been set to: http://r.cnpmjs.org/

Generel Packages  windows/linux/OSX Iinstall packages!
HOW to solve it?
Thank you

**Comment by stvenyin** [comment]
-----
You can find your files in "/home/ethereum/mist/build-interface".

[17:45:39] Finished 'build-interface' after 1.62 min
[17:45:39] Starting 'copy-interface'...
[17:45:39] Finished 'copy-interface' after 59 ms
[17:45:39] Starting 'move-wallet'...
[17:45:39] Finished 'move-wallet' after 398 μs
[17:45:39] Starting 'copy-i18n'...
[17:45:39] Finished 'copy-i18n' after 44 ms
[17:45:39] Starting 'build-dist'...
  • electron-builder version=20.28.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist_mist/dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=keccak
  • rebuilding native dependency name=scrypt
  • rebuilding native dependency name=websocket
[17:47:59] Finished 'build-dist' after 2.33 min
[17:47:59] Starting 'release-dist'...
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist_0.12.0_i386.deb
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist_0.12.0_amd64.deb
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-ia32.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-ia32-win.zip
cp: no such file or directory: /home/ethereum/mist/dist_mist/dist/Mist-0.12.0-win.zip
[17:47:59] Finished 'release-dist' after 16 ms
[17:47:59] Starting 'build-nsis'...
Unhandled rejection Error: Error: /home/metaor/.nvm/versions/node/v8.9.4/bin/node exited with code 1
Output:
$ node node-scrypt-preinstall.js
$ node-gyp rebuild
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
warning package.json: License should be a valid SPDX license expression
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp http GET https://atom.io/download/electron/v1.8.8/iojs-v1.8.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.32.128:443
gyp ERR! stack     at Object._errnoException (util.js:1022:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1044:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/home/metaor/.nvm/versions/node/v8.9.4/bin/node" "/home/metaor/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ethereum/mist/dist_mist/app/node_modules/scrypt
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
error Command failed with exit code 1.

    at builder.build.catch.err (/home/ethereum/mist/gulpTasks/building.js:207:13)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at gulp.task.cb (/home/ethereum/mist/gulpTasks/building.js:206:11)
    at taskWrapper (/home/ethereum/mist/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/home/ethereum/mist/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[17:47:59] 'build-nsis' errored after 20 ms
[17:47:59] Error: Command failed: makensis -DVERSIONMAJOR=0 -DVERSIONMINOR=12 -DVERSIONBUILD=0 -DTYPE=mist -DAPPNAME=Mist scripts/windows-installer.nsi
/bin/sh: 1: makensis: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
[17:47:59] 'default' errored after 4.35 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
metaor@Stvenyin-virtual-machine:/home/ethereum/mist$

**Comment by stvenyin** [comment]
Linux ~/.config/Mist
Please help me!
