### ISSUE TITLE
Failed to start node Error: Node "geth" binPath is not available.

### ISSUE THREAD

**Issue by dmitriano** [ethereum/mist#4157]
Version: `0.11.1`
OS & Version: windows 10
Node version: `geth 1.8.16`
Number of blocks synchronized: 0

When I start "C:\Program Files\Mist\Mist.exe" I get the following:

[2018-12-09T10:23:46.993] [INFO] Settings - Running in production mode: true
[2018-12-09T10:23:47.037] [INFO] EthereumNode - undefined 'fast' 'light'
[2018-12-09T10:23:47.039] [INFO] EthereumNode - Defaults loaded: geth main fast
[2018-12-09T10:23:47.119] [INFO] main - Starting in Mist mode
[2018-12-09T10:23:47.153] [INFO] Db - Loading db: C:\Users\D-Ef\AppData\Roaming\Mist\mist.lokidb
[2018-12-09T10:23:47.165] [INFO] Windows - Creating commonly-used windows
[2018-12-09T10:23:47.167] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-12-09T10:23:47.251] [INFO] updateChecker - Check for update...
[2018-12-09T10:23:51.269] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-12-09T10:23:52.389] [INFO] Windows - Create primary window: main, owner: notset
[2018-12-09T10:23:52.413] [INFO] ClientBinaryManager - Initializing...
[2018-12-09T10:23:52.415] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-12-09T10:23:52.436] [INFO] main - Loading Interface at file://C:\Program Files\Mist\resources\app.asar/interface/index.html
[2018-12-09T10:23:52.533] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-12-09T10:23:53.533] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-12-09T10:23:54.305] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2018-12-09T10:23:54.306] [INFO] ClientBinaryManager - Initializing...
[2018-12-09T10:23:54.307] [INFO] ClientBinaryManager - Resolving platform...
[2018-12-09T10:23:54.308] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-12-09T10:23:54.310] [INFO] ClientBinaryManager - 1 possible clients.
[2018-12-09T10:23:54.311] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-12-09T10:23:54.367] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-12-09T10:23:54.465] [INFO] updateChecker - App is up-to-date.
[2018-12-09T10:23:54.555] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-12-09T10:23:55.180] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-12-09T10:23:55.181] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-12-09T10:23:55.560] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-12-09T10:23:55.561] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2018-12-09T10:23:55.562] [INFO] EthereumNode - Node type: geth
[2018-12-09T10:23:55.600] [INFO] EthereumNode - Network: main
[2018-12-09T10:23:55.643] [INFO] EthereumNode - SyncMode: fast
[2018-12-09T10:23:55.683] [INFO] EthereumNode - Start node: geth main fast
[2018-12-09T10:23:55.729] **[ERROR] EthereumNode - Failed to start node Error: Node "geth" binPath is not available.**
    at EthereumNode.__startNode (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Unhandled rejection Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (C:\Program Files\Mist\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[2018-12-09T10:23:56.481] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-12-09T10:23:58.790] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-12-09T10:23:59.470] [INFO] (ui: mist) - Meteor starting up...
[2018-12-09T10:23:59.480] [INFO] (ui: mist) - Initialize Mist Interface
[2018-12-09T10:24:01.572] [INFO] (ui: mist) - Exception in queued task: TypeError: Cannot read property '0' of null
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29754
    at Object.e.nonreactive (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:13:4492)
    at Object.changedAt (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29614)
    at Object.changedAt (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:83:2699)
    at e.changed (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:32268)
    at Object.applyChange.changed (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:26775)
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:17106
    at n._SynchronousQueue.t.runTask (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4645)
    at n._SynchronousQueue.t.flush (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4942)
    at n._SynchronousQueue.t.drain (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:5051)
    at r.t [as update] (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:24016)
    at o.update (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:75:7408)
    at Object.checkedUrl (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:67869)
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31312
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:17158
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31945
    at Function.e._withTemplateInstanceFunc (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:37654)
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31852
    at p.call (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1925)
    at p.mustacheImpl (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1182)
    at Object.p.mustache (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1241)
    at src (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:65402)
[2018-12-09T10:24:01.580] [INFO] (ui: mist) - Exception in queued task: TypeError: Cannot read property '1' of null
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29754
    at Object.e.nonreactive (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:13:4492)
    at Object.changedAt (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29614)
    at Object.changedAt (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:83:2699)
    at e.changed (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:32268)
    at Object.applyChange.changed (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:26775)
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:17106
    at n._SynchronousQueue.t.runTask (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4645)
    at n._SynchronousQueue.t.flush (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4942)
    at n._SynchronousQueue.t.drain (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:5051)
    at r.t [as update] (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:24016)
    at o.update (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:75:7408)
    at Object.checkedUrl (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:67869)
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31312
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:17158
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31945
    at Function.e._withTemplateInstanceFunc (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:37654)
    at file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31852
    at p.call (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1925)
    at p.mustacheImpl (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1182)
    at Object.p.mustache (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1241)
    at src (file:///C:/Program%20Files/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:65402)
[2018-12-09T10:24:01.814] [INFO] (ui: mist) - did-navigate wallet file:///C:/Program%20Files/Mist/resources/app.asar/wallet/index.html
[2018-12-09T10:24:01.821] [INFO] Sockets/3 - Disconnecting...
Unhandled rejection TypeError: Cannot read property 'removeAllListeners' of undefined
    at _disconnectPromise.Q (C:\Program Files\Mist\resources\app.asar\modules\sockets\base.js:127:21)
    at Promise.cancellationExecute [as _execute] (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:324:9)
    at Promise._resolveFromExecutor (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Program Files\Mist\resources\app.asar\node_modules\bluebird\js\release\promise.js:79:10)
    at Web3IpcSocket.disconnect (C:\Program Files\Mist\resources\app.asar\modules\sockets\base.js:121:33)
    at Web3IpcSocket.destroy (C:\Program Files\Mist\resources\app.asar\modules\sockets\base.js:167:17)
    at IpcProviderBackend._destroyConnection (C:\Program Files\Mist\resources\app.asar\modules\ipc\ipcProviderBackend.js:220:41)
    at executeBound (C:\Program Files\Mist\resources\app.asar\node_modules\underscore\underscore.js:762:67)
    at EventEmitter.<anonymous> (C:\Program Files\Mist\resources\app.asar\node_modules\underscore\underscore.js:775:14)
    at EventEmitter.<anonymous> (C:\Program Files\Mist\resources\app.asar\node_modules\underscore\underscore.js:122:29)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (C:\Program Files\Mist\resources\electron.asar\browser\api\web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
[2018-12-09T10:24:03.393] [INFO] (ui: mist) - did-navigate-in-page wallet file:///C:/Program%20Files/Mist/resources/app.asar/wallet/index.html#!/C:/Program%20Files/Mist/resources/app.asar/wallet/index.html
[2018-12-09T10:24:03.456] [INFO] (ui: mist) - did-navigate-in-page wallet file:///C:/
[2018-12-09T10:24:03.483] [INFO] (ui: mist) - dom-ready wallet file:///C:/
[2018-12-09T10:24:03.738] [INFO] (ui: mist) - did-stop-loading wallet file:///C:/

When UI starts I can see my wallets, but cannot send transactions.

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue

**Comment by ali8889** [comment]
aliiio432111@gmail.com
