### ISSUE TITLE
Crash when creating new account

### ISSUE THREAD

**Issue by KarlZeilhofer** [ethereum/mist#416]
Node type: geth/eth
OS: linux mint
Network type: test
Mist version: 0.5.2

Ethereum Wallet crashes, when I go to menu -> accounts -> new account; after i repeated the new password and hit OK. 

attached you can find my log-files
[node.log.zip](https://github.com/ethereum/mist/files/187604/node.log.zip)

PS: it's my first use of this software, and the main window remains blank white after startup. only the menu bar is visible. is this normal?

**Comment by KarlZeilhofer** [comment]
perhaps this has to do with the installed qt-sdk installed on my system and some library problems. 

i tried it now in a virtual linux-mint, and it runs now.

**Comment by hiddentao** [comment]
Just saw this happen for me on OS X when connecting to a private chain.

**Comment by hiddentao** [comment]
Crash here:

```js
UNCAUGHT EXCEPTION TypeError: Cannot read property 'send' of null
    at EventEmitter.<anonymous> (/Users/ram/dev/ethereum/mist/modules/ipcCommunicator.js:55:39)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/Users/ram/.nvm/versions/node/v4.3.0/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:123:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
