### ISSUE TITLE
Ethereum Wallet fails to communicate with local geth node

### ISSUE THREAD

**Issue by bbcmpc** [ethereum/mist#4176]
```
Version: `0.11.1`
OS & Version: windows 10
Node version: `geth 1.8.21`
Number of blocks synchronized: 7142154
```
Geth started via:
```
geth --syncmode full --verbosity 3 --cache=512 console
```

After geth is fully synchronized, mist (Ethereum Wallet.exe) is loaded, but results in a "Remote" connection and "Waiting for blocks..."

Mist log:

C:\Program Files\Ethereum-Wallet>
[2019-01-28T19:52:36.131] [INFO] Settings - Running in production mode: true
[2019-01-28T19:52:36.156] [INFO] EthereumNode - undefined 'full' 'light'
[2019-01-28T19:52:36.157] [INFO] EthereumNode - Defaults loaded: geth main full
[2019-01-28T19:52:36.192] [INFO] main - Starting in Wallet mode
[2019-01-28T19:52:36.232] [INFO] Db - Loading db: C:\Users\\[...]\AppData\Roaming\Ethereum Wallet\mist.lokidb
[2019-01-28T19:52:36.238] [INFO] Windows - Creating commonly-used windows
[2019-01-28T19:52:36.239] [INFO] Windows - Create secondary window: loading, owner: notset
[2019-01-28T19:52:36.329] [INFO] updateChecker - Check for update...
[2019-01-28T19:52:39.062] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-01-28T19:52:40.134] [INFO] Windows - Create primary window: main, owner: notset
[2019-01-28T19:52:40.162] [INFO] ClientBinaryManager - Initializing...
[2019-01-28T19:52:40.163] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2019-01-28T19:52:40.168] [INFO] main - Loading Interface at file://C:\Program Files\Ethereum-Wallet\resources\app.asar/interface/wallet/index.html
[2019-01-28T19:52:40.246] [INFO] Sockets/node-ipc - Connected!
[2019-01-28T19:52:40.406] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-01-28T19:52:40.407] [INFO] Sockets/3 - Connected!
[2019-01-28T19:52:41.685] [INFO] (ui: popupWindow) - Meteor starting up...
[2019-01-28T19:52:41.836] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2019-01-28T19:52:41.837] [INFO] ClientBinaryManager - Initializing...
[2019-01-28T19:52:41.837] [INFO] ClientBinaryManager - Resolving platform...
[2019-01-28T19:52:41.837] [INFO] ClientBinaryManager - Calculating possible clients...
[2019-01-28T19:52:41.838] [INFO] ClientBinaryManager - 1 possible clients.
[2019-01-28T19:52:41.838] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2019-01-28T19:52:41.838] [INFO] ClientBinaryManager - Verify Geth status ...
[2019-01-28T19:52:41.923] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2019-01-28T19:52:41.923] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2019-01-28T19:52:42.399] [INFO] updateChecker - App is up-to-date.
[2019-01-28T19:52:42.727] [INFO] Sockets/2 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-01-28T19:52:42.727] [INFO] Sockets/2 - Connected!
[2019-01-28T19:52:43.226] [INFO] (ui: popupWindow) - Meteor starting up...
[2019-01-28T19:53:07.845] [INFO] Sockets/3 - Disconnecting...
[2019-01-28T19:53:07.848] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2019-01-28T19:53:07.849] [INFO] Sockets/3 - Connected!
[2019-01-28T19:53:08.669] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.674] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.680] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.690] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.693] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.706] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.708] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.719] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.722] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.870] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.932] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.934] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.936] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.938] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.939] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.939] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:08.940] [INFO] (ui: browser) - Cannot retrieve ENS addresses unless fully synced on main chain
[2019-01-28T19:53:11.907] [INFO] (ui: browser) - Restart app operation again
[2019-01-28T19:53:11.908] [INFO] (ui: browser) - Connect to node...
[2019-01-28T19:53:12.345] [INFO] (ui: browser) - Connect to node...
[2019-01-28T19:53:16.469] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xe41d2489571d322189246dafa5ebde1f4699f498 (_id: token_e41d248957) from block #',
  '1': 7141967 }
[2019-01-28T19:53:16.488] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x960b236a07cf122663c4303350609a66a7b288c0 (_id: token_960b236a07) from block #',
  '1': 7141967 }
[2019-01-28T19:53:16.502] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb8c77482e45f1f44de1745f52c74426c631bdd52 (_id: token_b8c77482e4) from block #',
  '1': 7141967 }
[2019-01-28T19:53:16.530] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x0d8775f648430679a709e98d2b0cb6250d2887ef (_id: token_0d8775f648) from block #',
  '1': 7141967 }
[2019-01-28T19:53:16.547] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0 (_id: token_86fa049857) from block #',
  '1': 0 }
[2019-01-28T19:53:17.105] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xaf30d2a7e90d7dc361c8c4585e9bb7d2f6f15bc7 (_id: token_af30d2a7e9) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.173] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x6810e776880c02933d47db1b9fc05908e5386b96 (_id: token_6810e77688) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.190] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xa74476443119a942de498590fe1f2454d7d4ac0d (_id: token_a744764431) from block #',
  '1': 7141109 }
[2019-01-28T19:53:17.207] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x888666ca69e0f178ded6d75b5726cee99a87d698 (_id: token_888666ca69) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.220] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xf433089366899d83a9f26a773d59ec7ecf30355e (_id: token_f433089366) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.243] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb63b606ac810a52cca15e44bb630fd42d8d1d83d (_id: token_b63b606ac8) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.259] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xcfb98637bcae43c13323eaa1731ced2b716962fd (_id: token_cfb98637bc) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.279] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xd26114cd6ee289accf82350c8d8487fedb8a0c07 (_id: token_d26114cd6e) from block #',
  '1': 7141133 }
[2019-01-28T19:53:17.298] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xe94327d07fc17907b4db788e5adf2ed424addff6 (_id: token_e94327d07f) from block #',
  '1': 0 }
[2019-01-28T19:53:17.310] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xaec2e87e0a235266d9c5adc9deb4b2e29b54d009 (_id: token_aec2e87e0a) from block #',
  '1': 7141085 }
[2019-01-28T19:53:17.330] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x744d70fdbe2ba4cf95131626614a1763df805b9e (_id: token_744d70fdbe) from block #',
  '1': 7141146 }
[2019-01-28T19:53:17.339] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac (_id: token_b64ef51c88) from block #',
  '1': 7141114 }
[2019-01-28T19:53:17.366] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb97048628db6b661d4c2aa833e95dbe1a905b280 (_id: token_b97048628d) from block #',
  '1': 7141137 }
[2019-01-28T19:53:17.376] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb7cb1c96db6b22b0d3d9536e0108d062bd488f74 (_id: token_b7cb1c96db) from block #',
  '1': 7141122 }
[2019-01-28T19:53:17.417] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x0abdace70d3790235af448c88547603b945604ea (_id: token_0abdace70d) from block #',
  '1': 7141112 }
[2019-01-28T19:53:17.445] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x0e0989b1f9b8a38983c2ba8053269ca62ec9b195 (_id: token_0e0989b1f9) from block #',
  '1': 7141141 }
[2019-01-28T19:53:17.460] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x58b6a8a3302369daec383334672404ee733ab239 (_id: token_58b6a8a330) from block #',
  '1': 7141134 }
[2019-01-28T19:53:17.472] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x17e67d1cb4e349b9ca4bc3e17c7df2a397a7bb64 (_id: token_17e67d1cb4) from block #',
  '1': 7141078 }
[2019-01-28T19:53:17.488] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x4dc3643dbc642b72c158e7f3d2ff232df61cb6ce (_id: token_4dc3643dbc) from block #',
  '1': 0 }
[2019-01-28T19:53:17.499] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xab95e915c123fded5bdfb6325e35ef5515f1ea69 (_id: token_ab95e915c1) from block #',
  '1': 0 }
[2019-01-28T19:53:19.183] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xe41d2489571d322189246dafa5ebde1f4699f498 (_id: token_e41d248957) from block #',
  '1': 7141967 }
[2019-01-28T19:53:19.219] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x960b236a07cf122663c4303350609a66a7b288c0 (_id: token_960b236a07) from block #',
  '1': 7141967 }
[2019-01-28T19:53:19.233] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb8c77482e45f1f44de1745f52c74426c631bdd52 (_id: token_b8c77482e4) from block #',
  '1': 7141967 }
[2019-01-28T19:53:19.255] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x0d8775f648430679a709e98d2b0cb6250d2887ef (_id: token_0d8775f648) from block #',
  '1': 7141967 }
[2019-01-28T19:53:19.274] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0 (_id: token_86fa049857) from block #',
  '1': 0 }
[2019-01-28T19:53:19.288] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xaf30d2a7e90d7dc361c8c4585e9bb7d2f6f15bc7 (_id: token_af30d2a7e9) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.301] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x6810e776880c02933d47db1b9fc05908e5386b96 (_id: token_6810e77688) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.313] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xa74476443119a942de498590fe1f2454d7d4ac0d (_id: token_a744764431) from block #',
  '1': 7141109 }
[2019-01-28T19:53:19.327] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x888666ca69e0f178ded6d75b5726cee99a87d698 (_id: token_888666ca69) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.388] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xf433089366899d83a9f26a773d59ec7ecf30355e (_id: token_f433089366) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.413] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb63b606ac810a52cca15e44bb630fd42d8d1d83d (_id: token_b63b606ac8) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.432] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xcfb98637bcae43c13323eaa1731ced2b716962fd (_id: token_cfb98637bc) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.469] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xd26114cd6ee289accf82350c8d8487fedb8a0c07 (_id: token_d26114cd6e) from block #',
  '1': 7141133 }
[2019-01-28T19:53:19.486] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xe94327d07fc17907b4db788e5adf2ed424addff6 (_id: token_e94327d07f) from block #',
  '1': 0 }
[2019-01-28T19:53:19.500] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xaec2e87e0a235266d9c5adc9deb4b2e29b54d009 (_id: token_aec2e87e0a) from block #',
  '1': 7141085 }
[2019-01-28T19:53:19.519] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x744d70fdbe2ba4cf95131626614a1763df805b9e (_id: token_744d70fdbe) from block #',
  '1': 7141146 }
[2019-01-28T19:53:19.531] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac (_id: token_b64ef51c88) from block #',
  '1': 7141114 }
[2019-01-28T19:53:19.543] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb97048628db6b661d4c2aa833e95dbe1a905b280 (_id: token_b97048628d) from block #',
  '1': 7141137 }
[2019-01-28T19:53:19.563] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xb7cb1c96db6b22b0d3d9536e0108d062bd488f74 (_id: token_b7cb1c96db) from block #',
  '1': 7141122 }
[2019-01-28T19:53:19.595] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x0abdace70d3790235af448c88547603b945604ea (_id: token_0abdace70d) from block #',
  '1': 7141112 }
[2019-01-28T19:53:19.636] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x0e0989b1f9b8a38983c2ba8053269ca62ec9b195 (_id: token_0e0989b1f9) from block #',
  '1': 7141141 }
[2019-01-28T19:53:19.647] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x58b6a8a3302369daec383334672404ee733ab239 (_id: token_58b6a8a330) from block #',
  '1': 7141134 }
[2019-01-28T19:53:19.668] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x17e67d1cb4e349b9ca4bc3e17c7df2a397a7bb64 (_id: token_17e67d1cb4) from block #',
  '1': 7141078 }
[2019-01-28T19:53:19.683] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0x4dc3643dbc642b72c158e7f3d2ff232df61cb6ce (_id: token_4dc3643dbc) from block #',
  '1': 0 }
[2019-01-28T19:53:19.692] [WARN] EthereumNodeRemote - Error from ws:  { RangeError: Invalid WebSocket frame: invalid status code 1006
    at Receiver.controlMessage (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\receiver.js:441:18)
    at Receiver.getData (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\receiver.js:329:42)
    at Receiver.startLoop (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\receiver.js:133:22)
    at Receiver._write (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\receiver.js:69:10)
    at doWrite (_stream_writable.js:371:12)
    at clearBuffer (_stream_writable.js:497:7)
    at onwrite (_stream_writable.js:423:7)
    at Receiver.startLoop (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\receiver.js:141:5)
    at perMessageDeflate.decompress (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\receiver.js:374:12)
    at _decompress (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\permessage-deflate.js:307:9)
    at _inflate.flush (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ws\lib\permessage-deflate.js:389:7)
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7)
    at InflateRaw.afterTransform (_stream_transform.js:90:3)
    at Zlib.callback (zlib.js:488:5) [Symbol(status-code)]: 1002 }
[2019-01-28T19:53:19.696] [WARN] EthereumNodeRemote - Remote WebSocket connection closed (code: 1002). Reopening connection...
[2019-01-28T19:53:19.700] [INFO] (ui: browser) - EVENT LOG:  { '0': 'Checking Token Transfers for 0xab95e915c123fded5bdfb6325e35ef5515f1ea69 (_id: token_ab95e915c1) from block #',
  '1': 0 }
[2019-01-28T19:53:19.701] [WARN] EthereumNodeRemote - Remote websocket connection not open, attempting to reconnect and retry eth_getLogs...
[2019-01-28T19:53:19.702] [WARN] EthereumNodeRemote - Remote websocket connection not open, attempting to reconnect and retry eth_getLogs...
[2019-01-28T19:53:19.703] [WARN] EthereumNodeRemote - Remote websocket connection not open, attempting to reconnect and retry eth_subscribe...
[2019-01-28T19:53:30.262] [WARN] EthereumNodeRemote - Remote WebSocket connection closed (code: 1006). Reopening connection...
[2019-01-28T19:53:30.581] [WARN] EthereumNodeRemote - Remote websocket connection not open, attempting to reconnect and retry net_peerCount...

What am I doing wrong? Why can't mist communicate with my local geth node?

**Comment by b-f-** [comment]
Same problem with 1.8.23, win x64 build. Mist asks for geth update from 1.8.18 to 1.8.21, after that it hangs.
[all.log](https://github.com/ethereum/mist/files/2885981/all.log)

**Comment by kbs1** [comment]
I am also getting `RangeError: Invalid WebSocket frame: invalid status code 1006` and the wallet never updates. This happens with IPC rpc. With http rpc it says "notifications not supported" see #4024 

So there is no way to run mist on ubuntu 18.04 right now (using latest ZIP)

**Comment by satori-q3a** [comment]
Currently I'm running geth 1.8.27 with fast sync that's fully sync'd to the network, however Mist 11.1 is erratic with it's reporting on my account information, and fails to give updated data on the accounts. The system is a Window 10, April-2019 update to 1809.

I transferred some eth to my local system's account, Mist 11.1 did not showed nothing received. After I used Mist 10.0 to verify that the transaction did indeed complete, only then did Mist 11.1 show the eth was received.

I used Mist 11.1 to transfer some eth to another of my local accounts, Mist showed the transfer in progess and did not show a completion.  Mist 10.0 showed that the transfers took place and the accounts were correct. Mist 11.1 still shows the transfer is pending and the reported accounts were using old data.

Mist 10.0 and Etherwall 2.3.2 both connect correctly to geth 1.8.27 and reports the current information on the interactions of the eth accounts and for the geth blocks.  Mist 11.1 does not show the updated data and always shows a waiting for geth block, altho it also says it's connect to a remote geth.

It appears that the only way to get updated transactions and accounts info is to restart Mist 11.1 after you perform a transaction.
