### ISSUE TITLE
problem installing tailwindcss 

### ISSUE THREAD

**Issue by AdamWarlock08** [ethereum/mist#4230]
when i try to build my css i receive this error.

question Which command would you like to run?: build:css
$ postcss src/index.css -0 src/tailwind.css
TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (C:\Users\steve\minproj3\node_modules\globby\index.js:16:9)
    at generateGlobTasks (C:\Users\steve\minproj3\node_modules\globby\index.js:41:2)
    at module.exports (C:\Users\steve\minproj3\node_modules\globby\index.js:115:20)
    at C:\Users\steve\minproj3\node_modules\postcss-cli\index.js:59:14
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore
