### ISSUE TITLE
Mist stays in `connecting` state

### ISSUE THREAD

**Issue by maciejso** [ethereum/mist#4233]
Have downloaded Mist. Installed successfully but can't run it on neither on my three Linux boxes.
Can anybody help me with that?

Latest Mist for Debian
Mist-linux64-0-11-1.deb

[2020-07-15T18:59:37.077] [INFO] Settings - Running in production mode: true
[2020-07-15T18:59:37.156] [INFO] EthereumNode - undefined null 'light'
[2020-07-15T18:59:37.159] [INFO] EthereumNode - Defaults loaded: geth main light
[2020-07-15T18:59:37.239] [INFO] main - Starting in Mist mode
[2020-07-15T18:59:37.362] [INFO] Db - Creating db: /home/maciej/.config/Mist/mist.lokidb
[2020-07-15T18:59:37.378] [INFO] Db - Loading db: /home/maciej/.config/Mist/mist.lokidb
[2020-07-15T18:59:37.387] [INFO] Windows - Creating commonly-used windows
[2020-07-15T18:59:37.389] [INFO] Windows - Create secondary window: loading, owner: notset
[2020-07-15T18:59:37.460] [INFO] updateChecker - Check for update...
[2020-07-15T18:59:41.728] [INFO] Sockets/node-ipc - Connect to {"path":"/home/maciej/.ethereum/geth.ipc"}
[2020-07-15T18:59:41.776] [INFO] Windows - Create primary window: main, owner: notset
[2020-07-15T18:59:41.813] [INFO] ClientBinaryManager - Initializing...
[2020-07-15T18:59:41.814] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2020-07-15T18:59:41.842] [INFO] main - Loading Interface at file:///opt/Mist/resources/app.asar/interface/index.html
[2020-07-15T18:59:41.974] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2020-07-15T18:59:42.267] [WARN] ClientBinaryManager - Error loading local config - assuming this is a first run: Error: ENOENT: no such file or directory, open '/home/maciej/.config/Mist/clientBinaries.json'
[2020-07-15T18:59:42.268] [INFO] ClientBinaryManager - Write new client binaries local config to disk ...
[2020-07-15T18:59:42.271] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2020-07-15T18:59:42.279] [INFO] ClientBinaryManager - Initializing...
[2020-07-15T18:59:42.280] [INFO] ClientBinaryManager - Resolving platform...
[2020-07-15T18:59:42.282] [INFO] ClientBinaryManager - Calculating possible clients...
[2020-07-15T18:59:42.285] [INFO] ClientBinaryManager - 1 possible clients.
[2020-07-15T18:59:42.301] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2020-07-15T18:59:42.303] [INFO] ClientBinaryManager - Verify Geth status ...
[2020-07-15T18:59:42.319] [ERROR] ClientBinaryManager - Unable to resolve Geth executable: geth
[2020-07-15T18:59:42.342] [INFO] ClientBinaryManager - Download binary for Geth ...
[2020-07-15T18:59:42.346] [INFO] ClientBinaryManager - Downloading package from https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.23-c9427004.tar.gz to /home/maciej/.config/Mist/binaries/Geth/archive.tar ...
[2020-07-15T18:59:42.360] [INFO] updateChecker - App is up-to-date.
[2020-07-15T18:59:42.443] [WARN] EthereumNodeRemote - Error from ws:  Error: Unexpected server response: 403
    at ClientRequest.req.on (/opt/Mist/resources/app.asar/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
[2020-07-15T18:59:42.455] [WARN] EthereumNodeRemote - Remote WebSocket connection closed (code: 1006). Reopening connection...
[2020-07-15T18:59:42.975] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2020-07-15T18:59:43.977] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2020-07-15T18:59:44.969] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2020-07-15T18:59:44.976] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2020-07-15T18:59:44.977] [INFO] EthereumNode - Node type: geth
[2020-07-15T18:59:44.978] [INFO] EthereumNode - Network: main
[2020-07-15T18:59:44.978] [INFO] EthereumNode - SyncMode: light
[2020-07-15T18:59:44.979] [INFO] EthereumNode - Start node: geth main light
[2020-07-15T18:59:45.001] [ERROR] EthereumNode - Failed to start node Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (/opt/Mist/resources/app.asar/modules/ethereumNode.js:374:13)
    at stop.then (/opt/Mist/resources/app.asar/modules/ethereumNode.js:300:19)
    at tryCatcher (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Mist/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[2020-07-15T18:59:47.303] [INFO] (ui: popupWindow) - Meteor starting up...
[2020-07-15T18:59:48.723] [INFO] (ui: mist) - Meteor starting up...
[2020-07-15T18:59:48.732] [INFO] (ui: mist) - Initialize Mist Interface
[2020-07-15T18:59:48.741] [INFO] (ui: popupWindow) - Meteor starting up...
[2020-07-15T18:59:50.392] [INFO] ClientBinaryManager - Verify Geth status ...
[2020-07-15T18:59:50.405] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2020-07-15T18:59:50.406] [INFO] ClientBinaryManager - Checking sanity for Geth ...

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore
