### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#453]
Node type: geth 1.3.5
OS: linux, archlinux, kernel 4.4.5
Network type: main
Mist version: 0.5.2

     ~ $ mist
    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: ENOENT, interface/project-tap.i18n not found in /usr/share/mist/resources/app.asar
        at notFoundError (ATOM_SHELL_ASAR.js:108:13)
        at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:433:9)
        at Object.<anonymous> (/usr/share/mist/resources/app.asar/modules/i18n.js:8:19)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/usr/share/mist/resources/app.asar/main.js:12:14)

`~/.config/Mist/node.log` is empty (0 Bytes).

**Comment by frozeman** [comment]
it seems like you bundled it wrongly. in the build process it seems like the tapi18n was not copied correctly.

What did you do?

**Comment by 5chdn** [comment]
Installed this via `PKGBUILD` from the arch user repository.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mist-git

**Comment by luclu** [comment]
@5chdn are you still encountering this issue?
Just tested this and it works fine for me!
I also dropped some line on the PKG's comments. :)

**Comment by 5chdn** [comment]
nope, can not reproduce anymore.

thanks for the commet. will update the PKGBUILD.

**Comment by luclu** [comment]
sweet
