### ISSUE TITLE
Error with MKR token after upgrading to Mist 7.1

### ISSUE THREAD

**Issue by bamos01** [ethereum/mist#508]
Node type: geth
OS: osx
Network type: main
Mist version: 7.1

This is for the maker dao token- it seemed to be working normally before in earlier versions of mist.  The other tokens and sync are working normally.

Getting this error on console
6ea29fb….js:295 Logs of Token MKR couldn't be received Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.module.exports.InvalidConnection (/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/errors.js:28:16)
    at IpcProvider._timeout (/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:150:48)
    at /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:38:15
    at EventEmitter.<anonymous> (/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/ipc/ipcProviderWrapper.js:51:13)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)(anonymous function) @ 6ea29fb….js:295(anonymous function) @ 6ea29fb….js:179(anonymous function) @ 6ea29fb….js:180(anonymous function) @ 6ea29fb….js:180(anonymous function) @ 6ea29fb….js:180IpcProvider._timeout @ /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovide…:150(anonymous function) @ /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovide…:38(anonymous function) @ /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/ipc/ipcProviderWrapper.js:51emitTwo @ events.js:87emit @ events.js:172

**Comment by luclu** [comment]
Can you please provide the token address for debugging?

**Comment by frozeman** [comment]
Please try to restart. It looks more like your node crashed or something, as it lost the IPC connection.

**Comment by bamos01** [comment]
There is definitely a problem with the Maker DAO token in Mist.  I believe it is related to the token using 18 decimal places- I am getting the following BigNumber error.  I tried this in Mist 7.2 and still am getting same error.  I didn't have this problem in the earlier versions of Mist with this token even with the 18 decimal places. 

085e9d7….js:182 Uncaught BigNumber Error: new BigNumber() not a base 16 number: P @ 085e9d7….js:182(anonymous function) @ 085e9d7….js:183e @ 085e9d7….js:182w @ 085e9d7….js:179(anonymous function) @ 085e9d7….js:179i.decode @ 085e9d7….js:179(anonymous function) @ 085e9d7….js:179h.decodeParams @ 085e9d7….js:179s.unpackOutput @ 085e9d7….js:180(anonymous function) @ 085e9d7….js:180(anonymous function) @ 085e9d7….js:180(anonymous function) @ 085e9d7….js:180(anonymous function) @ /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovide…:66(anonymous function) @ /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovide…:50(anonymous function) @ /Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/ipc/ipcProviderWrapper.js:51emitTwo @ events.js:87emit @ events.js:172

**Comment by frozeman** [comment]
It looks like a decoding issue with web3.js events. So the event fires some type of event variable, which web3.js might not support right now, or there is a web3.js issue with what is returned.

So this is better to be analysed and posted to the web3.js repo

**Comment by bamos01** [comment]
Ok - but I do want to point out that this error does happen with Mist
version 6. Does this make sense to you?

**Comment by bamos01** [comment]
Edit - I meant that this error does NOT happen with Mist v 6.

**Comment by bamos01** [comment]
seems to be working now for me
