### ISSUE TITLE
mist synchronizes and then crashes after splash screen 

### ISSUE THREAD

**Issue by lunokhod** [ethereum/mist#544]
After starting mist on OSX, the splash screen appears, and then successfully synchonizes. After synchronization, the splash screen disappears, a new window briefly appears, but then mist crashes with the error "Electron unexpectedly quit". The node.log file does not contain any information about the crash (the last line states the number of blocks that were imported).

I have ensured that meteor and all its components are up-to-date, and I am using the latest commit at github c1bec3ca05d3be9c26fb547f1108d80cad3cecda

**Comment by hiddentao** [comment]
I think I have this fixed, but it's not yet merged in. Would you be willing to try the following commit? https://github.com/hiddentao/mist/commit/e43d568e6fa5c7ede59a7c0bc9d1f35d28526f2f

**Comment by hiddentao** [comment]
Also, if you do try that version out please run it from the command-line with:

```bash
$ electron . --reset-tabs --loglevel trace
```

**Comment by lunokhod** [comment]
Sorry, but the same thing happened. Here is the entire screen output. Do you need anything else?

~~~~
% electron . --reset-tabs --loglevel trace
[2016-05-04 13:03:53.541] [DEBUG] getIpcPath - CONNECT to IPC PATH: /Users/lunokhod/Library/Ethereum/geth.ipc
[2016-05-04 13:03:53.582] [INFO] main - Starting in Mist mode
[2016-05-04 13:03:53.850] [DEBUG] getIpcPath - CONNECT to IPC PATH: /Users/lunokhod/Library/Ethereum/geth.ipc
[2016-05-04 13:03:54.433] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/lunokhod/Library/Ethereum/geth.ipc' }
Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2016-05-04 13:03:54.961] [INFO] ipcCommunicator - Backend language set to:  en
[2016-05-04 13:03:54.985] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/lunokhod/Library/Ethereum/geth.ipc' }
Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2016-05-04 13:03:56.413] [DEBUG] main - Geth connection REFUSED 0
[2016-05-04 13:03:56.415] [INFO] main - Node type:  geth
[2016-05-04 13:03:56.415] [INFO] main - Network:  main
[2016-05-04 13:03:56.417] [DEBUG] getNodePath - Resolved path for geth: /Users/lunokhod/Desktop/mist/nodes/geth/darwin-x64/geth
[2016-05-04 13:03:56.417] [INFO] ethereumNodes - Start node from /Users/lunokhod/Desktop/mist/nodes/geth/darwin-x64/geth
[2016-05-04 13:03:56.423] [INFO] ethereumNodes - Stopping nodes...
[2016-05-04 13:03:56.423] [INFO] ethereumNodes - Starting geth node...
[2016-05-04 13:03:57.379] [DEBUG] ethereumNodes - Saved standard node "geth" to file: /Users/lunokhod/Library/Application Support/Mist/node
[2016-05-04 13:03:57.380] [DEBUG] ethereumNodes - Saved network type "main" to file: /Users/lunokhod/Library/Application Support/Mist/network
[2016-05-04 13:03:57.421] [TRACE] main - NODE LOG: I0504 13:03:57.420547   60803 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)
[2016-05-04 13:03:57.421] [TRACE] main - "I0504 13:03:57.420547   60803 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)"
[2016-05-04 13:03:57.582] [INFO] main - Geth connection FOUND
[2016-05-04 13:03:57.606] [INFO] checkNodeSync - Checking node sync status...
[2016-05-04 13:03:57.632] [DEBUG] checkNodeSync - Time between last block 150021s
[2016-05-04 13:05:17.381] [TRACE] main - NODE LOG: I0504 13:05:17.380472   60803 downloader.go:288] Block synchronisation started
[2016-05-04 13:05:17.381] [TRACE] main - "I0504 13:05:17.380472   60803 downloader.go:288] Block synchronisation started"
[2016-05-04 13:05:49.911] [TRACE] main - NODE LOG: I0504 13:05:49.911484   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1442 txs in 9.572464068s. #1444977 [98f2b7a5 / 07e5e674]
[2016-05-04 13:05:49.912] [TRACE] main - "I0504 13:05:49.911484   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1442 txs in 9.572464068s. #1444977 [98f2b7a5 / 07e5e674]"
[2016-05-04 13:05:52.420] [TRACE] main - NODE LOG: I0504 13:05:52.419957   60803 blockchain.go:1251] imported 152 block(s) (0 queued 0 ignored) including 526 txs in 2.507687497s. #1445129 [b0f89d4c / 5100391e]
[2016-05-04 13:05:52.420] [TRACE] main - "I0504 13:05:52.419957   60803 blockchain.go:1251] imported 152 block(s) (0 queued 0 ignored) including 526 txs in 2.507687497s. #1445129 [b0f89d4c / 5100391e]"
[2016-05-04 13:06:00.702] [TRACE] main - NODE LOG: I0504 13:06:00.702534   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1763 txs in 8.268391847s. #1445385 [28df896e / edc65283]
[2016-05-04 13:06:00.703] [TRACE] main - "I0504 13:06:00.702534   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1763 txs in 8.268391847s. #1445385 [28df896e / edc65283]"
[2016-05-04 13:06:12.623] [TRACE] main - NODE LOG: I0504 13:06:12.622941   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2112 txs in 11.918393522s. #1445641 [341e8ddf / 6077a3df]
[2016-05-04 13:06:12.623] [TRACE] main - "I0504 13:06:12.622941   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2112 txs in 11.918393522s. #1445641 [341e8ddf / 6077a3df]"
[2016-05-04 13:06:18.943] [TRACE] main - NODE LOG: I0504 13:06:18.943215   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1724 txs in 6.31876716s. #1445897 [bb87a891 / 40cf9fc8]
[2016-05-04 13:06:18.943] [TRACE] main - "I0504 13:06:18.943215   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1724 txs in 6.31876716s. #1445897 [bb87a891 / 40cf9fc8]"
[2016-05-04 13:06:22.678] [TRACE] main - NODE LOG: I0504 13:06:22.677784   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 916 txs in 3.733281811s. #1446153 [e498cae1 / 59098b39]
[2016-05-04 13:06:22.678] [TRACE] main - "I0504 13:06:22.677784   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 916 txs in 3.733281811s. #1446153 [e498cae1 / 59098b39]"
[2016-05-04 13:06:43.064] [TRACE] main - NODE LOG: I0504 13:06:43.064595   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 3043 txs in 20.372837582s. #1446409 [48d6a7e8 / 69c1dedc]
[2016-05-04 13:06:43.065] [TRACE] main - "I0504 13:06:43.064595   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 3043 txs in 20.372837582s. #1446409 [48d6a7e8 / 69c1dedc]"
[2016-05-04 13:06:51.497] [TRACE] main - NODE LOG: I0504 13:06:51.497142   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1589 txs in 8.431250781s. #1446665 [1198c687 / 058e44a0]
[2016-05-04 13:06:51.497] [TRACE] main - "I0504 13:06:51.497142   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1589 txs in 8.431250781s. #1446665 [1198c687 / 058e44a0]"
[2016-05-04 13:06:56.457] [TRACE] main - NODE LOG: I0504 13:06:56.457605   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1494 txs in 4.958910614s. #1446921 [0073fa7a / dfe5455a]
[2016-05-04 13:06:56.458] [TRACE] main - "I0504 13:06:56.457605   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1494 txs in 4.958910614s. #1446921 [0073fa7a / dfe5455a]"
[2016-05-04 13:07:07.202] [TRACE] main - NODE LOG: I0504 13:07:07.201968   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2160 txs in 10.743019477s. #1447177 [56d648b8 / 20bc9936]
[2016-05-04 13:07:07.202] [TRACE] main - "I0504 13:07:07.201968   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2160 txs in 10.743019477s. #1447177 [56d648b8 / 20bc9936]"
[2016-05-04 13:07:11.255] [TRACE] main - NODE LOG: I0504 13:07:11.254890   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1076 txs in 4.032456922s. #1447433 [02a0a6fe / f40df4ac]
[2016-05-04 13:07:11.255] [TRACE] main - "I0504 13:07:11.254890   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1076 txs in 4.032456922s. #1447433 [02a0a6fe / f40df4ac]"
[2016-05-04 13:07:40.652] [TRACE] main - NODE LOG: I0504 13:07:40.651760   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 4395 txs in 29.39547302s. #1447689 [9e511a26 / 6855fad8]
[2016-05-04 13:07:40.652] [TRACE] main - "I0504 13:07:40.651760   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 4395 txs in 29.39547302s. #1447689 [9e511a26 / 6855fad8]"
[2016-05-04 13:07:46.178] [TRACE] main - NODE LOG: I0504 13:07:46.178557   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1626 txs in 5.525393539s. #1447945 [c66e6fdd / a5150299]
[2016-05-04 13:07:46.179] [TRACE] main - "I0504 13:07:46.178557   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1626 txs in 5.525393539s. #1447945 [c66e6fdd / a5150299]"
[2016-05-04 13:07:51.823] [TRACE] main - NODE LOG: I0504 13:07:51.823495   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1270 txs in 5.643618965s. #1448201 [968985e3 / d6101c5a]
[2016-05-04 13:07:51.824] [TRACE] main - "I0504 13:07:51.823495   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1270 txs in 5.643618965s. #1448201 [968985e3 / d6101c5a]"
[2016-05-04 13:08:04.452] [TRACE] main - NODE LOG: I0504 13:08:04.452232   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2218 txs in 12.614900316s. #1448457 [0fed48d8 / c0bc7792]
[2016-05-04 13:08:04.452] [TRACE] main - "I0504 13:08:04.452232   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2218 txs in 12.614900316s. #1448457 [0fed48d8 / c0bc7792]"
[2016-05-04 13:08:08.511] [TRACE] main - NODE LOG: I0504 13:08:08.511177   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1094 txs in 4.05764606s. #1448713 [75f49bcc / 845a135e]
[2016-05-04 13:08:08.511] [TRACE] main - "I0504 13:08:08.511177   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1094 txs in 4.05764606s. #1448713 [75f49bcc / 845a135e]"
[2016-05-04 13:08:12.170] [TRACE] main - NODE LOG: I0504 13:08:12.169975   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1005 txs in 3.657447973s. #1448969 [0d6195d9 / fe0fa446]
[2016-05-04 13:08:12.170] [TRACE] main - "I0504 13:08:12.169975   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1005 txs in 3.657447973s. #1448969 [0d6195d9 / fe0fa446]"
[2016-05-04 13:08:16.946] [TRACE] main - NODE LOG: I0504 13:08:16.946273   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1218 txs in 4.775042023s. #1449225 [74943693 / b48b39a9]
[2016-05-04 13:08:16.946] [TRACE] main - "I0504 13:08:16.946273   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1218 txs in 4.775042023s. #1449225 [74943693 / b48b39a9]"
[2016-05-04 13:08:21.368] [TRACE] main - NODE LOG: I0504 13:08:21.367957   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1298 txs in 4.407758312s. #1449481 [f890d7fe / a2b7ddd4]
[2016-05-04 13:08:21.368] [TRACE] main - "I0504 13:08:21.367957   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1298 txs in 4.407758312s. #1449481 [f890d7fe / a2b7ddd4]"
[2016-05-04 13:08:25.941] [TRACE] main - NODE LOG: I0504 13:08:25.941242   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1064 txs in 4.571922634s. #1449737 [8518082a / b30b8fa5]
[2016-05-04 13:08:25.941] [TRACE] main - "I0504 13:08:25.941242   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1064 txs in 4.571922634s. #1449737 [8518082a / b30b8fa5]"
[2016-05-04 13:08:37.741] [TRACE] main - NODE LOG: I0504 13:08:37.741337   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2214 txs in 11.798605605s. #1449993 [845b693a / 005a68a0]
[2016-05-04 13:08:37.741] [TRACE] main - "I0504 13:08:37.741337   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2214 txs in 11.798605605s. #1449993 [845b693a / 005a68a0]"
[2016-05-04 13:08:44.835] [TRACE] main - NODE LOG: I0504 13:08:44.835415   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2010 txs in 7.092506839s. #1450249 [f5967a4d / ef92d795]
[2016-05-04 13:08:44.835] [TRACE] main - "I0504 13:08:44.835415   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2010 txs in 7.092506839s. #1450249 [f5967a4d / ef92d795]"
[2016-05-04 13:08:50.356] [TRACE] main - NODE LOG: I0504 13:08:50.356473   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1376 txs in 5.504997387s. #1450505 [3d11116f / 4ea4d250]
[2016-05-04 13:08:50.357] [TRACE] main - "I0504 13:08:50.356473   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1376 txs in 5.504997387s. #1450505 [3d11116f / 4ea4d250]"
[2016-05-04 13:08:54.919] [TRACE] main - NODE LOG: I0504 13:08:54.919692   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1243 txs in 4.561870431s. #1450761 [f613226c / f13c13f3]
[2016-05-04 13:08:54.920] [TRACE] main - "I0504 13:08:54.919692   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1243 txs in 4.561870431s. #1450761 [f613226c / f13c13f3]"
[2016-05-04 13:08:59.090] [TRACE] main - NODE LOG: I0504 13:08:59.090122   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1224 txs in 4.16902324s. #1451017 [7e887887 / 8dd86aa5]
[2016-05-04 13:08:59.090] [TRACE] main - "I0504 13:08:59.090122   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1224 txs in 4.16902324s. #1451017 [7e887887 / 8dd86aa5]"
[2016-05-04 13:09:04.028] [TRACE] main - NODE LOG: I0504 13:09:04.027880   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1306 txs in 4.936148347s. #1451273 [f186c311 / b7567f60]
[2016-05-04 13:09:04.028] [TRACE] main - "I0504 13:09:04.027880   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1306 txs in 4.936148347s. #1451273 [f186c311 / b7567f60]"
[2016-05-04 13:09:17.797] [TRACE] main - NODE LOG: I0504 13:09:17.797269   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2449 txs in 13.75548046s. #1451529 [ca488941 / 1b0d7f28]
[2016-05-04 13:09:17.797] [TRACE] main - "I0504 13:09:17.797269   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2449 txs in 13.75548046s. #1451529 [ca488941 / 1b0d7f28]"
[2016-05-04 13:09:24.573] [TRACE] main - NODE LOG: I0504 13:09:24.573396   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1574 txs in 6.773725959s. #1451785 [cb8b07bd / 78a39756]
[2016-05-04 13:09:24.573] [TRACE] main - "I0504 13:09:24.573396   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1574 txs in 6.773725959s. #1451785 [cb8b07bd / 78a39756]"
[2016-05-04 13:09:28.486] [TRACE] main - NODE LOG: I0504 13:09:28.486703   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 954 txs in 3.912038087s. #1452041 [979f3bf8 / 7317ff42]
[2016-05-04 13:09:28.487] [TRACE] main - "I0504 13:09:28.486703   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 954 txs in 3.912038087s. #1452041 [979f3bf8 / 7317ff42]"
[2016-05-04 13:09:32.618] [TRACE] main - NODE LOG: I0504 13:09:32.617881   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1048 txs in 4.12985948s. #1452297 [abb66c92 / b80c2345]
[2016-05-04 13:09:32.618] [TRACE] main - "I0504 13:09:32.617881   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1048 txs in 4.12985948s. #1452297 [abb66c92 / b80c2345]"
[2016-05-04 13:09:38.156] [TRACE] main - NODE LOG: I0504 13:09:38.156268   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1338 txs in 5.524583995s. #1452553 [07e6faec / 25c4d940]
[2016-05-04 13:09:38.156] [TRACE] main - "I0504 13:09:38.156268   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1338 txs in 5.524583995s. #1452553 [07e6faec / 25c4d940]"
[2016-05-04 13:09:42.769] [TRACE] main - NODE LOG: I0504 13:09:42.769492   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1198 txs in 4.611855335s. #1452809 [92220788 / 0367f8fc]
[2016-05-04 13:09:42.770] [TRACE] main - "I0504 13:09:42.769492   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1198 txs in 4.611855335s. #1452809 [92220788 / 0367f8fc]"
[2016-05-04 13:09:55.634] [TRACE] main - NODE LOG: I0504 13:09:55.633996   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2402 txs in 12.862994641s. #1453065 [6fb00271 / d55b7fb3]
[2016-05-04 13:09:55.634] [TRACE] main - "I0504 13:09:55.633996   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2402 txs in 12.862994641s. #1453065 [6fb00271 / d55b7fb3]"
[2016-05-04 13:10:10.334] [TRACE] main - NODE LOG: I0504 13:10:10.334160   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1665 txs in 14.698874606s. #1453321 [3c83bc10 / 186394a5]
[2016-05-04 13:10:10.334] [TRACE] main - "I0504 13:10:10.334160   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1665 txs in 14.698874606s. #1453321 [3c83bc10 / 186394a5]"
[2016-05-04 13:10:20.836] [TRACE] main - NODE LOG: I0504 13:10:20.836596   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1711 txs in 10.488378359s. #1453577 [e888b846 / 617f726d]
[2016-05-04 13:10:20.837] [TRACE] main - "I0504 13:10:20.836596   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1711 txs in 10.488378359s. #1453577 [e888b846 / 617f726d]"
[2016-05-04 13:10:25.716] [TRACE] main - NODE LOG: I0504 13:10:25.715721   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1393 txs in 4.877786365s. #1453833 [47a3e725 / 7370b2bf]
[2016-05-04 13:10:25.716] [TRACE] main - "I0504 13:10:25.715721   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1393 txs in 4.877786365s. #1453833 [47a3e725 / 7370b2bf]"
[2016-05-04 13:10:30.310] [TRACE] main - NODE LOG: I0504 13:10:30.310479   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1002 txs in 4.593386401s. #1454089 [7a90b82e / 2c2cd763]
[2016-05-04 13:10:30.311] [TRACE] main - "I0504 13:10:30.310479   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1002 txs in 4.593386401s. #1454089 [7a90b82e / 2c2cd763]"
[2016-05-04 13:10:36.806] [TRACE] main - NODE LOG: I0504 13:10:36.805869   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1515 txs in 6.494114723s. #1454345 [02491294 / 408ac616]
[2016-05-04 13:10:36.806] [TRACE] main - "I0504 13:10:36.805869   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1515 txs in 6.494114723s. #1454345 [02491294 / 408ac616]"
[2016-05-04 13:10:48.856] [TRACE] main - NODE LOG: I0504 13:10:48.856409   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2166 txs in 12.038663527s. #1454601 [8873bddc / b99dfe60]
[2016-05-04 13:10:48.856] [TRACE] main - "I0504 13:10:48.856409   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 2166 txs in 12.038663527s. #1454601 [8873bddc / b99dfe60]"
[2016-05-04 13:10:54.577] [TRACE] main - NODE LOG: I0504 13:10:54.576890   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1602 txs in 5.719133455s. #1454857 [fb7d788e / 16ef8492]
[2016-05-04 13:10:54.577] [TRACE] main - "I0504 13:10:54.576890   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 1602 txs in 5.719133455s. #1454857 [fb7d788e / 16ef8492]"
[2016-05-04 13:10:59.076] [TRACE] main - NODE LOG: I0504 13:10:59.076287   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 977 txs in 4.498113233s. #1455113 [660fa87e / d263226e]
[2016-05-04 13:10:59.076] [TRACE] main - "I0504 13:10:59.076287   60803 blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 977 txs in 4.498113233s. #1455113 [660fa87e / d263226e]"
[2016-05-04 13:11:00.910] [TRACE] main - NODE LOG: I0504 13:11:00.910558   60803 blockchain.go:1251] imported 84 block(s) (0 queued 0 ignored) including 504 txs in 1.833783555s. #1455197 [d21d57f0 / a8abb543]
[2016-05-04 13:11:00.911] [TRACE] main - "I0504 13:11:00.910558   60803 blockchain.go:1251] imported 84 block(s) (0 queued 0 ignored) including 504 txs in 1.833783555s. #1455197 [d21d57f0 / a8abb543]"
[2016-05-04 13:11:14.384] [INFO] checkNodeSync - Sync finished, starting app!
[2016-05-04 13:11:14.385] [INFO] main - Loading Interface at http://localhost:3000?reset-tabs=true
~~~~

**Comment by hiddentao** [comment]
Ok, we need to know what's going on in the UI. Could you repeat the above with a different commit please - https://github.com/hiddentao/mist/commit/0a84c8bdd2737c5a6e0f24fc03447a8246ade0d9

**Comment by lunokhod** [comment]
It still crashes at the same place. Here is the output:
~~~~
electron . --reset-tabs --loglevel trace
[2016-05-06 13:30:58.921] [DEBUG] getIpcPath - CONNECT to IPC PATH: /Users/lunokhod/Library/Ethereum/geth.ipc
[2016-05-06 13:30:58.962] [INFO] main - Starting in Mist mode
[2016-05-06 13:30:59.387] [DEBUG] getIpcPath - CONNECT to IPC PATH: /Users/lunokhod/Library/Ethereum/geth.ipc
[2016-05-06 13:30:59.620] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/lunokhod/Library/Ethereum/geth.ipc' }
Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2016-05-06 13:31:00.260] [INFO] ipcCommunicator - Backend language set to:  en
[2016-05-06 13:31:00.287] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/lunokhod/Library/Ethereum/geth.ipc' }
Error: connect ECONNREFUSED /Users/lunokhod/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2016-05-06 13:31:01.695] [DEBUG] main - Geth connection REFUSED 0
[2016-05-06 13:31:01.698] [INFO] main - Node type:  geth
[2016-05-06 13:31:01.698] [INFO] main - Network:  main
[2016-05-06 13:31:01.699] [DEBUG] getNodePath - Resolved path for geth: /Users/lunokhod/Desktop/mist/nodes/geth/darwin-x64/geth
[2016-05-06 13:31:01.700] [INFO] ethereumNodes - Start node from /Users/lunokhod/Desktop/mist/nodes/geth/darwin-x64/geth
[2016-05-06 13:31:01.706] [INFO] ethereumNodes - Stopping nodes...
[2016-05-06 13:31:01.707] [INFO] ethereumNodes - Starting geth node...
[2016-05-06 13:31:03.221] [DEBUG] ethereumNodes - Saved network type "main" to file: /Users/lunokhod/Library/Application Support/Mist/network
[2016-05-06 13:31:03.221] [DEBUG] ethereumNodes - Saved standard node "geth" to file: /Users/lunokhod/Library/Application Support/Mist/node
[2016-05-06 13:31:03.262] [TRACE] main - NODE LOG: I0506 13:31:03.261652   68680 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)
[2016-05-06 13:31:03.262] [TRACE] main - "I0506 13:31:03.261652   68680 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)"
[2016-05-06 13:31:03.420] [INFO] main - Geth connection FOUND
[2016-05-06 13:31:03.442] [INFO] checkNodeSync - Checking node sync status...
[2016-05-06 13:31:03.453] [DEBUG] checkNodeSync - Time between last block 62s
[2016-05-06 13:31:03.454] [INFO] checkNodeSync - No sync necessary, starting app!
[2016-05-06 13:31:03.455] [INFO] main - Loading Interface at http://localhost:3000?reset-tabs=true
[2016-05-06 13:31:07.302] [INFO] (ui: mist) - http://about:blank
~~~~

**Comment by RamXX** [comment]
Exactly the same issue here. The exception caught displays this in the Apple report:
```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000f8

VM Regions Near 0xf8:
--> 
    __TEXT                 000000010f443000-000000010f444000 [    4K] r-x/rwx SM=COW  /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
```

if it's any help.

**Comment by hiddentao** [comment]
@lunokhod What's interesting is that the `--reset-tabs` CLI arg had no effect as it didn't even reset the tabs. Could you paste in the contents of `interface/client/appStart.js` please.

**Comment by RamXX** [comment]
Downgraded to Electrum 0.36.12 and the crash goes away.

**Comment by datashaman** [comment]
I had the same issue on Ubuntu Linux 15.10, it just stops running after loading the interface. Resolved by downgrading global version of electron to 0.36.12. No idea what effect that will have on the rest of it, though. :)

**Comment by luclu** [comment]
@lunokhod, @RamXX do you still encouter this issue in `0.8.1`? This seems to be fixed upstream.

**Comment by luclu** [comment]
Closed as of inactivity.
