### ISSUE TITLE
fish: './geth' terminated by signal SIGKILL

### ISSUE THREAD

**Issue by i90rr** [ethereum/mist#557]
Node type: default (geth?)
OS: OS X 10.11.4 up-to-date
Network type: main
Mist version: 0.7.2

Mist refuses to launch; upon a closer look I found:
```
$ ./geth --fast --cache 512 --verbosity 5
fish: './geth --fast --cache 512 --ver…' terminated by signal SIGKILL (Forced quit)
$ ls -l
total 52320
-rwxr-xr-x@ 1 i90rr  staff  26786388 Apr 22 19:07 get
```

Add the following to issue, when possible:
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)

It doesn't exist currently -- Mist wasn't able to create it yet?

Thanks.

**Comment by fjl** [comment]
That looks like an interesting failure. Could you check whether anything interesting is printed to syslog when you start geth? You can view syslog output in Console.app.

**Comment by i90rr** [comment]
Hi @fjl, sorry for the late reply.

I'm on 0.7.4 now: it won't open from Finder nor from Spotlight. Since the Console logs shows nothing I went to the terminal (Fish / Bash):
```bash
~/A/E/C/MacOS ▶︎︎ ./Electron .
fish: './Electron .' terminated by signal SIGKILL (Forced quit)

bash-3.2$ ./Electron
Killed: 9
```

I'm not sure how to further get more information or what would be the appropriate steps to debug the issue, I await for your instructions.

Cheers.

**Comment by i90rr** [comment]
Okay, brief update: the above error seems to be strictly related to the way Mist is packaged; I just cloned the repo and launched Mist from the command line:
```
[2016-05-17 13:54:42.519] [INFO] main - Starting in Mist mode
[2016-05-17 13:54:43.262] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ENOENT /Users/i90rr/Library/Ethereum/geth.ipc]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/Users/i90rr/Library/Ethereum/geth.ipc' }
Error: connect ENOENT /Users/i90rr/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2016-05-17 13:54:43.606] [INFO] main - Node type:  geth
[2016-05-17 13:54:43.606] [INFO] main - Network:  main
[2016-05-17 13:54:43.607] [INFO] ethereumNodes - Start node from /Users/i90rr/Projects/mist/nodes/geth/darwin-x64/geth
[2016-05-17 13:54:43.614] [INFO] ethereumNodes - Stopping nodes...
[2016-05-17 13:54:43.614] [INFO] ethereumNodes - Starting geth node...
[2016-05-17 13:54:43.773] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-05-17 13:54:43.788] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ENOENT /Users/i90rr/Library/Ethereum/geth.ipc]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/Users/i90rr/Library/Ethereum/geth.ipc' }
Error: connect ENOENT /Users/i90rr/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2016-05-17 13:54:46.127] [INFO] main - Geth connection FOUND
[2016-05-17 13:54:46.139] [INFO] checkNodeSync - Checking node sync status...
```
Let's see how it goes.

**Comment by i90rr** [comment]
UPDATE: after syncing the blockchain for some time the process stalled so I closed Mist and upon launching it again I got the same SIGKILL error posted previously.

For now I'm switching to the Linux version until I have more spare time to dig what's happening here.
