### ISSUE TITLE
Error: spawn ENOENT when building

### ISSUE THREAD

**Issue by kenorb** [ethereum/mist#571]
OS: OS X
Mist version: current master

I'm trying to run `meteor` in `interface` folder as instructed in README, however I've got this error:

```
mist/interface $ meteor
[[[[[ ~/Sources/ethereum/mist/interface ]]]]]


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
kenorb@MBP ~/.../mist/interface $ tail ~/.config/Mis^C
```

```
$ node --version
v0.10.44
$ meteor --version
Meteor version 0.5.2
```

**Comment by luclu** [comment]
@kenorb what version of meteor are you running?

**Comment by kenorb** [comment]
Updated.

**Comment by luclu** [comment]
Please try to update to the latest stable release `1.3.2.4` via `meteor update`.

**Comment by luclu** [comment]
I dunno about **node**. Version `0.10.44` is up-to-date but you might try to migrate to a newer release [link](https://github.com/nodejs/LTS#lts_schedule).

**Comment by kenorb** [comment]
I've tried to update `meteor`, but it doesn't let me.

```
$ meteor update
Failed to download manifest.
$ curl -v https://install.meteor.com
* Rebuilt URL to: https://install.meteor.com/
*   Trying 50.16.136.212...
* Connected to install.meteor.com (50.16.136.212) port 443 (#0)
* SSL peer handshake failed, the server most likely requires a client certificate to connect
* Closing connection 0
curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
```

**Comment by luclu** [comment]
Please try to remove and reinstall [Meteor](https://www.meteor.com/install).

**Comment by kenorb** [comment]
Did:

    $ npm remove meteor -g
Installing generated 2 warnings:

```
$ npm install meteor -g
npm WARN engine gzippo@0.1.7: wanted: {"node":">= 0.5 < 0.9"} (current: {"node":"0.10.44","npm":"2.15.0"})
/
> fibers@0.6.9 install /usr/local/lib/node_modules/meteor/node_modules/fibers
> node ./build.js

meteor -v  CXX(target) Release/obj.target/fibers/src/fibers.o

  CXX(target) Release/obj.target/fibers/src/coroutine.o
../src/coroutine.cc:23:41: warning: implicit conversion of NULL constant to 'pthread_key_t' (aka 'unsigned long') [-Wnull-conversion]
static pthread_key_t floor_thread_key = NULL;
                     ~~~~~~~~~~~~~~~~   ^~~~
                                        0
../src/coroutine.cc:24:40: warning: implicit conversion of NULL constant to 'pthread_key_t' (aka 'unsigned long') [-Wnull-conversion]
static pthread_key_t ceil_thread_key = NULL;
                     ~~~~~~~~~~~~~~~   ^~~~
                                       0
2 warnings generated.
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
Installed in `/usr/local/lib/node_modules/meteor/node_modules/fibers/bin/darwin-x64-v8-3.14/fibers.node`

> bson@0.1.5 install /usr/local/lib/node_modules/meteor/node_modules/mongodb/node_modules/bson
> node install.js || (exit 0)

```

The install proceed and I've got now meteor@0.5.2-1:

```
meteor@0.5.2-1 /usr/local/lib/node_modules/meteor
├── keypress@0.1.0
├── progress@0.0.5
├── semver@1.1.0
├── stream-buffers@0.2.3
├── mime@1.2.7
├── gzippo@0.1.7
├── optimist@0.3.5 (wordwrap@0.0.3)
├── nib@0.8.2
├── simplesmtp@0.1.25 (xoauth2@1.1.0, rai@0.1.12)
├── mailcomposer@0.1.15 (mimelib-noiconv@0.1.9)
├── coffee-script@1.4.0
├── sockjs@0.3.4 (node-uuid@1.3.3, faye-websocket@0.4.0)
├── useragent@1.1.0 (yamlparser@0.0.2, semver@1.0.14, request@2.9.202)
├── http-proxy@0.8.5 (colors@0.6.2, pkginfo@0.2.3)
├── stylus@0.30.1 (mkdirp@0.3.5, cssom@0.2.5, debug@2.2.0)
├── clean-css@0.8.2
├── uglify-js@1.3.4
├── connect@1.9.2 (formidable@1.0.17, qs@6.2.0)
├── request@2.12.0
├── handlebars@1.0.7 (uglify-js@1.2.6)
├── less@1.3.1
├── fibers@0.6.9
└── mongodb@1.1.11 (bson@0.1.5)

```

I hope that's the recent version (since it has extra `-1`).

However it still doesn't work inside `mist/interface`, e.g.

```
$ meteor -v
[[[[[ ~/Sources/GitHub/ethereum/mist/interface ]]]]]


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
kenorb@MBP ~/.../mist/interface $ meteor -V
[[[[[ ~/Sources/GitHub/ethereum/mist/interface ]]]]]


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by luclu** [comment]
Try not to use npm for meteor but the linked installer.

**Comment by kenorb** [comment]
Using `wget` instead worked fine:

    wget -qO- https://install.meteor.com | sh

This installed Meteor 1.3.2.4.

After than using `meteor` in mentioned scenario worked fine.

Thanks for your help.

**Comment by luclu** [comment]
Awesome! Have fun ;)
