### ISSUE TITLE
Black / White window

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#599]
**Please** use [this issue](https://github.com/ethereum/mist/issues/75) and append to it, **if you are affected**. (Reports will be pooled over there.)

This is an issue regarding the [electron-shell](https://github.com/atom/electron). Users of other applications are affected as well. 

--- 

Currently there are three known work-arounds for this:

1. Verify your graphics-drivers are up-to-date. If you are running open-source-drivers try the vendor's proprietary ones.
2. Run **Ethereum Wallet** / **Mist** from the commandline with the flag `--ignore-gpu-blacklist`.
 - Windows: `./Ethereum-Wallet.exe --ignore-gpu-blacklist`
 - OSX / Linux:  `./Ethereum-Wallet --ignore-gpu-blacklist`
3. Downgrade to an earlier version. (Won't do any harm, but may introduce already closed bugs - **not recommended**)

---

If you are affected and want to help, please try out [these steps](https://github.com/ethereum/mist/issues/75#issuecomment-183257637) and report back here.

**Comment by luclu** [comment]
Create a batch-file on Linux:

1 . In a texteditor paste:
```
#!/bin/bash
echo running the Ethereum Wallet
./Ethereum-Wallet --ignore-gpu-blacklist
```
2 . save file (without ending) in the folder cointaining `Ethereum-Wallet`

3 . you might need to make it executable with `chmod +x <filename>`

**Comment by pabx06** [comment]
![image](https://user-images.githubusercontent.com/4013370/36771296-d7203258-1c4f-11e8-8cdc-8b0cd65f1b11.png)
i tried ./Ethereum\ Wallet.exe --ignore-gpu-blacklist
but samething here... with the latest 64 bit & 32bit

**Comment by LordMort** [comment]
Same problem here. Actually this problem has been persistently occurring for me since version 0.8.10 of BOTH Ethereum Wallet, as well as Mist.
Downgrading to an earlier version has been tried unsuccessfully, as has the "--ignore-gpu-blacklist", as well as switching between the 32-Bit and the 64-Bit versions of BOTH Ethereum Wallet and Mist

System (current): Windows 10 Pro x64 1803
Graphics: -Integrated Intel HD 3000
               -Dedicated NVIDIA Quaro 1000M

OpenGL: Working, tested with multiple other crypto wallets

Issues:
=> Ethereum Wallet:
      - Starts with a blank screen. The log shows that it has been unable to find the, INSTALLED, geth "binPath".
      - Using the "--ignore-gpu-blacklist" option has NO effect
      - The installation of geth has been checked to have been successful, because I am able to start geth when using it DIRECTLY.
      - Using geth from the command line is possible, both starting up and syncing

=> Mist
      - Starts with a blank screen. The log shows that there were issues with a .js-file where a "null" object has been causing problems (see attached log excerpt) in a "queued task" with a "TypeError" being thrown
      - Using the "--ignore-gpu-blacklist" option has NO effect
      - Using geth from the command line is possible, both starting up and syncing

=> Excerpt from Mist "all.log" with reoccurring problem
"
[2018-10-28T00:53:24.729] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-10-28T00:53:24.737] [INFO] (ui: mist) - Meteor starting up...
[2018-10-28T00:53:24.745] [INFO] (ui: mist) - Initialize Mist Interface
[2018-10-28T00:53:25.900] [INFO] (ui: mist) - Exception in queued task: TypeError: Cannot read property '0' of null
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29754
    at Object.e.nonreactive (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:13:4492)
    at Object.changedAt (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29614)
    at Object.changedAt (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:83:2699)
    at e.changed (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:32268)
    at Object.applyChange.changed (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:26775)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:17106
    at n._SynchronousQueue.t.runTask (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4645)
    at n._SynchronousQueue.t.flush (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4942)
    at n._SynchronousQueue.t.drain (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:5051)
    at r.t [as update] (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:24016)
    at o.update (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:75:7408)
    at Object.checkedUrl (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:67869)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31312
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:17158
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31945
    at Function.e._withTemplateInstanceFunc (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:37654)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31852
    at p.call (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1925)
    at p.mustacheImpl (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1182)
    at Object.p.mustache (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1241)
    at src (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:65402)
[2018-10-28T00:53:25.922] [INFO] (ui: mist) - Exception in queued task: TypeError: Cannot read property '1' of null
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29754
    at Object.e.nonreactive (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:13:4492)
    at Object.changedAt (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29614)
    at Object.changedAt (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:83:2699)
    at e.changed (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:32268)
    at Object.applyChange.changed (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:26775)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:17106
    at n._SynchronousQueue.t.runTask (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4645)
    at n._SynchronousQueue.t.flush (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4942)
    at n._SynchronousQueue.t.drain (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:5051)
    at r.t [as update] (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:24016)
    at o.update (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:75:7408)
    at Object.checkedUrl (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:67869)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31312
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:17158
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31945
    at Function.e._withTemplateInstanceFunc (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:37654)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31852
    at p.call (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1925)
    at p.mustacheImpl (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1182)
    at Object.p.mustache (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1241)
    at src (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:65402)
[2018-10-28T00:53:25.925] [INFO] (ui: mist) - Exception in queued task: TypeError: Cannot read property '1' of null
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29754
    at Object.e.nonreactive (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:13:4492)
    at Object.changedAt (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:29614)
    at Object.changedAt (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:83:2699)
    at e.changed (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:32268)
    at Object.applyChange.changed (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:26775)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:17106
    at n._SynchronousQueue.t.runTask (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4645)
    at n._SynchronousQueue.t.flush (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:4942)
    at n._SynchronousQueue.t.drain (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:1:5051)
    at r.t [as update] (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:53:24016)
    at o.update (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:75:7408)
    at Object.checkedUrl (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:68242)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31312
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:17158
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31945
    at Function.e._withTemplateInstanceFunc (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:37654)
    at file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:91:31852
    at p.call (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1925)
    at p.mustacheImpl (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1182)
    at Object.p.mustache (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:93:1241)
    at src (file:///*********************/Mist/resources/app.asar/interface/906a32c06fa638643ada12739f8e4d1862ddb954.js:189:65402)
[2018-10-28T00:53:26.096] [INFO] (ui: mist) - did-navigate wallet file:///*********************/Mist/resources/app.asar/wallet/index.html
[2018-10-28T00:53:26.098] [INFO] Sockets/3 - Disconnecting...
[2018-10-28T00:53:26.260] [INFO] (ui: mist) - did-navigate browser https://www.stateofthedapps.com/
[2018-10-28T00:53:26.347] [INFO] Sockets/4 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-10-28T00:53:26.349] [INFO] Sockets/4 - Connected!
[2018-10-28T00:53:26.506] [INFO] Sockets/5 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-10-28T00:53:26.507] [INFO] Sockets/5 - Connected!
[2018-10-28T00:53:26.710] [INFO] (ui: mist) - did-navigate-in-page browser https://www.stateofthedapps.com/
[2018-10-28T00:53:26.726] [INFO] (ui: mist) - dom-ready browser https://www.stateofthedapps.com/
[2018-10-28T00:53:26.746] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-10-28T00:53:26.747] [INFO] Sockets/3 - Connected!
[2018-10-28T00:53:26.981] [INFO] (ui: mist) - did-stop-loading browser https://www.stateofthedapps.com/
[2018-10-28T00:53:27.067] [INFO] (ui: mist) - did-get-redirect-request browser https://www.stateofthedapps.com/
[2018-10-28T00:53:27.314] [INFO] (ui: mist) - did-navigate-in-page wallet file:///*********************/Mist/resources/app.asar/wallet/index.html#!/*********************/Mist/resources/app.asar/wallet/index.html
[2018-10-28T00:53:27.358] [INFO] (ui: mist) - did-navigate-in-page wallet file:///C:/
[2018-10-28T00:53:27.379] [INFO] (ui: mist) - dom-ready wallet file:///C:/
[2018-10-28T00:53:27.480] [INFO] (ui: mist) - did-stop-loading wallet file:///C:/
[2018-10-28T00:54:16.211] [INFO] main - Defer quitting until sockets and node are shut down
[2018-10-28T00:54:16.212] [INFO] Sockets - Destroy all sockets
[2018-10-28T00:54:16.212] [INFO] Sockets/2 - Disconnecting...
[2018-10-28T00:54:16.213] [INFO] Sockets/3 - Disconnecting...
[2018-10-28T00:54:16.213] [INFO] Sockets/4 - Disconnecting...
[2018-10-28T00:54:16.213] [INFO] Sockets/5 - Disconnecting...
[2018-10-28T00:54:16.214] [INFO] Sockets/node-ipc - Disconnecting...
[2018-10-28T00:54:16.630] [INFO] Sockets/4 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-10-28T00:54:16.631] [INFO] Sockets/4 - Connected!
[2018-10-28T00:54:16.723] [INFO] main - About to quit...
[2018-10-28T00:54:16.742] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2018-10-28T00:54:16.742] [INFO] main - About to quit...
"

I would be grateful for a proposed solution seeing as this is a rather vexing problem.
In case of a reply, please bear in mind that the solutions proposed by @luclu, @frozeman  and others have so far been tried and found to be NOT working.
