### ISSUE TITLE
Cannot process transaction - UNCAUGHT EXCEPTION

### ISSUE THREAD

**Issue by gcarq** [ethereum/mist#638]
`mist` crashes if a want to send ether from a slock.it DAO account address to a regular address.
Note: I have a slock.it DAO watch contract set up.

```
[2016-05-14 04:04:20.772] [INFO] (ui: wallet) - Estimated gas:  21000 null
[2016-05-14 04:04:20.998] [INFO] (ui: wallet) - Estimated gas:  21000 null
[2016-05-14 04:04:21.972] [INFO] (ui: wallet) - Providing gas:  21000 
[2016-05-14 04:04:21.973] [INFO] (ui: wallet) - Finally choosen gas 21000
[2016-05-14 04:04:21.974] [INFO] (ui: wallet) - Send Ether
[2016-05-14 04:04:21.974] [INFO] (ui: wallet) - Gas Price: 13624789530
[2016-05-14 04:04:21.974] [INFO] (ui: wallet) - Amount: 8832059419851569
[2016-05-14 04:04:22.885] [INFO] (ui: popup) - Estimated gas:  21000 null
[2016-05-14 04:04:27.263] [INFO] (ui: popup) - Choosen Gas:  0x5208 0x5208
[2016-05-14 04:04:28.160] [ERROR] main - UNCAUGHT EXCEPTION [Error: Object has been destroyed]
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.<anonymous> (/usr/share/mist/resources/app.asar/modules/ipc/ipcProviderBackend.js:388:31)
    at EventEmitter.g (events.js:260:16)
    at emitThree (events.js:102:20)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/usr/share/mist/resources/atom.asar/browser/api/web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
[2016-05-14 04:04:28.162] [INFO] main - Closing socket 8
[2016-05-14 04:04:28.162] [INFO] main - Closing socket 10
[2016-05-14 04:04:28.162] [INFO] main - Closing socket 12
[2016-05-14 04:04:28.663] [INFO] ethereumNodes - Stopping nodes...
[2016-05-14 04:04:28.664] [INFO] main - Closing socket 8
```
Occurred on aur/mist0.7.3-1 @ Linux 4.4.8-1-ck #1 SMP PREEMPT x86_64 GNU/Linux

**Comment by luclu** [comment]
@gcarq please check if this issue still occures on version 0.7.4 as many fixes are included. Ping me back on the outcome!

**Comment by luclu** [comment]
I will close this for now.
