### ISSUE TITLE
Ethereum Wallet 0.7.5 freezes after loading up

### ISSUE THREAD

**Issue by amustafa** [ethereum/mist#836]
I just downloaded Ethereum Wallet 0.7.5 and the screen freezes after loading up. I run the file in the terminal, it loads the screen, connect to geth (or starts a geth connection) and then opens up to the main screen, correctly showing all of my accounts. After that, everything freezes. No buttons are clickable and the main screen isn't scroll-able. The menu items still work though.

I'm currently building the source to see if it's just the build or if it's the code as well. 

Node type: geth
OS: linux (64bit)
Network type: main
Mist version: 0.7.5

With Geth running in another process:
[2016-06-16 00:19:28.457] [INFO] main - Running in production mode: true
[2016-06-16 00:19:28.531] [INFO] main - Starting in Wallet mode
[2016-06-16 00:19:28.646] [INFO] Windows - Creating commonly-used windows
[2016-06-16 00:19:28.647] [INFO] Windows - Create window: loading, owner: notset
[2016-06-16 00:19:28.835] [INFO] updateChecker - Check for update...
[2016-06-16 00:19:30.522] [INFO] Windows - Create window: main, owner: notset
[2016-06-16 00:19:30.534] [INFO] Windows - Create window: splash, owner: notset
[2016-06-16 00:19:31.321] [INFO] updateChecker - App is up-to-date.
[2016-06-16 00:19:31.453] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-06-16 00:19:32.229] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-06-16 00:19:32.390] [INFO] Sockets/node-ipc - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:19:32.479] [INFO] Sockets/node-ipc - Connected!
[2016-06-16 00:19:32.480] [INFO] NodeSync - Ethereum node connected, re-start sync
[2016-06-16 00:19:32.481] [INFO] NodeSync - Starting sync loop
[2016-06-16 00:19:32.482] [INFO] Sockets/7 - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:19:32.483] [INFO] main - Connected via IPC to node.
[2016-06-16 00:19:32.498] [INFO] Sockets/7 - Connected!
[2016-06-16 00:19:32.508] [INFO] (ui: splash) - network is mainnet
[2016-06-16 00:19:34.486] [INFO] NodeSync - No more sync necessary
[2016-06-16 00:19:34.487] [INFO] main - Loading Interface at file:///home/amustafa/Applications/opt/Ethereum-Wallet/Ethereum-Wallet-linux64-0-7-5/resources/app.asar/interface/wallet/index.html
[2016-06-16 00:19:34.513] [INFO] NodeSync - Sync loop ended
[2016-06-16 00:19:34.794] [INFO] Sockets/8 - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:19:34.795] [INFO] Sockets/8 - Connected!
[2016-06-16 00:19:43.105] [INFO] (ui: wallet) - Connect to node...

Without Geth running in another process:
[2016-06-16 00:21:06.283] [INFO] main - Running in production mode: true
[2016-06-16 00:21:06.355] [INFO] main - Starting in Wallet mode
[2016-06-16 00:21:06.477] [INFO] Windows - Creating commonly-used windows
[2016-06-16 00:21:06.478] [INFO] Windows - Create window: loading, owner: notset
[2016-06-16 00:21:06.677] [INFO] updateChecker - Check for update...
[2016-06-16 00:21:08.395] [INFO] Windows - Create window: main, owner: notset
[2016-06-16 00:21:08.410] [INFO] Windows - Create window: splash, owner: notset
[2016-06-16 00:21:09.255] [INFO] updateChecker - App is up-to-date.
[2016-06-16 00:21:09.396] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-06-16 00:21:10.156] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-06-16 00:21:10.355] [INFO] Sockets/node-ipc - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:21:10.447] [ERROR] Sockets/node-ipc - Connection error { Error: connect ENOENT /home/amustafa/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/amustafa/.ethereum/geth.ipc' }
Error: connect ENOENT /home/amustafa/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
[2016-06-16 00:21:10.490] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-06-16 00:21:10.490] [INFO] EthereumNode - Node type: geth
[2016-06-16 00:21:10.490] [INFO] EthereumNode - Network: main
[2016-06-16 00:21:10.491] [INFO] EthereumNode - Start node: geth main
[2016-06-16 00:21:14.561] [INFO] EthereumNode - 4s elapsed, assuming node started up successfully
[2016-06-16 00:21:14.562] [INFO] EthereumNode - Started node successfully: geth main
[2016-06-16 00:21:14.563] [INFO] Sockets/node-ipc - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:21:14.564] [INFO] Sockets/node-ipc - Connected!
[2016-06-16 00:21:14.572] [INFO] NodeSync - Ethereum node connected, re-start sync
[2016-06-16 00:21:14.575] [INFO] NodeSync - Starting sync loop
[2016-06-16 00:21:14.576] [INFO] Sockets/7 - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:21:14.577] [INFO] main - Connected via IPC to node.
[2016-06-16 00:21:14.591] [INFO] Sockets/7 - Connected!
[2016-06-16 00:21:14.615] [INFO] (ui: splash) - network is mainnet
[2016-06-16 00:21:16.579] [INFO] NodeSync - No more sync necessary
[2016-06-16 00:21:16.579] [INFO] main - Loading Interface at file:///home/amustafa/Applications/opt/Ethereum-Wallet/Ethereum-Wallet-linux64-0-7-5/resources/app.asar/interface/wallet/index.html
[2016-06-16 00:21:16.605] [INFO] NodeSync - Sync loop ended
[2016-06-16 00:21:16.892] [INFO] Sockets/8 - Connect to {"path":"/home/amustafa/.ethereum/geth.ipc"}
[2016-06-16 00:21:16.893] [INFO] Sockets/8 - Connected!
[2016-06-16 00:21:20.533] [INFO] (ui: wallet) - Node started syncing, stopping app operation
[2016-06-16 00:21:25.389] [INFO] (ui: wallet) - Connect to node...

**Comment by nvmr** [comment]
Same for the OS X version on OS X 10.11.5. Balances are shown correctly but the tool is unresponsive and says "waiting for blocks" forever. Only way to quit it is via Force Quit. Same behaviour whether I run geth separately or not.
<img width="340" alt="screen shot 2016-06-16 at 10 54 43" src="https://cloud.githubusercontent.com/assets/4020438/16112839/89272faa-33b9-11e6-96e3-1c099d7fbf3e.png">

Version 0.74 continues to work for me.

**Comment by tuxbear** [comment]
+1 for OS X 10.11.4

**Comment by bahner** [comment]
+1 for Ubuntu. Strace attached. The strace is a "strace -ffp PID" running for a few seconds. It's mostly timeouts.
[mist.txt](https://github.com/ethereum/mist/files/318213/mist.txt)

**Comment by willtate** [comment]
+1 Locks in OSX.  in 0.7.4 I was able to fix a similar behavior by completely deleting the chain data and having it resync, but that didn't help this time.

**Comment by davedavis** [comment]
Same issue. 
Windows 10, x64. 

Loads up fine and syncs, then for some reason, after getting up to date, it displays that I'm 41 mins behind. This appeared within minutes of syncing the last block. 

The menu elements and the close "X" button are still active though. 
Process is leaking more memory than the previous version too. 

![memleak](https://cloud.githubusercontent.com/assets/5341256/16143486/f60f8f76-3464-11e6-9d63-cae7dbcf6a14.jpg)
![bug](https://cloud.githubusercontent.com/assets/5341256/16143487/f612bf52-3464-11e6-8d75-14f72d745433.jpg)

After approximately 10 minutes after clicking the "X" close button, Electron and Geth terminated. 

I'll try grab the log when it happens again.

**Comment by sjledet** [comment]
I'm getting the same issue

**Comment by somhi** [comment]
same issue here on Ubuntu 16.04

**Comment by bp360** [comment]
Same, mac 10.11.5, mist 0.7.5, geth 1.4.7, SSD

Switching to the Testnet (for just a minute or two - not long enough to sync the whole testnet) then switching back to the Main Network temporarily had my block timer ("22s since last block"...) working again - until my fan fired up and geth was cranking again and it froze after about 1 minute :(

**Comment by jstefanop** [comment]
same issue on Mac...this version pretty much broke the wallet...CPU @ 300% and it eats up gigs of ram. Trying to launch the 7.4 version does the same thing now...

**Comment by luclu** [comment]
@jstefanop could you kindly join the discussion over here https://github.com/ethereum/mist/issues/837 and run that commands listed there while having this memory bloat (2+ GB)?
Your help is much appreciated. Thank you!

**Comment by jstefanop** [comment]
@luclu done

**Comment by luclu** [comment]
@jstefanop thank you! could you also please add geth's memory footprint to the post?

**Comment by amustafa** [comment]
I found a workaround for my issue. 

I made the ~/.config/Mist folder inaccessible (by deleting or renaming). The interface worked fine after that. I did need to reload all my contracts though. I only had a few so it wasn't too bad.

**Comment by jstefanop** [comment]
Another work around is to let your geth node be outdated for a a couple hundred blocks, then launch the wallet and wait until it starts downloading blocks, then quickly kill your internet connection. As long as it does not sync all the way it will buy you enough time to launch the interface, go to contracts and load up the DAO contract then delete it. This will resolve the issue until the bug is fixed.
