### ISSUE TITLE
Problem with mist Wallet 0.7.6 (Beta 20) “vulnerability release”

### ISSUE THREAD

**Issue by lgs** [ethereum/mist#891]
After updating to Wallet 0.7.6 (Beta 20), running mist start syncing mainnet from the beginning, which is very bad, because syncing ~1,7MBlocks took me 4 days last time ...

Is that due to the "vulnerability release" ? Can I speed up the sync (... no, 'geth --fast' doesn't help).

It also give me ntp server errors which I didn't get with Wallet 0.7.5, here it is a log snippet:

<pre>
[2016-06-26 22:32:27.913] [ERROR] main - Couldn't get time from NTP time sync server. Error: can't find 'ntp enabled:' line in timedatectl output
    at /home/lsoave/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/node_modules/os-timesync/index.js:47:19
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
Error: can't find 'ntp enabled:' line in timedatectl output
    at /home/lsoave/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/node_modules/os-timesync/index.js:47:19
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
</pre>

NOTE: crossposted on http://ethereum.stackexchange.com/questions/6549/problem-with-mist-wallet-0-7-6-beta-20-vulnerability-release

**Comment by luclu** [comment]
Could you please give me the size of the `chaindata`-folder?
Do you use geth from the terminal?

---

> Is that due to the "vulnerability release" ?

No, `0.7.5` as well as `0.7.6` use the same version of geth.

> Can I speed up the sync (... no, 'geth --fast' doesn't help).

The wallet already uses `--fast`.

> It also give me ntp server errors which I didn't get with Wallet 0.7.5, here it is a log snippet:

This bug was introduces in verison `0.7.6` - There is already a bug report: https://github.com/ethereum/mist/issues/397#issuecomment-228400418

**Comment by lgs** [comment]
... while it is still syncing (around 1.2MBlocks):

<pre>
lsoave@basenode:~$ du -ms /home/lsoave/.ethereum/
31625	/home/lsoave/.ethereum/
lsoave@basenode:~$ du -ms /home/lsoave/.ethereum/chaindata
27277	/home/lsoave/.ethereum/chaindata
</pre>

yes, I use 'geth' from the terminal (bash) on Ubuntu 16.04

**Comment by luclu** [comment]
Please don't mix `stable` and `unstable` branches/releases of geth. The current `develop` branch cointains this for example this PR https://github.com/ethereum/go-ethereum/pull/2455 which will break backwards compatibility with `1.4.8` and earlier. This might even be the cause of your troubles.

Feel free to ask any question, but I will close this issue as we can't support these kind of cases in our frontend issue tracker. ;)
