### ISSUE TITLE
UNCAUGHT EXCEPTION TypeError: this._onSyncDone is not a function

### ISSUE THREAD

**Issue by zweicoder** [ethereum/mist#907]
Node type: geth
OS: linux
Network type: main/test
Mist version: 0.7.6

```javascript
[ERROR] main - UNCAUGHT EXCEPTION TypeError: this._onSyncDone is not a function
    at EventEmitter.ipc.on (/home/pewpew/Downloads/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/modules/nodeSync.js:57:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.<anonymous> (/home/pewpew/Downloads/Ethereum-Wallet-linux64-0-7-6/resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
TypeError: this._onSyncDone is not a function
    at EventEmitter.ipc.on (/home/pewpew/Downloads/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/modules/nodeSync.js:57:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.<anonymous> (/home/pewpew/Downloads/Ethereum-Wallet-linux64-0-7-6/resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

```
Just reporting this bug I experienced. 

Wallet crashed after node finished syncing. I'm running geth 1.5.0-unstable on a different datadir like so: `geth --datadir /media/windows/.ethereum/ --ipcpath ~/.ethereum/geth.ipc` then starting mist so I can use a different `datadir`.

**Comment by luclu** [comment]
Thank you @zweicoder.
Though as no other reports have been filed and you were using geth `1.5.0-unstable` I will close this for now.
