### ISSUE TITLE
Mist Browsers mode does not load websites

### ISSUE THREAD

**Issue by MaVo159** [ethereum/mist#908]
Node type: geth
OS: linux
Network type: both
Mist version: 0.7.6

In mist mode no webpages are loaded. The window stays white after typing the address into the address bar and pressing enter. I tried this with 

I checked with http://governmental.github.io/GovernMental/index.html and a locally hosted site. The locally hosted site revealed that Mist doesn't even try to access the webserver. 

Are there any alternative ways of displaying a dapp in mist?

The node.log contains nothing but the typical stuff from running geth successfully.

Terminal log:
./Ethereum-Wallet --mode=mist
[2016-06-29 18:07:52.152] [INFO] main - Running in production mode: true
[2016-06-29 18:07:52.205] [INFO] main - Starting in Mist mode
[2016-06-29 18:07:52.298] [INFO] Windows - Creating commonly-used windows
[2016-06-29 18:07:52.299] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-06-29 18:07:52.310] [INFO] updateChecker - Check for update...
[2016-06-29 18:07:53.435] [INFO] Windows - Create primary window: main, owner: notset
[2016-06-29 18:07:53.451] [INFO] Windows - Create primary window: splash, owner: notset
[2016-06-29 18:07:53.742] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-06-29 18:07:54.135] [INFO] updateChecker - App is up-to-date.
[2016-06-29 18:07:54.260] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-06-29 18:07:54.355] [INFO] Sockets/node-ipc - Connect to {"path":"/home/xxx/.ethereum/geth.ipc"}
[2016-06-29 18:07:54.360] [ERROR] Sockets/node-ipc - Connection error { Error: connect ENOENT /home/xxx/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/xxx/.ethereum/geth.ipc' }
Error: connect ENOENT /home/xxx/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
[2016-06-29 18:07:54.378] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-06-29 18:07:54.378] [INFO] EthereumNode - Node type: geth
[2016-06-29 18:07:54.378] [INFO] EthereumNode - Network: main
[2016-06-29 18:07:54.378] [INFO] EthereumNode - Start node: geth main
[2016-06-29 18:07:58.565] [INFO] EthereumNode - 4s elapsed, assuming node started up successfully
[2016-06-29 18:07:58.566] [INFO] EthereumNode - Started node successfully: geth main
[2016-06-29 18:07:58.577] [INFO] Sockets/node-ipc - Connect to {"path":"/home/xxx/.ethereum/geth.ipc"}
[2016-06-29 18:07:58.579] [INFO] Sockets/node-ipc - Connected!
[2016-06-29 18:07:58.579] [INFO] NodeSync - Ethereum node connected, re-start sync
[2016-06-29 18:07:58.581] [INFO] NodeSync - Starting sync loop
[2016-06-29 18:07:58.582] [INFO] Sockets/7 - Connect to {"path":"/home/xxx/.ethereum/geth.ipc"}
[2016-06-29 18:07:58.583] [INFO] main - Connected via IPC to node.
[2016-06-29 18:07:58.605] [INFO] Sockets/7 - Connected!
[2016-06-29 18:07:58.617] [INFO] (ui: splash) - network is mainnet
[2016-06-29 18:14:49.263] [INFO] main - Loading Interface at file:///home/xxx/EthWallet/resources/app.asar/interface/index.html
[2016-06-29 18:14:49.303] [INFO] NodeSync - Sync loop ended
[2016-06-29 18:14:49.590] [INFO] Sockets/8 - Connect to {"path":"/home/xxx/.ethereum/geth.ipc"}
[2016-06-29 18:14:49.594] [INFO] Sockets/8 - Connected!
[2016-06-29 18:14:50.094] [INFO] (ui: mist) - Web3 already initialized, re-using provider.
[2016-06-29 18:14:50.159] [INFO] (ui: mist) - Meteor starting up...
[2016-06-29 18:14:50.187] [INFO] (ui: mist) - Node started syncing, stopping app operation
[2016-06-29 18:14:50.246] [INFO] (ui: mist) - http://governmental.github.io/GovernMental/index.html

**Comment by MaVo159** [comment]
This is a dublicate of #884
