### ISSUE TITLE
Socket creates multiple event listeners on reset?

### ISSUE THREAD

**Issue by frozeman** [ethereum/mist#917]
Mist version: 0.7.6

This issue is a collection of issues i encountered while working on web3.js subscriptions:

I work currently on the new web3.js subscriptions and especially here on the part which auto-subscribes to a lost socket connection.

It seems like when you have mist running and you kill the node and restart it, that the error/end/timeout etc events get replicated on the socket and the send down multiple times to `owner.send('ipcProvider-....')`.

-----

Additionally there is a uncaught connection error, which leads to mist crashing, when mist is killed.
```js
[2016-07-01 16:37:40.922] [ERROR] main - UNCAUGHT EXCEPTION { Error: connect ENOENT /Users/frozeman/Library/Ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/Users/frozeman/Library/Ethereum/geth.ipc' }
```

---

- [ ] Multiple event listeners on socket
- [ ] uncaught connection error

**Comment by hiddentao** [comment]
So you're running Geth separately to Mist? And thus shutting it down externally?

**Comment by hiddentao** [comment]
Having trouble reproducing these errors
