### ISSUE TITLE
Error checking for update TypeError: Invalid Version: 0.8

### ISSUE THREAD

**Issue by nicksavers** [ethereum/mist#943]
Node type: geth
OS: Ubuntu Linux 16.04 x64
Network type: main
Mist version: 0.8.0

```javascript
[2016-07-08 20:01:45.619] [INFO] updateChecker - Check for update...
[2016-07-08 20:01:46.603] [ERROR] updateChecker - Error checking for update TypeError: Invalid Version: 0.8
    at new SemVer (/home/nick/Mist-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:293:11)
    at compare (/home/nick/Mist-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/home/nick/Mist-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:595:10)
    at got.then (/home/nick/Mist-linux64-0-8-0/resources/app.asar/modules/updateChecker.js:49:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by 5chdn** [comment]
Same here on Arch Linux x64.

**Comment by luclu** [comment]
This error is caused by a wrong release name not following the updater's convention. We are most likely going to fix this by changing its name and trigger the update-alert today.
