### ISSUE TITLE
Mist wont open after power outage/ computer crash

### ISSUE THREAD

**Issue by uraxs** [ethereum/mist#946]
Node type: geth/eth
OS: linux
Network type: main
Mist version: 0.7.6

Mist wont open after power outage/ computer crash

![image](https://cloud.githubusercontent.com/assets/20372686/16709031/bdce4068-45fc-11e6-859f-cc68ae08da43.png)

I'm sure this is an easy fix but I'd appreciate a little guidance. Been spending too much time searching for the correct log and I can't find the backups I made so my ether is stuck in the ether...

More than happy to upload any needed info if I know what you need and where to find it. 
Ethereum-Wallet-linux64-0-7-6

thx

I've checked the already existing issues, before creating this issue. 

My log files are empty!

-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
Please try to start `Ethereum-Wallet` via terminal and post its output.

**Comment by uraxs** [comment]
g@g-All-Series ~ $ ps -ef | grep geth 
g         4201  4182  0 12:57 pts/3    00:00:00 grep --colour=auto geth
g@g-All-Series ~ $ sudo cd /Ethereum
[sudo] password for g: 
sudo: cd: command not found
g@g-All-Series ~ $ sudo cd /Ethereum-Wallet-linux64-0-7-6
sudo: cd: command not found
g@g-All-Series ~ $ cd /Ethereum-Wallet-linux64-0-7-6
bash: cd: /Ethereum-Wallet-linux64-0-7-6: No such file or directory
g@g-All-Series ~ $ cd /home/g/Ethereum-Wallet-linux64-0-7-6
g@g-All-Series ~/Ethereum-Wallet-linux64-0-7-6 $ ./Ethereum-Wallet
[2016-07-11 13:04:15.377] [INFO] main - Running in production mode: true
[2016-07-11 13:04:15.445] [INFO] main - Starting in Wallet mode
[2016-07-11 13:04:15.660] [INFO] Windows - Creating commonly-used windows
[2016-07-11 13:04:15.661] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-07-11 13:04:15.769] [INFO] updateChecker - Check for update...
[2016-07-11 13:04:19.287] [INFO] Windows - Create primary window: main, owner: notset
[2016-07-11 13:04:19.468] [INFO] Windows - Create primary window: splash, owner: notset
[2016-07-11 13:04:20.547] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-07-11 13:04:21.318] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-07-11 13:04:21.588] [INFO] Sockets/node-ipc - Connect to {"path":"/home/g/.ethereum/geth.ipc"}
[2016-07-11 13:04:21.595] [ERROR] Sockets/node-ipc - Connection error { Error: connect ECONNREFUSED /home/g/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/home/g/.ethereum/geth.ipc' }
Error: connect ECONNREFUSED /home/g/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
[2016-07-11 13:04:21.619] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-07-11 13:04:21.621] [INFO] EthereumNode - Node type: �dEF
[2016-07-11 13:04:21.621] [INFO] EthereumNode - Network: uR�
[2016-07-11 13:04:21.621] [INFO] EthereumNode - Start node: �dEF uR�
[2016-07-11 13:04:21.645] [INFO] EthereumNode - Node startup error
[2016-07-11 13:04:21.647] [ERROR] EthereumNode - Failed to start node { Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  path: '/home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  spawnargs: [ '--unsafe-transactions', '--master', undefined ] }
Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-07-11 13:04:21.701] [ERROR] EthereumNode - Failed to start node { Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  path: '/home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  spawnargs: [ '--unsafe-transactions', '--master', undefined ] }
Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-07-11 13:04:21.704] [ERROR] main - Error starting up node and/or syncing { Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  path: '/home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  spawnargs: [ '--unsafe-transactions', '--master', undefined ] }
Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-07-11 13:04:22.648] [INFO] updateChecker - App (v0.7.6) is out of date. New v0.8.0 found.
[2016-07-11 13:04:22.737] [INFO] Windows - Create popup window: updateAvailable
[2016-07-11 13:04:22.737] [INFO] Windows - Create secondary window: updateAvailable, owner: notset
[2016-07-11 13:04:23.689] [INFO] (ui: popup-no-web3) - Web3 not yet initialized, doing so now with HttpProvider.

![image](https://cloud.githubusercontent.com/assets/20372686/16730137/09603faa-4769-11e6-8da5-77d32d3f6248.png)

**Comment by uraxs** [comment]
,
  spawnargs: [ '--unsafe-transactions', '--master', undefined ] }
Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/Ў�/Ў� ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-07-11 13:15:34.606] [INFO] (ui: popup-no-web3) - Web3 not yet initialized, doing so now with HttpProvider.
[2016-07-11 13:17:00.675] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2016-07-11 13:17:00.678] [INFO] Sockets - Destroy all sockets
[2016-07-11 13:17:00.679] [INFO] Sockets/7 - Disconnecting...
[2016-07-11 13:17:00.687] [INFO] Sockets/node-ipc - Disconnecting...
[2016-07-11 13:17:00.695] [ERROR] main - Error shutting down sockets
[2016-07-11 13:17:01.196] [INFO] Sockets - Destroy all sockets
[2016-07-11 13:17:01.196] [INFO] Sockets/7 - Disconnecting...
[2016-07-11 13:17:01.201] [INFO] Windows - All primary windows closed/invisible, so quitting app...
[2016-07-11 13:17:01.201] [ERROR] main - Error shutting down sockets
[2016-07-11 13:17:01.213] [INFO] Windows - All primary windows closed/invisible, so quitting app...
g@g-All-Series ~/Ethereum-Wallet-linux64-0-7-6 $ 


-finally ended as this!

**Comment by luclu** [comment]
```bash
[2016-07-11 13:04:21.619] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-07-11 13:04:21.621] [INFO] EthereumNode - Node type: �dEF
[2016-07-11 13:04:21.621] [INFO] EthereumNode - Network: �uR�
[2016-07-11 13:04:21.621] [INFO] EthereumNode - Start node: �dEF �uR�
[2016-07-11 13:04:21.645] [INFO] EthereumNode - Node startup error
[2016-07-11 13:04:21.647] [ERROR] EthereumNode - Failed to start node { Error: spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  path: '/home/g/Ethereum-Wallet-linux64-0-7-6/resources/node/�dEF/�dEF',
  spawnargs: [ '--unsafe-transactions', '--master', undefined ] }
```

There seems to be some weird issue with your character encoding like with the `geth` name showing up as `�dEF`. 

What OS-flavour are you running? 
What is the output of `locale -a` and `localectl`?

**Comment by uraxs** [comment]
~ $ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

~ $ localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

linux mint w/ cinnamon 
kernel 3.19.0-61

**Comment by uraxs** [comment]
hey luclu...just a thought- would it help or hurt if I reinstall geth and download a fresh blockchain? or would I subsequently lose my ether? everything on my system seems normal yet it seems that when the crash happened something got corrupted in geth/ db

**Comment by luclu** [comment]
Yeah, you can try that. Start with the app only. Then the Mist folder under `%appdata%` followed by the Ethereum folder. Backup the `keystore` folder under the later.

**Comment by uraxs** [comment]
...ok, I backed up all relevant files (2 copies on different hdd's) and expunged the old, unzipped a fresh copy of 0.8.0, dropped in the keystore file and started the wallet...downloading new chaindata/ blocks now....we'll see if it all works and how good of magicians we are at the disappearing ether/ reappearing ether trick!? let you know how it works out

**Comment by uraxs** [comment]
touche'!...launch application.... *DING*  voila!!! thank you very much for your help @luclu
