### ISSUE TITLE
Mist browser chrashes when node.log is missing

### ISSUE THREAD

**Issue by fansari** [ethereum/mist#961]
Node type: geth
OS: linux
Network type: main
Mist version: 0.8.0 

When ~/.config/Mist/node.log is missing and I click at "Develop -> Show log file" the browser crashes with this error messages. The expected behaviour should be that the file is created.

``` javascript
/home/fansari/ether/Mist-linux64-0-8-0/resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filenam

TypeError: log.info is not a function
    at click (/home/fansari/ether/Mist-linux64-0-8-0/resources/app.asar/modules/menuItems.js:324:25)
    at MenuItem.click (/home/fansari/ether/Mist-linux64-0-8-0/resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/home/fansari/ether/Mist-linux64-0-8-0/resources/electron.asar/browser/api/menu.js:119:40)
```

**Comment by luclu** [comment]
This happens when geth is externally run and Mist attaches to it. As Mist is not evoking geth it won't pass its logs to the `node.log` file.

---

To circumvent this behaviour an alert could be displayed.

**Comment by alexvandesande** [comment]
@luclu can you take ownership of this?

**Comment by luclu** [comment]
Already fixed some time ago.
