### ISSUE TITLE
New Mist 0.8.1 makes the Geth.exe crash

### ISSUE THREAD

**Issue by holgerkpedersen** [ethereum/mist#999]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.8.1

geth delivered with the file "Ethereum-Wallet-win64-0-8-1.zip" seems to crash; when "mist" has opened.

Here is geth stated manually before calling Ethereum-Wallet.exe:
"
C:\Users\Holger\Downloads\Ethereum-Wallet-win64-0-8-1\resources\node\geth>geth --rpc console
I0719 16:37:55.126033 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\Holger\AppData\Roaming\Ethereum\chaindata
I0719 16:37:55.335260 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0719 16:37:55.337215 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0719 16:37:55.338193 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0719 16:37:55.339170 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0719 16:37:55.341125 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0719 16:37:55.344058 ethdb/database.go:169] closed db:C:\Users\Holger\AppData\Roaming\Ethereum\chaindata
I0719 16:37:55.346991 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\Holger\AppData\Roaming\Ethereum\chaindata
I0719 16:37:55.426368 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\Holger\AppData\Roaming\Ethereum\dapp
I0719 16:37:55.433211 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0719 16:37:55.434189 eth/backend.go:201] Blockchain DB Version: 3
I0719 16:37:55.437122 core/blockchain.go:206] Last header: #1914194 [d656f12b.] TD=39144340571395198538
I0719 16:37:55.438099 core/blockchain.go:207] Last block: #1914194 [d656f12b.] TD=39144340571395198538
I0719 16:37:55.439076 core/blockchain.go:208] Fast block: #1914194 [d656f12b.] TD=39144340571395198538
I0719 16:37:55.442009 p2p/server.go:313] Starting Server
I0719 16:37:57.298714 p2p/discover/udp.go:217] Listening, enode://2434268d8d2c50dd1458a680d9b9657eec90aab018f5366a0d8154aa8ffc6a7fcb15eabedcc6d0659600307d85f0801fb274ed7bf53655f3f218e014aa2d6bc9@[::]:30303
I0719 16:37:57.301672 p2p/server.go:556] Listening on [::]:30303
I0719 16:37:57.303627 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0719 16:37:57.304604 node/node.go:366] HTTP endpoint opened: http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Geth/v1.4.10-stable/windows/go1.6.2
coinbase: 0x33352bee22b6d06e796d60ee008fdaa04e7deb70
at block: 1914194 (Tue, 19 Jul 2016 16:32:18 CEST)
 datadir: C:\Users\Holger\AppData\Roaming\Ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.blockNumber
1914194
> I0719 16:38:17.301965 eth/downloader/downloader.go:320] Block synchronisation started
I0719 16:38:24.001486 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0719 16:39:00.165829 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0719 16:39:21.402988 eth/handler.go:295] Peer 0d1b9eed7afe2d58 [eth/63]: timed out DAO fork-check, dropping
I0719 16:39:37.258381 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0719 16:40:08.199858 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0719 16:40:26.575988 eth/handler.go:295] Peer a0983646e7626044 [eth/63]: timed out DAO fork-check, dropping
I0719 16:41:23.960104 eth/handler.go:295] Peer 9b3479addddd94a6 [eth/63]: timed out DAO fork-check, dropping
> eth.blockNumber
1914194
>
"

After starting 

"
> I0719 16:44:20.552680 eth/handler.go:295] Peer f2d6fd4ba38bdcf1 [eth/63]: timed out DAO fork-check, dropping
I0719 16:44:41.727509 eth/handler.go:295] Peer ff5ab154c1639f5c [eth/63]: timed out DAO fork-check, dropping
I0719 16:45:45.740796 eth/handler.go:295] Peer bb5b1691368cd66e [eth/63]: timed out DAO fork-check, dropping

> I0719 16:47:54.887283 eth/handler.go:295] Peer a0983646e7626044 [eth/63]: timed out DAO fork-check, dropping
I0719 16:48:50.275965 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 1.8587004s. #1914195 [9123ecfa / 9123ecfa]
I0719 16:48:53.880015 core/blockchain.go:963] imported 18 block(s) (0 queued 0 ignored) including 49 txs in 3.6020493s. #1914213 [994cdd22 / 63415a6b]
I0719 16:49:05.468671 core/blockchain.go:963] imported 45 block(s) (0 queued 0 ignored) including 289 txs in 11.4589408s. #1914258 [144cc7b2 / dfc80816]
I0719 16:49:10.396132 core/blockchain.go:963] imported 3 block(s) (0 queued 0 ignored) including 6 txs in 42.9566ms. #1914261 [92746a31 / 96fd0970]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x968a18]

goroutine 22334 [running]:
panic(0xeba9a0, 0xc082002090)
        C:/Go/src/runtime/panic.go:481 +0x3f4
github.com/ethereum/go-ethereum/eth/filters.(*Filter).bloomFilter(0xc090b60c00, 0x0, 0x1ed701249bd3c481)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:208 +0xf8
github.com/ethereum/go-ethereum/eth/filters.(*Filter).getLogs(0xc090b60c00, 0x1ae6b8, 0x1aea9f, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:137 +0x15e
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1b773f, 0x4, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:109 +0x398
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1b773f, 0x3, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1d3595, 0x2, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1d3595, 0x1, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1d3595, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).Find(0xc090b60c00, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:91 +0x1c4
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc08206c420, 0xc08cb14d20, 0x22, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/api.go:534 +0xf8
reflect.Value.call(0xdd08c0, 0xfbd6e8, 0x13, 0x100e310, 0x4, 0xc08cb14d80, 0x2, 0x2, 0x0, 0x0, ...)
        C:/Go/src/reflect/value.go:435 +0x1214
reflect.Value.Call(0xdd08c0, 0xfbd6e8, 0x13, 0xc08cb14d80, 0x2, 0x2, 0x0, 0x0, 0x0)
        C:/Go/src/reflect/value.go:303 +0xb8
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc0824cd020, 0x48c6ee0, 0xc08f5938c0, 0x4d022b8, 0xc092b9bc70, 0xc08be6e8c0, 0x0, 0x0, 0xc0823f7ea0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x1267
github.com/ethereum/go-ethereum/rpc.(*Server).execBatch(0xc0824cd020, 0x48c6ee0, 0xc08f5938c0, 0x4d022b8, 0xc092b9bc70, 0xc087731f58, 0x1, 0x1)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/rpc/server.go:369 +0x492
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/rpc/server.go:214 +0xc2a
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x968a18]

goroutine 22333 [running]:
panic(0xeba9a0, 0xc082002090)
        C:/Go/src/runtime/panic.go:481 +0x3f4
github.com/ethereum/go-ethereum/eth/filters.(*Filter).bloomFilter(0xc090b60c00, 0x0, 0x1ed701249bd3c481)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:208 +0xf8
github.com/ethereum/go-ethereum/eth/filters.(*Filter).getLogs(0xc090b60c00, 0x1ae6b8, 0x1aea9f, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:137 +0x15e
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1b773f, 0x4, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:109 +0x398
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1b773f, 0x3, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1d3595, 0x2, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1d3595, 0x1, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc090b60c00, 0x1ad4db, 0x1d3595, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x57b
github.com/ethereum/go-ethereum/eth/filters.(*Filter).Find(0xc090b60c00, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:91 +0x1c4
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc08206c420, 0xc08cb14bd0, 0x22, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/filters/api.go:534 +0xf8
reflect.Value.call(0xdd08c0, 0xfbd6e8, 0x13, 0x100e310, 0x4, 0xc08f80ea20, 0x2, 0x2, 0x0, 0x0, ...)
        C:/Go/src/reflect/value.go:435 +0x1214
reflect.Value.Call(0xdd08c0, 0xfbd6e8, 0x13, 0xc08f80ea20, 0x2, 0x2, 0x0, 0x0, 0x0)
        C:/Go/src/reflect/value.go:303 +0xb8
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc0824cd020, 0x48c6ee0, 0xc08f5938c0, 0x4d022b8, 0xc092b9bc70, 0xc08be6e850, 0x0, 0x0, 0xc0821506e0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x1267
github.com/ethereum/go-ethereum/rpc.(*Server).execBatch(0xc0824cd020, 0x48c6ee0, 0xc08f5938c0, 0x4d022b8, 0xc092b9bc70, 0xc087731f50, 0x1, 0x1)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/rpc/server.go:369 +0x492
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/rpc/server.go:214 +0xc2a

C:\Users\Holger\Downloads\Ethereum-Wallet-win64-0-8-1\resources\node\geth>pause
Press any key to continue . . .
"
![image](https://cloud.githubusercontent.com/assets/1609665/16954482/4d619b90-4dd1-11e6-8f95-220eacaf954a.png)

Add the following to issue, when possible:
[node.zip](https://github.com/ethereum/mist/files/371732/node.zip)

**Comment by luclu** [comment]
Thank you @holgerkpedersen, nice catch. Pinging @fjl

**Comment by frozeman** [comment]
@karalabe any idea?

**Comment by fjl** [comment]
@bas-vk is investigating this error

**Comment by Lietmotiv** [comment]
I had the same issue. My fix was to remove the db completely and start fresh. Took a little under 2 hours.  I am on OSX but this probably works on other platforms.

I just closed everything. Opened up command prompt 
`geth removedb`   
`geth --fast --maxpeers 99 --cache 1024 --jitvm`

I then opened Mist and watched the blocks count down pretty quickly. 

The max peers I think helped with the speed as I believe it defaults to 25 and just forcing it to refresh completely didn't take long.  I did it with Geth 1.5 dev but it should work with 1.4.10 too. Good luck.

**Comment by fredbuluku** [comment]
Enable web3 to accept in the system
